// Generated by jextract

package ai.pipestream.turbo.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct turbo_model_info {
 *     uint32_t struct_size;
 *     uint32_t task;
 *     uint32_t kind;
 *     uint32_t modality;
 *     uint32_t dim;
 *     uint32_t n_labels;
 *     uint32_t pooling;
 *     uint32_t normalize;
 *     uint32_t max_seq;
 *     uint32_t max_batch;
 *     uint32_t dtype_used;
 *     uint32_t fully_accelerated;
 *     uint32_t stage_placement[5];
 *     uint32_t n_inputs;
 *     uint32_t n_outputs;
 *     uint32_t vocab_size;
 *     char model_id[128];
 *     char revision[64];
 *     char tokenizer_sha256[72];
 *     char provider_id[32];
 *     char prefix_query[128];
 *     char prefix_document[128];
 * }
 * }
 */
public class turbo_model_info {

    turbo_model_info() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        TurboNative.C_INT.withName("struct_size"),
        TurboNative.C_INT.withName("task"),
        TurboNative.C_INT.withName("kind"),
        TurboNative.C_INT.withName("modality"),
        TurboNative.C_INT.withName("dim"),
        TurboNative.C_INT.withName("n_labels"),
        TurboNative.C_INT.withName("pooling"),
        TurboNative.C_INT.withName("normalize"),
        TurboNative.C_INT.withName("max_seq"),
        TurboNative.C_INT.withName("max_batch"),
        TurboNative.C_INT.withName("dtype_used"),
        TurboNative.C_INT.withName("fully_accelerated"),
        MemoryLayout.sequenceLayout(5, TurboNative.C_INT).withName("stage_placement"),
        TurboNative.C_INT.withName("n_inputs"),
        TurboNative.C_INT.withName("n_outputs"),
        TurboNative.C_INT.withName("vocab_size"),
        MemoryLayout.sequenceLayout(128, TurboNative.C_CHAR).withName("model_id"),
        MemoryLayout.sequenceLayout(64, TurboNative.C_CHAR).withName("revision"),
        MemoryLayout.sequenceLayout(72, TurboNative.C_CHAR).withName("tokenizer_sha256"),
        MemoryLayout.sequenceLayout(32, TurboNative.C_CHAR).withName("provider_id"),
        MemoryLayout.sequenceLayout(128, TurboNative.C_CHAR).withName("prefix_query"),
        MemoryLayout.sequenceLayout(128, TurboNative.C_CHAR).withName("prefix_document")
    ).withName("turbo_model_info");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt struct_size$LAYOUT = (OfInt)$LAYOUT.select(groupElement("struct_size"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t struct_size
     * }
     */
    public static final OfInt struct_size$layout() {
        return struct_size$LAYOUT;
    }

    private static final long struct_size$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t struct_size
     * }
     */
    public static final long struct_size$offset() {
        return struct_size$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t struct_size
     * }
     */
    public static int struct_size(MemorySegment struct) {
        return struct.get(struct_size$LAYOUT, struct_size$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t struct_size
     * }
     */
    public static void struct_size(MemorySegment struct, int fieldValue) {
        struct.set(struct_size$LAYOUT, struct_size$OFFSET, fieldValue);
    }

    private static final OfInt task$LAYOUT = (OfInt)$LAYOUT.select(groupElement("task"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t task
     * }
     */
    public static final OfInt task$layout() {
        return task$LAYOUT;
    }

    private static final long task$OFFSET = 4;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t task
     * }
     */
    public static final long task$offset() {
        return task$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t task
     * }
     */
    public static int task(MemorySegment struct) {
        return struct.get(task$LAYOUT, task$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t task
     * }
     */
    public static void task(MemorySegment struct, int fieldValue) {
        struct.set(task$LAYOUT, task$OFFSET, fieldValue);
    }

    private static final OfInt kind$LAYOUT = (OfInt)$LAYOUT.select(groupElement("kind"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t kind
     * }
     */
    public static final OfInt kind$layout() {
        return kind$LAYOUT;
    }

    private static final long kind$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t kind
     * }
     */
    public static final long kind$offset() {
        return kind$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t kind
     * }
     */
    public static int kind(MemorySegment struct) {
        return struct.get(kind$LAYOUT, kind$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t kind
     * }
     */
    public static void kind(MemorySegment struct, int fieldValue) {
        struct.set(kind$LAYOUT, kind$OFFSET, fieldValue);
    }

    private static final OfInt modality$LAYOUT = (OfInt)$LAYOUT.select(groupElement("modality"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t modality
     * }
     */
    public static final OfInt modality$layout() {
        return modality$LAYOUT;
    }

    private static final long modality$OFFSET = 12;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t modality
     * }
     */
    public static final long modality$offset() {
        return modality$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t modality
     * }
     */
    public static int modality(MemorySegment struct) {
        return struct.get(modality$LAYOUT, modality$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t modality
     * }
     */
    public static void modality(MemorySegment struct, int fieldValue) {
        struct.set(modality$LAYOUT, modality$OFFSET, fieldValue);
    }

    private static final OfInt dim$LAYOUT = (OfInt)$LAYOUT.select(groupElement("dim"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t dim
     * }
     */
    public static final OfInt dim$layout() {
        return dim$LAYOUT;
    }

    private static final long dim$OFFSET = 16;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t dim
     * }
     */
    public static final long dim$offset() {
        return dim$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t dim
     * }
     */
    public static int dim(MemorySegment struct) {
        return struct.get(dim$LAYOUT, dim$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t dim
     * }
     */
    public static void dim(MemorySegment struct, int fieldValue) {
        struct.set(dim$LAYOUT, dim$OFFSET, fieldValue);
    }

    private static final OfInt n_labels$LAYOUT = (OfInt)$LAYOUT.select(groupElement("n_labels"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t n_labels
     * }
     */
    public static final OfInt n_labels$layout() {
        return n_labels$LAYOUT;
    }

    private static final long n_labels$OFFSET = 20;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t n_labels
     * }
     */
    public static final long n_labels$offset() {
        return n_labels$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t n_labels
     * }
     */
    public static int n_labels(MemorySegment struct) {
        return struct.get(n_labels$LAYOUT, n_labels$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t n_labels
     * }
     */
    public static void n_labels(MemorySegment struct, int fieldValue) {
        struct.set(n_labels$LAYOUT, n_labels$OFFSET, fieldValue);
    }

    private static final OfInt pooling$LAYOUT = (OfInt)$LAYOUT.select(groupElement("pooling"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t pooling
     * }
     */
    public static final OfInt pooling$layout() {
        return pooling$LAYOUT;
    }

    private static final long pooling$OFFSET = 24;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t pooling
     * }
     */
    public static final long pooling$offset() {
        return pooling$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t pooling
     * }
     */
    public static int pooling(MemorySegment struct) {
        return struct.get(pooling$LAYOUT, pooling$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t pooling
     * }
     */
    public static void pooling(MemorySegment struct, int fieldValue) {
        struct.set(pooling$LAYOUT, pooling$OFFSET, fieldValue);
    }

    private static final OfInt normalize$LAYOUT = (OfInt)$LAYOUT.select(groupElement("normalize"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t normalize
     * }
     */
    public static final OfInt normalize$layout() {
        return normalize$LAYOUT;
    }

    private static final long normalize$OFFSET = 28;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t normalize
     * }
     */
    public static final long normalize$offset() {
        return normalize$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t normalize
     * }
     */
    public static int normalize(MemorySegment struct) {
        return struct.get(normalize$LAYOUT, normalize$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t normalize
     * }
     */
    public static void normalize(MemorySegment struct, int fieldValue) {
        struct.set(normalize$LAYOUT, normalize$OFFSET, fieldValue);
    }

    private static final OfInt max_seq$LAYOUT = (OfInt)$LAYOUT.select(groupElement("max_seq"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t max_seq
     * }
     */
    public static final OfInt max_seq$layout() {
        return max_seq$LAYOUT;
    }

    private static final long max_seq$OFFSET = 32;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t max_seq
     * }
     */
    public static final long max_seq$offset() {
        return max_seq$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t max_seq
     * }
     */
    public static int max_seq(MemorySegment struct) {
        return struct.get(max_seq$LAYOUT, max_seq$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t max_seq
     * }
     */
    public static void max_seq(MemorySegment struct, int fieldValue) {
        struct.set(max_seq$LAYOUT, max_seq$OFFSET, fieldValue);
    }

    private static final OfInt max_batch$LAYOUT = (OfInt)$LAYOUT.select(groupElement("max_batch"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t max_batch
     * }
     */
    public static final OfInt max_batch$layout() {
        return max_batch$LAYOUT;
    }

    private static final long max_batch$OFFSET = 36;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t max_batch
     * }
     */
    public static final long max_batch$offset() {
        return max_batch$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t max_batch
     * }
     */
    public static int max_batch(MemorySegment struct) {
        return struct.get(max_batch$LAYOUT, max_batch$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t max_batch
     * }
     */
    public static void max_batch(MemorySegment struct, int fieldValue) {
        struct.set(max_batch$LAYOUT, max_batch$OFFSET, fieldValue);
    }

    private static final OfInt dtype_used$LAYOUT = (OfInt)$LAYOUT.select(groupElement("dtype_used"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t dtype_used
     * }
     */
    public static final OfInt dtype_used$layout() {
        return dtype_used$LAYOUT;
    }

    private static final long dtype_used$OFFSET = 40;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t dtype_used
     * }
     */
    public static final long dtype_used$offset() {
        return dtype_used$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t dtype_used
     * }
     */
    public static int dtype_used(MemorySegment struct) {
        return struct.get(dtype_used$LAYOUT, dtype_used$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t dtype_used
     * }
     */
    public static void dtype_used(MemorySegment struct, int fieldValue) {
        struct.set(dtype_used$LAYOUT, dtype_used$OFFSET, fieldValue);
    }

    private static final OfInt fully_accelerated$LAYOUT = (OfInt)$LAYOUT.select(groupElement("fully_accelerated"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t fully_accelerated
     * }
     */
    public static final OfInt fully_accelerated$layout() {
        return fully_accelerated$LAYOUT;
    }

    private static final long fully_accelerated$OFFSET = 44;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t fully_accelerated
     * }
     */
    public static final long fully_accelerated$offset() {
        return fully_accelerated$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t fully_accelerated
     * }
     */
    public static int fully_accelerated(MemorySegment struct) {
        return struct.get(fully_accelerated$LAYOUT, fully_accelerated$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t fully_accelerated
     * }
     */
    public static void fully_accelerated(MemorySegment struct, int fieldValue) {
        struct.set(fully_accelerated$LAYOUT, fully_accelerated$OFFSET, fieldValue);
    }

    private static final SequenceLayout stage_placement$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("stage_placement"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t stage_placement[5]
     * }
     */
    public static final SequenceLayout stage_placement$layout() {
        return stage_placement$LAYOUT;
    }

    private static final long stage_placement$OFFSET = 48;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t stage_placement[5]
     * }
     */
    public static final long stage_placement$offset() {
        return stage_placement$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t stage_placement[5]
     * }
     */
    public static MemorySegment stage_placement(MemorySegment struct) {
        return struct.asSlice(stage_placement$OFFSET, stage_placement$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t stage_placement[5]
     * }
     */
    public static void stage_placement(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, stage_placement$OFFSET, stage_placement$LAYOUT.byteSize());
    }

    private static long[] stage_placement$DIMS = { 5 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * uint32_t stage_placement[5]
     * }
     */
    public static long[] stage_placement$dimensions() {
        return stage_placement$DIMS;
    }
    private static final VarHandle stage_placement$ELEM_HANDLE = stage_placement$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * uint32_t stage_placement[5]
     * }
     */
    public static int stage_placement(MemorySegment struct, long index0) {
        return stage_placement(struct).getAtIndex(JAVA_INT, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * uint32_t stage_placement[5]
     * }
     */
    public static void stage_placement(MemorySegment struct, long index0, int fieldValue) {
        stage_placement(struct).setAtIndex(JAVA_INT, index0, fieldValue);
    }

    private static final OfInt n_inputs$LAYOUT = (OfInt)$LAYOUT.select(groupElement("n_inputs"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t n_inputs
     * }
     */
    public static final OfInt n_inputs$layout() {
        return n_inputs$LAYOUT;
    }

    private static final long n_inputs$OFFSET = 68;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t n_inputs
     * }
     */
    public static final long n_inputs$offset() {
        return n_inputs$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t n_inputs
     * }
     */
    public static int n_inputs(MemorySegment struct) {
        return struct.get(n_inputs$LAYOUT, n_inputs$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t n_inputs
     * }
     */
    public static void n_inputs(MemorySegment struct, int fieldValue) {
        struct.set(n_inputs$LAYOUT, n_inputs$OFFSET, fieldValue);
    }

    private static final OfInt n_outputs$LAYOUT = (OfInt)$LAYOUT.select(groupElement("n_outputs"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t n_outputs
     * }
     */
    public static final OfInt n_outputs$layout() {
        return n_outputs$LAYOUT;
    }

    private static final long n_outputs$OFFSET = 72;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t n_outputs
     * }
     */
    public static final long n_outputs$offset() {
        return n_outputs$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t n_outputs
     * }
     */
    public static int n_outputs(MemorySegment struct) {
        return struct.get(n_outputs$LAYOUT, n_outputs$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t n_outputs
     * }
     */
    public static void n_outputs(MemorySegment struct, int fieldValue) {
        struct.set(n_outputs$LAYOUT, n_outputs$OFFSET, fieldValue);
    }

    private static final OfInt vocab_size$LAYOUT = (OfInt)$LAYOUT.select(groupElement("vocab_size"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t vocab_size
     * }
     */
    public static final OfInt vocab_size$layout() {
        return vocab_size$LAYOUT;
    }

    private static final long vocab_size$OFFSET = 76;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t vocab_size
     * }
     */
    public static final long vocab_size$offset() {
        return vocab_size$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t vocab_size
     * }
     */
    public static int vocab_size(MemorySegment struct) {
        return struct.get(vocab_size$LAYOUT, vocab_size$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t vocab_size
     * }
     */
    public static void vocab_size(MemorySegment struct, int fieldValue) {
        struct.set(vocab_size$LAYOUT, vocab_size$OFFSET, fieldValue);
    }

    private static final SequenceLayout model_id$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("model_id"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * char model_id[128]
     * }
     */
    public static final SequenceLayout model_id$layout() {
        return model_id$LAYOUT;
    }

    private static final long model_id$OFFSET = 80;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * char model_id[128]
     * }
     */
    public static final long model_id$offset() {
        return model_id$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * char model_id[128]
     * }
     */
    public static MemorySegment model_id(MemorySegment struct) {
        return struct.asSlice(model_id$OFFSET, model_id$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * char model_id[128]
     * }
     */
    public static void model_id(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, model_id$OFFSET, model_id$LAYOUT.byteSize());
    }

    private static long[] model_id$DIMS = { 128 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * char model_id[128]
     * }
     */
    public static long[] model_id$dimensions() {
        return model_id$DIMS;
    }
    private static final VarHandle model_id$ELEM_HANDLE = model_id$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * char model_id[128]
     * }
     */
    public static byte model_id(MemorySegment struct, long index0) {
        return model_id(struct).getAtIndex(JAVA_BYTE, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * char model_id[128]
     * }
     */
    public static void model_id(MemorySegment struct, long index0, byte fieldValue) {
        model_id(struct).setAtIndex(JAVA_BYTE, index0, fieldValue);
    }

    private static final SequenceLayout revision$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("revision"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * char revision[64]
     * }
     */
    public static final SequenceLayout revision$layout() {
        return revision$LAYOUT;
    }

    private static final long revision$OFFSET = 208;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * char revision[64]
     * }
     */
    public static final long revision$offset() {
        return revision$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * char revision[64]
     * }
     */
    public static MemorySegment revision(MemorySegment struct) {
        return struct.asSlice(revision$OFFSET, revision$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * char revision[64]
     * }
     */
    public static void revision(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, revision$OFFSET, revision$LAYOUT.byteSize());
    }

    private static long[] revision$DIMS = { 64 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * char revision[64]
     * }
     */
    public static long[] revision$dimensions() {
        return revision$DIMS;
    }
    private static final VarHandle revision$ELEM_HANDLE = revision$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * char revision[64]
     * }
     */
    public static byte revision(MemorySegment struct, long index0) {
        return revision(struct).getAtIndex(JAVA_BYTE, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * char revision[64]
     * }
     */
    public static void revision(MemorySegment struct, long index0, byte fieldValue) {
        revision(struct).setAtIndex(JAVA_BYTE, index0, fieldValue);
    }

    private static final SequenceLayout tokenizer_sha256$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("tokenizer_sha256"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * char tokenizer_sha256[72]
     * }
     */
    public static final SequenceLayout tokenizer_sha256$layout() {
        return tokenizer_sha256$LAYOUT;
    }

    private static final long tokenizer_sha256$OFFSET = 272;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * char tokenizer_sha256[72]
     * }
     */
    public static final long tokenizer_sha256$offset() {
        return tokenizer_sha256$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * char tokenizer_sha256[72]
     * }
     */
    public static MemorySegment tokenizer_sha256(MemorySegment struct) {
        return struct.asSlice(tokenizer_sha256$OFFSET, tokenizer_sha256$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * char tokenizer_sha256[72]
     * }
     */
    public static void tokenizer_sha256(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, tokenizer_sha256$OFFSET, tokenizer_sha256$LAYOUT.byteSize());
    }

    private static long[] tokenizer_sha256$DIMS = { 72 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * char tokenizer_sha256[72]
     * }
     */
    public static long[] tokenizer_sha256$dimensions() {
        return tokenizer_sha256$DIMS;
    }
    private static final VarHandle tokenizer_sha256$ELEM_HANDLE = tokenizer_sha256$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * char tokenizer_sha256[72]
     * }
     */
    public static byte tokenizer_sha256(MemorySegment struct, long index0) {
        return tokenizer_sha256(struct).getAtIndex(JAVA_BYTE, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * char tokenizer_sha256[72]
     * }
     */
    public static void tokenizer_sha256(MemorySegment struct, long index0, byte fieldValue) {
        tokenizer_sha256(struct).setAtIndex(JAVA_BYTE, index0, fieldValue);
    }

    private static final SequenceLayout provider_id$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("provider_id"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * char provider_id[32]
     * }
     */
    public static final SequenceLayout provider_id$layout() {
        return provider_id$LAYOUT;
    }

    private static final long provider_id$OFFSET = 344;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * char provider_id[32]
     * }
     */
    public static final long provider_id$offset() {
        return provider_id$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * char provider_id[32]
     * }
     */
    public static MemorySegment provider_id(MemorySegment struct) {
        return struct.asSlice(provider_id$OFFSET, provider_id$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * char provider_id[32]
     * }
     */
    public static void provider_id(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, provider_id$OFFSET, provider_id$LAYOUT.byteSize());
    }

    private static long[] provider_id$DIMS = { 32 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * char provider_id[32]
     * }
     */
    public static long[] provider_id$dimensions() {
        return provider_id$DIMS;
    }
    private static final VarHandle provider_id$ELEM_HANDLE = provider_id$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * char provider_id[32]
     * }
     */
    public static byte provider_id(MemorySegment struct, long index0) {
        return provider_id(struct).getAtIndex(JAVA_BYTE, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * char provider_id[32]
     * }
     */
    public static void provider_id(MemorySegment struct, long index0, byte fieldValue) {
        provider_id(struct).setAtIndex(JAVA_BYTE, index0, fieldValue);
    }

    private static final SequenceLayout prefix_query$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("prefix_query"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * char prefix_query[128]
     * }
     */
    public static final SequenceLayout prefix_query$layout() {
        return prefix_query$LAYOUT;
    }

    private static final long prefix_query$OFFSET = 376;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * char prefix_query[128]
     * }
     */
    public static final long prefix_query$offset() {
        return prefix_query$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * char prefix_query[128]
     * }
     */
    public static MemorySegment prefix_query(MemorySegment struct) {
        return struct.asSlice(prefix_query$OFFSET, prefix_query$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * char prefix_query[128]
     * }
     */
    public static void prefix_query(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, prefix_query$OFFSET, prefix_query$LAYOUT.byteSize());
    }

    private static long[] prefix_query$DIMS = { 128 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * char prefix_query[128]
     * }
     */
    public static long[] prefix_query$dimensions() {
        return prefix_query$DIMS;
    }
    private static final VarHandle prefix_query$ELEM_HANDLE = prefix_query$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * char prefix_query[128]
     * }
     */
    public static byte prefix_query(MemorySegment struct, long index0) {
        return prefix_query(struct).getAtIndex(JAVA_BYTE, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * char prefix_query[128]
     * }
     */
    public static void prefix_query(MemorySegment struct, long index0, byte fieldValue) {
        prefix_query(struct).setAtIndex(JAVA_BYTE, index0, fieldValue);
    }

    private static final SequenceLayout prefix_document$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("prefix_document"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * char prefix_document[128]
     * }
     */
    public static final SequenceLayout prefix_document$layout() {
        return prefix_document$LAYOUT;
    }

    private static final long prefix_document$OFFSET = 504;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * char prefix_document[128]
     * }
     */
    public static final long prefix_document$offset() {
        return prefix_document$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * char prefix_document[128]
     * }
     */
    public static MemorySegment prefix_document(MemorySegment struct) {
        return struct.asSlice(prefix_document$OFFSET, prefix_document$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * char prefix_document[128]
     * }
     */
    public static void prefix_document(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, prefix_document$OFFSET, prefix_document$LAYOUT.byteSize());
    }

    private static long[] prefix_document$DIMS = { 128 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * char prefix_document[128]
     * }
     */
    public static long[] prefix_document$dimensions() {
        return prefix_document$DIMS;
    }
    private static final VarHandle prefix_document$ELEM_HANDLE = prefix_document$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * char prefix_document[128]
     * }
     */
    public static byte prefix_document(MemorySegment struct, long index0) {
        return prefix_document(struct).getAtIndex(JAVA_BYTE, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * char prefix_document[128]
     * }
     */
    public static void prefix_document(MemorySegment struct, long index0, byte fieldValue) {
        prefix_document(struct).setAtIndex(JAVA_BYTE, index0, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

