// Generated by jextract

package ai.pipestream.turbo.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef uint32_t (*turbo_stream_fn)(void *, const struct turbo_generation_chunk {
 *     uint32_t struct_size;
 *     uint32_t sequence;
 *     uint32_t n_tokens;
 *     uint32_t n_logprobs;
 *     const int32_t *tokens;
 *     struct turbo_text text;
 *     const float *logprobs;
 *     uint32_t done;
 *     uint32_t finish_reason;
 *     uint32_t prompt_tokens;
 *     uint32_t generated_tokens;
 * } *)
 * }
 */
public class turbo_stream_fn {

    turbo_stream_fn() {
        // Should not be called directly
    }

    /**
     * The function pointer signature, expressed as a functional interface
     */
    public interface Function {
        int apply(MemorySegment user_data, MemorySegment chunk);
    }

    private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
        TurboNative.C_INT,
        TurboNative.C_POINTER,
        TurboNative.C_POINTER
    );

    /**
     * The descriptor of this function pointer
     */
    public static FunctionDescriptor descriptor() {
        return $DESC;
    }

    private static final MethodHandle UP$MH = TurboNative.upcallHandle(turbo_stream_fn.Function.class, "apply", $DESC);

    /**
     * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
     * The lifetime of the returned segment is managed by {@code arena}
     */
    public static MemorySegment allocate(turbo_stream_fn.Function fi, Arena arena) {
        return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
    }

    private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

    /**
     * Invoke the upcall stub {@code funcPtr}, with given parameters
     */
    public static int invoke(MemorySegment funcPtr,MemorySegment user_data, MemorySegment chunk) {
        try {
            return (int) DOWN$MH.invokeExact(funcPtr, user_data, chunk);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
}

