// Generated by jextract

package ai.pipestream.turbo.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct turbo_tokenizer_info {
 *     uint32_t struct_size;
 *     uint32_t vocab_size;
 *     uint32_t max_seq;
 *     uint32_t specials_per_sequence;
 *     int32_t pad_id;
 *     int32_t bos_id;
 *     int32_t eos_id;
 *     int32_t unk_id;
 *     char kind[32];
 *     char sha256[72];
 * }
 * }
 */
public class turbo_tokenizer_info {

    turbo_tokenizer_info() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        TurboNative.C_INT.withName("struct_size"),
        TurboNative.C_INT.withName("vocab_size"),
        TurboNative.C_INT.withName("max_seq"),
        TurboNative.C_INT.withName("specials_per_sequence"),
        TurboNative.C_INT.withName("pad_id"),
        TurboNative.C_INT.withName("bos_id"),
        TurboNative.C_INT.withName("eos_id"),
        TurboNative.C_INT.withName("unk_id"),
        MemoryLayout.sequenceLayout(32, TurboNative.C_CHAR).withName("kind"),
        MemoryLayout.sequenceLayout(72, TurboNative.C_CHAR).withName("sha256")
    ).withName("turbo_tokenizer_info");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt struct_size$LAYOUT = (OfInt)$LAYOUT.select(groupElement("struct_size"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t struct_size
     * }
     */
    public static final OfInt struct_size$layout() {
        return struct_size$LAYOUT;
    }

    private static final long struct_size$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t struct_size
     * }
     */
    public static final long struct_size$offset() {
        return struct_size$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t struct_size
     * }
     */
    public static int struct_size(MemorySegment struct) {
        return struct.get(struct_size$LAYOUT, struct_size$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t struct_size
     * }
     */
    public static void struct_size(MemorySegment struct, int fieldValue) {
        struct.set(struct_size$LAYOUT, struct_size$OFFSET, fieldValue);
    }

    private static final OfInt vocab_size$LAYOUT = (OfInt)$LAYOUT.select(groupElement("vocab_size"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t vocab_size
     * }
     */
    public static final OfInt vocab_size$layout() {
        return vocab_size$LAYOUT;
    }

    private static final long vocab_size$OFFSET = 4;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t vocab_size
     * }
     */
    public static final long vocab_size$offset() {
        return vocab_size$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t vocab_size
     * }
     */
    public static int vocab_size(MemorySegment struct) {
        return struct.get(vocab_size$LAYOUT, vocab_size$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t vocab_size
     * }
     */
    public static void vocab_size(MemorySegment struct, int fieldValue) {
        struct.set(vocab_size$LAYOUT, vocab_size$OFFSET, fieldValue);
    }

    private static final OfInt max_seq$LAYOUT = (OfInt)$LAYOUT.select(groupElement("max_seq"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t max_seq
     * }
     */
    public static final OfInt max_seq$layout() {
        return max_seq$LAYOUT;
    }

    private static final long max_seq$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t max_seq
     * }
     */
    public static final long max_seq$offset() {
        return max_seq$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t max_seq
     * }
     */
    public static int max_seq(MemorySegment struct) {
        return struct.get(max_seq$LAYOUT, max_seq$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t max_seq
     * }
     */
    public static void max_seq(MemorySegment struct, int fieldValue) {
        struct.set(max_seq$LAYOUT, max_seq$OFFSET, fieldValue);
    }

    private static final OfInt specials_per_sequence$LAYOUT = (OfInt)$LAYOUT.select(groupElement("specials_per_sequence"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t specials_per_sequence
     * }
     */
    public static final OfInt specials_per_sequence$layout() {
        return specials_per_sequence$LAYOUT;
    }

    private static final long specials_per_sequence$OFFSET = 12;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t specials_per_sequence
     * }
     */
    public static final long specials_per_sequence$offset() {
        return specials_per_sequence$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t specials_per_sequence
     * }
     */
    public static int specials_per_sequence(MemorySegment struct) {
        return struct.get(specials_per_sequence$LAYOUT, specials_per_sequence$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t specials_per_sequence
     * }
     */
    public static void specials_per_sequence(MemorySegment struct, int fieldValue) {
        struct.set(specials_per_sequence$LAYOUT, specials_per_sequence$OFFSET, fieldValue);
    }

    private static final OfInt pad_id$LAYOUT = (OfInt)$LAYOUT.select(groupElement("pad_id"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int32_t pad_id
     * }
     */
    public static final OfInt pad_id$layout() {
        return pad_id$LAYOUT;
    }

    private static final long pad_id$OFFSET = 16;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int32_t pad_id
     * }
     */
    public static final long pad_id$offset() {
        return pad_id$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int32_t pad_id
     * }
     */
    public static int pad_id(MemorySegment struct) {
        return struct.get(pad_id$LAYOUT, pad_id$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int32_t pad_id
     * }
     */
    public static void pad_id(MemorySegment struct, int fieldValue) {
        struct.set(pad_id$LAYOUT, pad_id$OFFSET, fieldValue);
    }

    private static final OfInt bos_id$LAYOUT = (OfInt)$LAYOUT.select(groupElement("bos_id"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int32_t bos_id
     * }
     */
    public static final OfInt bos_id$layout() {
        return bos_id$LAYOUT;
    }

    private static final long bos_id$OFFSET = 20;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int32_t bos_id
     * }
     */
    public static final long bos_id$offset() {
        return bos_id$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int32_t bos_id
     * }
     */
    public static int bos_id(MemorySegment struct) {
        return struct.get(bos_id$LAYOUT, bos_id$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int32_t bos_id
     * }
     */
    public static void bos_id(MemorySegment struct, int fieldValue) {
        struct.set(bos_id$LAYOUT, bos_id$OFFSET, fieldValue);
    }

    private static final OfInt eos_id$LAYOUT = (OfInt)$LAYOUT.select(groupElement("eos_id"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int32_t eos_id
     * }
     */
    public static final OfInt eos_id$layout() {
        return eos_id$LAYOUT;
    }

    private static final long eos_id$OFFSET = 24;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int32_t eos_id
     * }
     */
    public static final long eos_id$offset() {
        return eos_id$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int32_t eos_id
     * }
     */
    public static int eos_id(MemorySegment struct) {
        return struct.get(eos_id$LAYOUT, eos_id$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int32_t eos_id
     * }
     */
    public static void eos_id(MemorySegment struct, int fieldValue) {
        struct.set(eos_id$LAYOUT, eos_id$OFFSET, fieldValue);
    }

    private static final OfInt unk_id$LAYOUT = (OfInt)$LAYOUT.select(groupElement("unk_id"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int32_t unk_id
     * }
     */
    public static final OfInt unk_id$layout() {
        return unk_id$LAYOUT;
    }

    private static final long unk_id$OFFSET = 28;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int32_t unk_id
     * }
     */
    public static final long unk_id$offset() {
        return unk_id$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int32_t unk_id
     * }
     */
    public static int unk_id(MemorySegment struct) {
        return struct.get(unk_id$LAYOUT, unk_id$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int32_t unk_id
     * }
     */
    public static void unk_id(MemorySegment struct, int fieldValue) {
        struct.set(unk_id$LAYOUT, unk_id$OFFSET, fieldValue);
    }

    private static final SequenceLayout kind$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("kind"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * char kind[32]
     * }
     */
    public static final SequenceLayout kind$layout() {
        return kind$LAYOUT;
    }

    private static final long kind$OFFSET = 32;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * char kind[32]
     * }
     */
    public static final long kind$offset() {
        return kind$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * char kind[32]
     * }
     */
    public static MemorySegment kind(MemorySegment struct) {
        return struct.asSlice(kind$OFFSET, kind$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * char kind[32]
     * }
     */
    public static void kind(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, kind$OFFSET, kind$LAYOUT.byteSize());
    }

    private static long[] kind$DIMS = { 32 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * char kind[32]
     * }
     */
    public static long[] kind$dimensions() {
        return kind$DIMS;
    }
    private static final VarHandle kind$ELEM_HANDLE = kind$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * char kind[32]
     * }
     */
    public static byte kind(MemorySegment struct, long index0) {
        return kind(struct).getAtIndex(JAVA_BYTE, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * char kind[32]
     * }
     */
    public static void kind(MemorySegment struct, long index0, byte fieldValue) {
        kind(struct).setAtIndex(JAVA_BYTE, index0, fieldValue);
    }

    private static final SequenceLayout sha256$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("sha256"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * char sha256[72]
     * }
     */
    public static final SequenceLayout sha256$layout() {
        return sha256$LAYOUT;
    }

    private static final long sha256$OFFSET = 64;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * char sha256[72]
     * }
     */
    public static final long sha256$offset() {
        return sha256$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * char sha256[72]
     * }
     */
    public static MemorySegment sha256(MemorySegment struct) {
        return struct.asSlice(sha256$OFFSET, sha256$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * char sha256[72]
     * }
     */
    public static void sha256(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, sha256$OFFSET, sha256$LAYOUT.byteSize());
    }

    private static long[] sha256$DIMS = { 72 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * char sha256[72]
     * }
     */
    public static long[] sha256$dimensions() {
        return sha256$DIMS;
    }
    private static final VarHandle sha256$ELEM_HANDLE = sha256$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * char sha256[72]
     * }
     */
    public static byte sha256(MemorySegment struct, long index0) {
        return sha256(struct).getAtIndex(JAVA_BYTE, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * char sha256[72]
     * }
     */
    public static void sha256(MemorySegment struct, long index0, byte fieldValue) {
        sha256(struct).setAtIndex(JAVA_BYTE, index0, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

