// Generated by jextract

package ai.pipestream.turbo.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct turbo_token_batch {
 *     uint32_t struct_size;
 *     uint32_t batch;
 *     uint32_t seq;
 *     uint32_t row_stride;
 *     const int32_t *ids;
 *     const int32_t *mask;
 *     const int32_t *types;
 * }
 * }
 */
public class turbo_token_batch {

    turbo_token_batch() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        TurboNative.C_INT.withName("struct_size"),
        TurboNative.C_INT.withName("batch"),
        TurboNative.C_INT.withName("seq"),
        TurboNative.C_INT.withName("row_stride"),
        TurboNative.C_POINTER.withName("ids"),
        TurboNative.C_POINTER.withName("mask"),
        TurboNative.C_POINTER.withName("types")
    ).withName("turbo_token_batch");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt struct_size$LAYOUT = (OfInt)$LAYOUT.select(groupElement("struct_size"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t struct_size
     * }
     */
    public static final OfInt struct_size$layout() {
        return struct_size$LAYOUT;
    }

    private static final long struct_size$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t struct_size
     * }
     */
    public static final long struct_size$offset() {
        return struct_size$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t struct_size
     * }
     */
    public static int struct_size(MemorySegment struct) {
        return struct.get(struct_size$LAYOUT, struct_size$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t struct_size
     * }
     */
    public static void struct_size(MemorySegment struct, int fieldValue) {
        struct.set(struct_size$LAYOUT, struct_size$OFFSET, fieldValue);
    }

    private static final OfInt batch$LAYOUT = (OfInt)$LAYOUT.select(groupElement("batch"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t batch
     * }
     */
    public static final OfInt batch$layout() {
        return batch$LAYOUT;
    }

    private static final long batch$OFFSET = 4;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t batch
     * }
     */
    public static final long batch$offset() {
        return batch$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t batch
     * }
     */
    public static int batch(MemorySegment struct) {
        return struct.get(batch$LAYOUT, batch$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t batch
     * }
     */
    public static void batch(MemorySegment struct, int fieldValue) {
        struct.set(batch$LAYOUT, batch$OFFSET, fieldValue);
    }

    private static final OfInt seq$LAYOUT = (OfInt)$LAYOUT.select(groupElement("seq"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t seq
     * }
     */
    public static final OfInt seq$layout() {
        return seq$LAYOUT;
    }

    private static final long seq$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t seq
     * }
     */
    public static final long seq$offset() {
        return seq$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t seq
     * }
     */
    public static int seq(MemorySegment struct) {
        return struct.get(seq$LAYOUT, seq$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t seq
     * }
     */
    public static void seq(MemorySegment struct, int fieldValue) {
        struct.set(seq$LAYOUT, seq$OFFSET, fieldValue);
    }

    private static final OfInt row_stride$LAYOUT = (OfInt)$LAYOUT.select(groupElement("row_stride"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t row_stride
     * }
     */
    public static final OfInt row_stride$layout() {
        return row_stride$LAYOUT;
    }

    private static final long row_stride$OFFSET = 12;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t row_stride
     * }
     */
    public static final long row_stride$offset() {
        return row_stride$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t row_stride
     * }
     */
    public static int row_stride(MemorySegment struct) {
        return struct.get(row_stride$LAYOUT, row_stride$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t row_stride
     * }
     */
    public static void row_stride(MemorySegment struct, int fieldValue) {
        struct.set(row_stride$LAYOUT, row_stride$OFFSET, fieldValue);
    }

    private static final AddressLayout ids$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("ids"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const int32_t *ids
     * }
     */
    public static final AddressLayout ids$layout() {
        return ids$LAYOUT;
    }

    private static final long ids$OFFSET = 16;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const int32_t *ids
     * }
     */
    public static final long ids$offset() {
        return ids$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const int32_t *ids
     * }
     */
    public static MemorySegment ids(MemorySegment struct) {
        return struct.get(ids$LAYOUT, ids$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const int32_t *ids
     * }
     */
    public static void ids(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(ids$LAYOUT, ids$OFFSET, fieldValue);
    }

    private static final AddressLayout mask$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("mask"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const int32_t *mask
     * }
     */
    public static final AddressLayout mask$layout() {
        return mask$LAYOUT;
    }

    private static final long mask$OFFSET = 24;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const int32_t *mask
     * }
     */
    public static final long mask$offset() {
        return mask$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const int32_t *mask
     * }
     */
    public static MemorySegment mask(MemorySegment struct) {
        return struct.get(mask$LAYOUT, mask$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const int32_t *mask
     * }
     */
    public static void mask(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(mask$LAYOUT, mask$OFFSET, fieldValue);
    }

    private static final AddressLayout types$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("types"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const int32_t *types
     * }
     */
    public static final AddressLayout types$layout() {
        return types$LAYOUT;
    }

    private static final long types$OFFSET = 32;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const int32_t *types
     * }
     */
    public static final long types$offset() {
        return types$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const int32_t *types
     * }
     */
    public static MemorySegment types(MemorySegment struct) {
        return struct.get(types$LAYOUT, types$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const int32_t *types
     * }
     */
    public static void types(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(types$LAYOUT, types$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

