// Generated by jextract

package ai.pipestream.turbo.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct turbo_generate_desc {
 *     uint32_t struct_size;
 *     uint32_t max_new_tokens;
 *     uint32_t min_new_tokens;
 *     uint32_t n_sequences;
 *     float temperature;
 *     uint32_t top_k;
 *     float top_p;
 *     float min_p;
 *     float repeat_penalty;
 *     float presence_penalty;
 *     float frequency_penalty;
 *     uint32_t has_seed;
 *     uint64_t seed;
 *     uint32_t n_stop;
 *     uint32_t n_stop_tokens;
 *     const struct turbo_text *stop;
 *     const int32_t *stop_tokens;
 *     uint32_t n_logit_bias;
 *     uint32_t logprobs;
 *     const struct turbo_logit_bias *logit_bias;
 *     uint32_t structured_kind;
 *     uint32_t echo;
 *     struct turbo_text structured;
 *     uint32_t n_tools;
 *     uint32_t n_options;
 *     const struct turbo_text *tools;
 *     const struct turbo_kv *options;
 * }
 * }
 */
public class turbo_generate_desc {

    turbo_generate_desc() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        TurboNative.C_INT.withName("struct_size"),
        TurboNative.C_INT.withName("max_new_tokens"),
        TurboNative.C_INT.withName("min_new_tokens"),
        TurboNative.C_INT.withName("n_sequences"),
        TurboNative.C_FLOAT.withName("temperature"),
        TurboNative.C_INT.withName("top_k"),
        TurboNative.C_FLOAT.withName("top_p"),
        TurboNative.C_FLOAT.withName("min_p"),
        TurboNative.C_FLOAT.withName("repeat_penalty"),
        TurboNative.C_FLOAT.withName("presence_penalty"),
        TurboNative.C_FLOAT.withName("frequency_penalty"),
        TurboNative.C_INT.withName("has_seed"),
        TurboNative.C_LONG.withName("seed"),
        TurboNative.C_INT.withName("n_stop"),
        TurboNative.C_INT.withName("n_stop_tokens"),
        TurboNative.C_POINTER.withName("stop"),
        TurboNative.C_POINTER.withName("stop_tokens"),
        TurboNative.C_INT.withName("n_logit_bias"),
        TurboNative.C_INT.withName("logprobs"),
        TurboNative.C_POINTER.withName("logit_bias"),
        TurboNative.C_INT.withName("structured_kind"),
        TurboNative.C_INT.withName("echo"),
        turbo_text.layout().withName("structured"),
        TurboNative.C_INT.withName("n_tools"),
        TurboNative.C_INT.withName("n_options"),
        TurboNative.C_POINTER.withName("tools"),
        TurboNative.C_POINTER.withName("options")
    ).withName("turbo_generate_desc");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt struct_size$LAYOUT = (OfInt)$LAYOUT.select(groupElement("struct_size"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t struct_size
     * }
     */
    public static final OfInt struct_size$layout() {
        return struct_size$LAYOUT;
    }

    private static final long struct_size$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t struct_size
     * }
     */
    public static final long struct_size$offset() {
        return struct_size$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t struct_size
     * }
     */
    public static int struct_size(MemorySegment struct) {
        return struct.get(struct_size$LAYOUT, struct_size$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t struct_size
     * }
     */
    public static void struct_size(MemorySegment struct, int fieldValue) {
        struct.set(struct_size$LAYOUT, struct_size$OFFSET, fieldValue);
    }

    private static final OfInt max_new_tokens$LAYOUT = (OfInt)$LAYOUT.select(groupElement("max_new_tokens"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t max_new_tokens
     * }
     */
    public static final OfInt max_new_tokens$layout() {
        return max_new_tokens$LAYOUT;
    }

    private static final long max_new_tokens$OFFSET = 4;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t max_new_tokens
     * }
     */
    public static final long max_new_tokens$offset() {
        return max_new_tokens$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t max_new_tokens
     * }
     */
    public static int max_new_tokens(MemorySegment struct) {
        return struct.get(max_new_tokens$LAYOUT, max_new_tokens$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t max_new_tokens
     * }
     */
    public static void max_new_tokens(MemorySegment struct, int fieldValue) {
        struct.set(max_new_tokens$LAYOUT, max_new_tokens$OFFSET, fieldValue);
    }

    private static final OfInt min_new_tokens$LAYOUT = (OfInt)$LAYOUT.select(groupElement("min_new_tokens"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t min_new_tokens
     * }
     */
    public static final OfInt min_new_tokens$layout() {
        return min_new_tokens$LAYOUT;
    }

    private static final long min_new_tokens$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t min_new_tokens
     * }
     */
    public static final long min_new_tokens$offset() {
        return min_new_tokens$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t min_new_tokens
     * }
     */
    public static int min_new_tokens(MemorySegment struct) {
        return struct.get(min_new_tokens$LAYOUT, min_new_tokens$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t min_new_tokens
     * }
     */
    public static void min_new_tokens(MemorySegment struct, int fieldValue) {
        struct.set(min_new_tokens$LAYOUT, min_new_tokens$OFFSET, fieldValue);
    }

    private static final OfInt n_sequences$LAYOUT = (OfInt)$LAYOUT.select(groupElement("n_sequences"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t n_sequences
     * }
     */
    public static final OfInt n_sequences$layout() {
        return n_sequences$LAYOUT;
    }

    private static final long n_sequences$OFFSET = 12;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t n_sequences
     * }
     */
    public static final long n_sequences$offset() {
        return n_sequences$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t n_sequences
     * }
     */
    public static int n_sequences(MemorySegment struct) {
        return struct.get(n_sequences$LAYOUT, n_sequences$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t n_sequences
     * }
     */
    public static void n_sequences(MemorySegment struct, int fieldValue) {
        struct.set(n_sequences$LAYOUT, n_sequences$OFFSET, fieldValue);
    }

    private static final OfFloat temperature$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("temperature"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float temperature
     * }
     */
    public static final OfFloat temperature$layout() {
        return temperature$LAYOUT;
    }

    private static final long temperature$OFFSET = 16;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float temperature
     * }
     */
    public static final long temperature$offset() {
        return temperature$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float temperature
     * }
     */
    public static float temperature(MemorySegment struct) {
        return struct.get(temperature$LAYOUT, temperature$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float temperature
     * }
     */
    public static void temperature(MemorySegment struct, float fieldValue) {
        struct.set(temperature$LAYOUT, temperature$OFFSET, fieldValue);
    }

    private static final OfInt top_k$LAYOUT = (OfInt)$LAYOUT.select(groupElement("top_k"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t top_k
     * }
     */
    public static final OfInt top_k$layout() {
        return top_k$LAYOUT;
    }

    private static final long top_k$OFFSET = 20;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t top_k
     * }
     */
    public static final long top_k$offset() {
        return top_k$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t top_k
     * }
     */
    public static int top_k(MemorySegment struct) {
        return struct.get(top_k$LAYOUT, top_k$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t top_k
     * }
     */
    public static void top_k(MemorySegment struct, int fieldValue) {
        struct.set(top_k$LAYOUT, top_k$OFFSET, fieldValue);
    }

    private static final OfFloat top_p$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("top_p"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float top_p
     * }
     */
    public static final OfFloat top_p$layout() {
        return top_p$LAYOUT;
    }

    private static final long top_p$OFFSET = 24;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float top_p
     * }
     */
    public static final long top_p$offset() {
        return top_p$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float top_p
     * }
     */
    public static float top_p(MemorySegment struct) {
        return struct.get(top_p$LAYOUT, top_p$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float top_p
     * }
     */
    public static void top_p(MemorySegment struct, float fieldValue) {
        struct.set(top_p$LAYOUT, top_p$OFFSET, fieldValue);
    }

    private static final OfFloat min_p$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("min_p"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float min_p
     * }
     */
    public static final OfFloat min_p$layout() {
        return min_p$LAYOUT;
    }

    private static final long min_p$OFFSET = 28;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float min_p
     * }
     */
    public static final long min_p$offset() {
        return min_p$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float min_p
     * }
     */
    public static float min_p(MemorySegment struct) {
        return struct.get(min_p$LAYOUT, min_p$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float min_p
     * }
     */
    public static void min_p(MemorySegment struct, float fieldValue) {
        struct.set(min_p$LAYOUT, min_p$OFFSET, fieldValue);
    }

    private static final OfFloat repeat_penalty$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("repeat_penalty"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float repeat_penalty
     * }
     */
    public static final OfFloat repeat_penalty$layout() {
        return repeat_penalty$LAYOUT;
    }

    private static final long repeat_penalty$OFFSET = 32;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float repeat_penalty
     * }
     */
    public static final long repeat_penalty$offset() {
        return repeat_penalty$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float repeat_penalty
     * }
     */
    public static float repeat_penalty(MemorySegment struct) {
        return struct.get(repeat_penalty$LAYOUT, repeat_penalty$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float repeat_penalty
     * }
     */
    public static void repeat_penalty(MemorySegment struct, float fieldValue) {
        struct.set(repeat_penalty$LAYOUT, repeat_penalty$OFFSET, fieldValue);
    }

    private static final OfFloat presence_penalty$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("presence_penalty"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float presence_penalty
     * }
     */
    public static final OfFloat presence_penalty$layout() {
        return presence_penalty$LAYOUT;
    }

    private static final long presence_penalty$OFFSET = 36;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float presence_penalty
     * }
     */
    public static final long presence_penalty$offset() {
        return presence_penalty$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float presence_penalty
     * }
     */
    public static float presence_penalty(MemorySegment struct) {
        return struct.get(presence_penalty$LAYOUT, presence_penalty$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float presence_penalty
     * }
     */
    public static void presence_penalty(MemorySegment struct, float fieldValue) {
        struct.set(presence_penalty$LAYOUT, presence_penalty$OFFSET, fieldValue);
    }

    private static final OfFloat frequency_penalty$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("frequency_penalty"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float frequency_penalty
     * }
     */
    public static final OfFloat frequency_penalty$layout() {
        return frequency_penalty$LAYOUT;
    }

    private static final long frequency_penalty$OFFSET = 40;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float frequency_penalty
     * }
     */
    public static final long frequency_penalty$offset() {
        return frequency_penalty$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float frequency_penalty
     * }
     */
    public static float frequency_penalty(MemorySegment struct) {
        return struct.get(frequency_penalty$LAYOUT, frequency_penalty$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float frequency_penalty
     * }
     */
    public static void frequency_penalty(MemorySegment struct, float fieldValue) {
        struct.set(frequency_penalty$LAYOUT, frequency_penalty$OFFSET, fieldValue);
    }

    private static final OfInt has_seed$LAYOUT = (OfInt)$LAYOUT.select(groupElement("has_seed"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t has_seed
     * }
     */
    public static final OfInt has_seed$layout() {
        return has_seed$LAYOUT;
    }

    private static final long has_seed$OFFSET = 44;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t has_seed
     * }
     */
    public static final long has_seed$offset() {
        return has_seed$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t has_seed
     * }
     */
    public static int has_seed(MemorySegment struct) {
        return struct.get(has_seed$LAYOUT, has_seed$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t has_seed
     * }
     */
    public static void has_seed(MemorySegment struct, int fieldValue) {
        struct.set(has_seed$LAYOUT, has_seed$OFFSET, fieldValue);
    }

    private static final OfLong seed$LAYOUT = (OfLong)$LAYOUT.select(groupElement("seed"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint64_t seed
     * }
     */
    public static final OfLong seed$layout() {
        return seed$LAYOUT;
    }

    private static final long seed$OFFSET = 48;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint64_t seed
     * }
     */
    public static final long seed$offset() {
        return seed$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint64_t seed
     * }
     */
    public static long seed(MemorySegment struct) {
        return struct.get(seed$LAYOUT, seed$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint64_t seed
     * }
     */
    public static void seed(MemorySegment struct, long fieldValue) {
        struct.set(seed$LAYOUT, seed$OFFSET, fieldValue);
    }

    private static final OfInt n_stop$LAYOUT = (OfInt)$LAYOUT.select(groupElement("n_stop"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t n_stop
     * }
     */
    public static final OfInt n_stop$layout() {
        return n_stop$LAYOUT;
    }

    private static final long n_stop$OFFSET = 56;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t n_stop
     * }
     */
    public static final long n_stop$offset() {
        return n_stop$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t n_stop
     * }
     */
    public static int n_stop(MemorySegment struct) {
        return struct.get(n_stop$LAYOUT, n_stop$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t n_stop
     * }
     */
    public static void n_stop(MemorySegment struct, int fieldValue) {
        struct.set(n_stop$LAYOUT, n_stop$OFFSET, fieldValue);
    }

    private static final OfInt n_stop_tokens$LAYOUT = (OfInt)$LAYOUT.select(groupElement("n_stop_tokens"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t n_stop_tokens
     * }
     */
    public static final OfInt n_stop_tokens$layout() {
        return n_stop_tokens$LAYOUT;
    }

    private static final long n_stop_tokens$OFFSET = 60;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t n_stop_tokens
     * }
     */
    public static final long n_stop_tokens$offset() {
        return n_stop_tokens$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t n_stop_tokens
     * }
     */
    public static int n_stop_tokens(MemorySegment struct) {
        return struct.get(n_stop_tokens$LAYOUT, n_stop_tokens$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t n_stop_tokens
     * }
     */
    public static void n_stop_tokens(MemorySegment struct, int fieldValue) {
        struct.set(n_stop_tokens$LAYOUT, n_stop_tokens$OFFSET, fieldValue);
    }

    private static final AddressLayout stop$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("stop"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const struct turbo_text *stop
     * }
     */
    public static final AddressLayout stop$layout() {
        return stop$LAYOUT;
    }

    private static final long stop$OFFSET = 64;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const struct turbo_text *stop
     * }
     */
    public static final long stop$offset() {
        return stop$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const struct turbo_text *stop
     * }
     */
    public static MemorySegment stop(MemorySegment struct) {
        return struct.get(stop$LAYOUT, stop$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const struct turbo_text *stop
     * }
     */
    public static void stop(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(stop$LAYOUT, stop$OFFSET, fieldValue);
    }

    private static final AddressLayout stop_tokens$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("stop_tokens"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const int32_t *stop_tokens
     * }
     */
    public static final AddressLayout stop_tokens$layout() {
        return stop_tokens$LAYOUT;
    }

    private static final long stop_tokens$OFFSET = 72;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const int32_t *stop_tokens
     * }
     */
    public static final long stop_tokens$offset() {
        return stop_tokens$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const int32_t *stop_tokens
     * }
     */
    public static MemorySegment stop_tokens(MemorySegment struct) {
        return struct.get(stop_tokens$LAYOUT, stop_tokens$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const int32_t *stop_tokens
     * }
     */
    public static void stop_tokens(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(stop_tokens$LAYOUT, stop_tokens$OFFSET, fieldValue);
    }

    private static final OfInt n_logit_bias$LAYOUT = (OfInt)$LAYOUT.select(groupElement("n_logit_bias"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t n_logit_bias
     * }
     */
    public static final OfInt n_logit_bias$layout() {
        return n_logit_bias$LAYOUT;
    }

    private static final long n_logit_bias$OFFSET = 80;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t n_logit_bias
     * }
     */
    public static final long n_logit_bias$offset() {
        return n_logit_bias$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t n_logit_bias
     * }
     */
    public static int n_logit_bias(MemorySegment struct) {
        return struct.get(n_logit_bias$LAYOUT, n_logit_bias$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t n_logit_bias
     * }
     */
    public static void n_logit_bias(MemorySegment struct, int fieldValue) {
        struct.set(n_logit_bias$LAYOUT, n_logit_bias$OFFSET, fieldValue);
    }

    private static final OfInt logprobs$LAYOUT = (OfInt)$LAYOUT.select(groupElement("logprobs"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t logprobs
     * }
     */
    public static final OfInt logprobs$layout() {
        return logprobs$LAYOUT;
    }

    private static final long logprobs$OFFSET = 84;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t logprobs
     * }
     */
    public static final long logprobs$offset() {
        return logprobs$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t logprobs
     * }
     */
    public static int logprobs(MemorySegment struct) {
        return struct.get(logprobs$LAYOUT, logprobs$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t logprobs
     * }
     */
    public static void logprobs(MemorySegment struct, int fieldValue) {
        struct.set(logprobs$LAYOUT, logprobs$OFFSET, fieldValue);
    }

    private static final AddressLayout logit_bias$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("logit_bias"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const struct turbo_logit_bias *logit_bias
     * }
     */
    public static final AddressLayout logit_bias$layout() {
        return logit_bias$LAYOUT;
    }

    private static final long logit_bias$OFFSET = 88;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const struct turbo_logit_bias *logit_bias
     * }
     */
    public static final long logit_bias$offset() {
        return logit_bias$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const struct turbo_logit_bias *logit_bias
     * }
     */
    public static MemorySegment logit_bias(MemorySegment struct) {
        return struct.get(logit_bias$LAYOUT, logit_bias$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const struct turbo_logit_bias *logit_bias
     * }
     */
    public static void logit_bias(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(logit_bias$LAYOUT, logit_bias$OFFSET, fieldValue);
    }

    private static final OfInt structured_kind$LAYOUT = (OfInt)$LAYOUT.select(groupElement("structured_kind"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t structured_kind
     * }
     */
    public static final OfInt structured_kind$layout() {
        return structured_kind$LAYOUT;
    }

    private static final long structured_kind$OFFSET = 96;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t structured_kind
     * }
     */
    public static final long structured_kind$offset() {
        return structured_kind$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t structured_kind
     * }
     */
    public static int structured_kind(MemorySegment struct) {
        return struct.get(structured_kind$LAYOUT, structured_kind$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t structured_kind
     * }
     */
    public static void structured_kind(MemorySegment struct, int fieldValue) {
        struct.set(structured_kind$LAYOUT, structured_kind$OFFSET, fieldValue);
    }

    private static final OfInt echo$LAYOUT = (OfInt)$LAYOUT.select(groupElement("echo"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t echo
     * }
     */
    public static final OfInt echo$layout() {
        return echo$LAYOUT;
    }

    private static final long echo$OFFSET = 100;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t echo
     * }
     */
    public static final long echo$offset() {
        return echo$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t echo
     * }
     */
    public static int echo(MemorySegment struct) {
        return struct.get(echo$LAYOUT, echo$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t echo
     * }
     */
    public static void echo(MemorySegment struct, int fieldValue) {
        struct.set(echo$LAYOUT, echo$OFFSET, fieldValue);
    }

    private static final GroupLayout structured$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("structured"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct turbo_text structured
     * }
     */
    public static final GroupLayout structured$layout() {
        return structured$LAYOUT;
    }

    private static final long structured$OFFSET = 104;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct turbo_text structured
     * }
     */
    public static final long structured$offset() {
        return structured$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct turbo_text structured
     * }
     */
    public static MemorySegment structured(MemorySegment struct) {
        return struct.asSlice(structured$OFFSET, structured$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct turbo_text structured
     * }
     */
    public static void structured(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, structured$OFFSET, structured$LAYOUT.byteSize());
    }

    private static final OfInt n_tools$LAYOUT = (OfInt)$LAYOUT.select(groupElement("n_tools"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t n_tools
     * }
     */
    public static final OfInt n_tools$layout() {
        return n_tools$LAYOUT;
    }

    private static final long n_tools$OFFSET = 120;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t n_tools
     * }
     */
    public static final long n_tools$offset() {
        return n_tools$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t n_tools
     * }
     */
    public static int n_tools(MemorySegment struct) {
        return struct.get(n_tools$LAYOUT, n_tools$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t n_tools
     * }
     */
    public static void n_tools(MemorySegment struct, int fieldValue) {
        struct.set(n_tools$LAYOUT, n_tools$OFFSET, fieldValue);
    }

    private static final OfInt n_options$LAYOUT = (OfInt)$LAYOUT.select(groupElement("n_options"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t n_options
     * }
     */
    public static final OfInt n_options$layout() {
        return n_options$LAYOUT;
    }

    private static final long n_options$OFFSET = 124;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t n_options
     * }
     */
    public static final long n_options$offset() {
        return n_options$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t n_options
     * }
     */
    public static int n_options(MemorySegment struct) {
        return struct.get(n_options$LAYOUT, n_options$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t n_options
     * }
     */
    public static void n_options(MemorySegment struct, int fieldValue) {
        struct.set(n_options$LAYOUT, n_options$OFFSET, fieldValue);
    }

    private static final AddressLayout tools$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("tools"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const struct turbo_text *tools
     * }
     */
    public static final AddressLayout tools$layout() {
        return tools$LAYOUT;
    }

    private static final long tools$OFFSET = 128;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const struct turbo_text *tools
     * }
     */
    public static final long tools$offset() {
        return tools$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const struct turbo_text *tools
     * }
     */
    public static MemorySegment tools(MemorySegment struct) {
        return struct.get(tools$LAYOUT, tools$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const struct turbo_text *tools
     * }
     */
    public static void tools(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(tools$LAYOUT, tools$OFFSET, fieldValue);
    }

    private static final AddressLayout options$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("options"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const struct turbo_kv *options
     * }
     */
    public static final AddressLayout options$layout() {
        return options$LAYOUT;
    }

    private static final long options$OFFSET = 136;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const struct turbo_kv *options
     * }
     */
    public static final long options$offset() {
        return options$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const struct turbo_kv *options
     * }
     */
    public static MemorySegment options(MemorySegment struct) {
        return struct.get(options$LAYOUT, options$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const struct turbo_kv *options
     * }
     */
    public static void options(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(options$LAYOUT, options$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

