// Generated by jextract

package ai.pipestream.turbo.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct turbo_classify_options {
 *     uint32_t struct_size;
 *     uint32_t truncate;
 *     uint32_t max_tokens;
 *     uint32_t aggregation;
 *     uint32_t raw_scores;
 *     uint32_t reserved;
 * }
 * }
 */
public class turbo_classify_options {

    turbo_classify_options() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        TurboNative.C_INT.withName("struct_size"),
        TurboNative.C_INT.withName("truncate"),
        TurboNative.C_INT.withName("max_tokens"),
        TurboNative.C_INT.withName("aggregation"),
        TurboNative.C_INT.withName("raw_scores"),
        TurboNative.C_INT.withName("reserved")
    ).withName("turbo_classify_options");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt struct_size$LAYOUT = (OfInt)$LAYOUT.select(groupElement("struct_size"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t struct_size
     * }
     */
    public static final OfInt struct_size$layout() {
        return struct_size$LAYOUT;
    }

    private static final long struct_size$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t struct_size
     * }
     */
    public static final long struct_size$offset() {
        return struct_size$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t struct_size
     * }
     */
    public static int struct_size(MemorySegment struct) {
        return struct.get(struct_size$LAYOUT, struct_size$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t struct_size
     * }
     */
    public static void struct_size(MemorySegment struct, int fieldValue) {
        struct.set(struct_size$LAYOUT, struct_size$OFFSET, fieldValue);
    }

    private static final OfInt truncate$LAYOUT = (OfInt)$LAYOUT.select(groupElement("truncate"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t truncate
     * }
     */
    public static final OfInt truncate$layout() {
        return truncate$LAYOUT;
    }

    private static final long truncate$OFFSET = 4;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t truncate
     * }
     */
    public static final long truncate$offset() {
        return truncate$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t truncate
     * }
     */
    public static int truncate(MemorySegment struct) {
        return struct.get(truncate$LAYOUT, truncate$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t truncate
     * }
     */
    public static void truncate(MemorySegment struct, int fieldValue) {
        struct.set(truncate$LAYOUT, truncate$OFFSET, fieldValue);
    }

    private static final OfInt max_tokens$LAYOUT = (OfInt)$LAYOUT.select(groupElement("max_tokens"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t max_tokens
     * }
     */
    public static final OfInt max_tokens$layout() {
        return max_tokens$LAYOUT;
    }

    private static final long max_tokens$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t max_tokens
     * }
     */
    public static final long max_tokens$offset() {
        return max_tokens$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t max_tokens
     * }
     */
    public static int max_tokens(MemorySegment struct) {
        return struct.get(max_tokens$LAYOUT, max_tokens$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t max_tokens
     * }
     */
    public static void max_tokens(MemorySegment struct, int fieldValue) {
        struct.set(max_tokens$LAYOUT, max_tokens$OFFSET, fieldValue);
    }

    private static final OfInt aggregation$LAYOUT = (OfInt)$LAYOUT.select(groupElement("aggregation"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t aggregation
     * }
     */
    public static final OfInt aggregation$layout() {
        return aggregation$LAYOUT;
    }

    private static final long aggregation$OFFSET = 12;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t aggregation
     * }
     */
    public static final long aggregation$offset() {
        return aggregation$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t aggregation
     * }
     */
    public static int aggregation(MemorySegment struct) {
        return struct.get(aggregation$LAYOUT, aggregation$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t aggregation
     * }
     */
    public static void aggregation(MemorySegment struct, int fieldValue) {
        struct.set(aggregation$LAYOUT, aggregation$OFFSET, fieldValue);
    }

    private static final OfInt raw_scores$LAYOUT = (OfInt)$LAYOUT.select(groupElement("raw_scores"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t raw_scores
     * }
     */
    public static final OfInt raw_scores$layout() {
        return raw_scores$LAYOUT;
    }

    private static final long raw_scores$OFFSET = 16;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t raw_scores
     * }
     */
    public static final long raw_scores$offset() {
        return raw_scores$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t raw_scores
     * }
     */
    public static int raw_scores(MemorySegment struct) {
        return struct.get(raw_scores$LAYOUT, raw_scores$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t raw_scores
     * }
     */
    public static void raw_scores(MemorySegment struct, int fieldValue) {
        struct.set(raw_scores$LAYOUT, raw_scores$OFFSET, fieldValue);
    }

    private static final OfInt reserved$LAYOUT = (OfInt)$LAYOUT.select(groupElement("reserved"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t reserved
     * }
     */
    public static final OfInt reserved$layout() {
        return reserved$LAYOUT;
    }

    private static final long reserved$OFFSET = 20;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t reserved
     * }
     */
    public static final long reserved$offset() {
        return reserved$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t reserved
     * }
     */
    public static int reserved(MemorySegment struct) {
        return struct.get(reserved$LAYOUT, reserved$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t reserved
     * }
     */
    public static void reserved(MemorySegment struct, int fieldValue) {
        struct.set(reserved$LAYOUT, reserved$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

