// Generated by jextract

package ai.pipestream.turbo.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct turbo_capability {
 *     uint32_t struct_size;
 *     uint32_t status;
 *     uint32_t dtype;
 *     uint32_t reference_dtype;
 *     float cosine_floor;
 *     float max_abs_error;
 *     uint32_t deterministic;
 *     uint32_t reserved;
 *     char notes[128];
 * }
 * }
 */
public class turbo_capability {

    turbo_capability() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        TurboNative.C_INT.withName("struct_size"),
        TurboNative.C_INT.withName("status"),
        TurboNative.C_INT.withName("dtype"),
        TurboNative.C_INT.withName("reference_dtype"),
        TurboNative.C_FLOAT.withName("cosine_floor"),
        TurboNative.C_FLOAT.withName("max_abs_error"),
        TurboNative.C_INT.withName("deterministic"),
        TurboNative.C_INT.withName("reserved"),
        MemoryLayout.sequenceLayout(128, TurboNative.C_CHAR).withName("notes")
    ).withName("turbo_capability");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt struct_size$LAYOUT = (OfInt)$LAYOUT.select(groupElement("struct_size"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t struct_size
     * }
     */
    public static final OfInt struct_size$layout() {
        return struct_size$LAYOUT;
    }

    private static final long struct_size$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t struct_size
     * }
     */
    public static final long struct_size$offset() {
        return struct_size$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t struct_size
     * }
     */
    public static int struct_size(MemorySegment struct) {
        return struct.get(struct_size$LAYOUT, struct_size$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t struct_size
     * }
     */
    public static void struct_size(MemorySegment struct, int fieldValue) {
        struct.set(struct_size$LAYOUT, struct_size$OFFSET, fieldValue);
    }

    private static final OfInt status$LAYOUT = (OfInt)$LAYOUT.select(groupElement("status"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t status
     * }
     */
    public static final OfInt status$layout() {
        return status$LAYOUT;
    }

    private static final long status$OFFSET = 4;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t status
     * }
     */
    public static final long status$offset() {
        return status$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t status
     * }
     */
    public static int status(MemorySegment struct) {
        return struct.get(status$LAYOUT, status$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t status
     * }
     */
    public static void status(MemorySegment struct, int fieldValue) {
        struct.set(status$LAYOUT, status$OFFSET, fieldValue);
    }

    private static final OfInt dtype$LAYOUT = (OfInt)$LAYOUT.select(groupElement("dtype"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t dtype
     * }
     */
    public static final OfInt dtype$layout() {
        return dtype$LAYOUT;
    }

    private static final long dtype$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t dtype
     * }
     */
    public static final long dtype$offset() {
        return dtype$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t dtype
     * }
     */
    public static int dtype(MemorySegment struct) {
        return struct.get(dtype$LAYOUT, dtype$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t dtype
     * }
     */
    public static void dtype(MemorySegment struct, int fieldValue) {
        struct.set(dtype$LAYOUT, dtype$OFFSET, fieldValue);
    }

    private static final OfInt reference_dtype$LAYOUT = (OfInt)$LAYOUT.select(groupElement("reference_dtype"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t reference_dtype
     * }
     */
    public static final OfInt reference_dtype$layout() {
        return reference_dtype$LAYOUT;
    }

    private static final long reference_dtype$OFFSET = 12;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t reference_dtype
     * }
     */
    public static final long reference_dtype$offset() {
        return reference_dtype$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t reference_dtype
     * }
     */
    public static int reference_dtype(MemorySegment struct) {
        return struct.get(reference_dtype$LAYOUT, reference_dtype$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t reference_dtype
     * }
     */
    public static void reference_dtype(MemorySegment struct, int fieldValue) {
        struct.set(reference_dtype$LAYOUT, reference_dtype$OFFSET, fieldValue);
    }

    private static final OfFloat cosine_floor$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("cosine_floor"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float cosine_floor
     * }
     */
    public static final OfFloat cosine_floor$layout() {
        return cosine_floor$LAYOUT;
    }

    private static final long cosine_floor$OFFSET = 16;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float cosine_floor
     * }
     */
    public static final long cosine_floor$offset() {
        return cosine_floor$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float cosine_floor
     * }
     */
    public static float cosine_floor(MemorySegment struct) {
        return struct.get(cosine_floor$LAYOUT, cosine_floor$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float cosine_floor
     * }
     */
    public static void cosine_floor(MemorySegment struct, float fieldValue) {
        struct.set(cosine_floor$LAYOUT, cosine_floor$OFFSET, fieldValue);
    }

    private static final OfFloat max_abs_error$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("max_abs_error"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float max_abs_error
     * }
     */
    public static final OfFloat max_abs_error$layout() {
        return max_abs_error$LAYOUT;
    }

    private static final long max_abs_error$OFFSET = 20;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float max_abs_error
     * }
     */
    public static final long max_abs_error$offset() {
        return max_abs_error$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float max_abs_error
     * }
     */
    public static float max_abs_error(MemorySegment struct) {
        return struct.get(max_abs_error$LAYOUT, max_abs_error$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float max_abs_error
     * }
     */
    public static void max_abs_error(MemorySegment struct, float fieldValue) {
        struct.set(max_abs_error$LAYOUT, max_abs_error$OFFSET, fieldValue);
    }

    private static final OfInt deterministic$LAYOUT = (OfInt)$LAYOUT.select(groupElement("deterministic"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t deterministic
     * }
     */
    public static final OfInt deterministic$layout() {
        return deterministic$LAYOUT;
    }

    private static final long deterministic$OFFSET = 24;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t deterministic
     * }
     */
    public static final long deterministic$offset() {
        return deterministic$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t deterministic
     * }
     */
    public static int deterministic(MemorySegment struct) {
        return struct.get(deterministic$LAYOUT, deterministic$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t deterministic
     * }
     */
    public static void deterministic(MemorySegment struct, int fieldValue) {
        struct.set(deterministic$LAYOUT, deterministic$OFFSET, fieldValue);
    }

    private static final OfInt reserved$LAYOUT = (OfInt)$LAYOUT.select(groupElement("reserved"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t reserved
     * }
     */
    public static final OfInt reserved$layout() {
        return reserved$LAYOUT;
    }

    private static final long reserved$OFFSET = 28;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t reserved
     * }
     */
    public static final long reserved$offset() {
        return reserved$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t reserved
     * }
     */
    public static int reserved(MemorySegment struct) {
        return struct.get(reserved$LAYOUT, reserved$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t reserved
     * }
     */
    public static void reserved(MemorySegment struct, int fieldValue) {
        struct.set(reserved$LAYOUT, reserved$OFFSET, fieldValue);
    }

    private static final SequenceLayout notes$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("notes"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * char notes[128]
     * }
     */
    public static final SequenceLayout notes$layout() {
        return notes$LAYOUT;
    }

    private static final long notes$OFFSET = 32;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * char notes[128]
     * }
     */
    public static final long notes$offset() {
        return notes$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * char notes[128]
     * }
     */
    public static MemorySegment notes(MemorySegment struct) {
        return struct.asSlice(notes$OFFSET, notes$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * char notes[128]
     * }
     */
    public static void notes(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, notes$OFFSET, notes$LAYOUT.byteSize());
    }

    private static long[] notes$DIMS = { 128 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * char notes[128]
     * }
     */
    public static long[] notes$dimensions() {
        return notes$DIMS;
    }
    private static final VarHandle notes$ELEM_HANDLE = notes$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * char notes[128]
     * }
     */
    public static byte notes(MemorySegment struct, long index0) {
        return notes(struct).getAtIndex(JAVA_BYTE, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * char notes[128]
     * }
     */
    public static void notes(MemorySegment struct, long index0, byte fieldValue) {
        notes(struct).setAtIndex(JAVA_BYTE, index0, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

