// Generated by jextract

package ai.pipestream.turbo.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct turbo_generation_chunk {
 *     uint32_t struct_size;
 *     uint32_t sequence;
 *     uint32_t n_tokens;
 *     uint32_t n_logprobs;
 *     const int32_t *tokens;
 *     struct turbo_text text;
 *     const float *logprobs;
 *     uint32_t done;
 *     uint32_t finish_reason;
 *     uint32_t prompt_tokens;
 *     uint32_t generated_tokens;
 * }
 * }
 */
public class turbo_generation_chunk {

    turbo_generation_chunk() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        TurboNative.C_INT.withName("struct_size"),
        TurboNative.C_INT.withName("sequence"),
        TurboNative.C_INT.withName("n_tokens"),
        TurboNative.C_INT.withName("n_logprobs"),
        TurboNative.C_POINTER.withName("tokens"),
        turbo_text.layout().withName("text"),
        TurboNative.C_POINTER.withName("logprobs"),
        TurboNative.C_INT.withName("done"),
        TurboNative.C_INT.withName("finish_reason"),
        TurboNative.C_INT.withName("prompt_tokens"),
        TurboNative.C_INT.withName("generated_tokens")
    ).withName("turbo_generation_chunk");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt struct_size$LAYOUT = (OfInt)$LAYOUT.select(groupElement("struct_size"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t struct_size
     * }
     */
    public static final OfInt struct_size$layout() {
        return struct_size$LAYOUT;
    }

    private static final long struct_size$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t struct_size
     * }
     */
    public static final long struct_size$offset() {
        return struct_size$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t struct_size
     * }
     */
    public static int struct_size(MemorySegment struct) {
        return struct.get(struct_size$LAYOUT, struct_size$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t struct_size
     * }
     */
    public static void struct_size(MemorySegment struct, int fieldValue) {
        struct.set(struct_size$LAYOUT, struct_size$OFFSET, fieldValue);
    }

    private static final OfInt sequence$LAYOUT = (OfInt)$LAYOUT.select(groupElement("sequence"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t sequence
     * }
     */
    public static final OfInt sequence$layout() {
        return sequence$LAYOUT;
    }

    private static final long sequence$OFFSET = 4;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t sequence
     * }
     */
    public static final long sequence$offset() {
        return sequence$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t sequence
     * }
     */
    public static int sequence(MemorySegment struct) {
        return struct.get(sequence$LAYOUT, sequence$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t sequence
     * }
     */
    public static void sequence(MemorySegment struct, int fieldValue) {
        struct.set(sequence$LAYOUT, sequence$OFFSET, fieldValue);
    }

    private static final OfInt n_tokens$LAYOUT = (OfInt)$LAYOUT.select(groupElement("n_tokens"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t n_tokens
     * }
     */
    public static final OfInt n_tokens$layout() {
        return n_tokens$LAYOUT;
    }

    private static final long n_tokens$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t n_tokens
     * }
     */
    public static final long n_tokens$offset() {
        return n_tokens$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t n_tokens
     * }
     */
    public static int n_tokens(MemorySegment struct) {
        return struct.get(n_tokens$LAYOUT, n_tokens$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t n_tokens
     * }
     */
    public static void n_tokens(MemorySegment struct, int fieldValue) {
        struct.set(n_tokens$LAYOUT, n_tokens$OFFSET, fieldValue);
    }

    private static final OfInt n_logprobs$LAYOUT = (OfInt)$LAYOUT.select(groupElement("n_logprobs"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t n_logprobs
     * }
     */
    public static final OfInt n_logprobs$layout() {
        return n_logprobs$LAYOUT;
    }

    private static final long n_logprobs$OFFSET = 12;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t n_logprobs
     * }
     */
    public static final long n_logprobs$offset() {
        return n_logprobs$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t n_logprobs
     * }
     */
    public static int n_logprobs(MemorySegment struct) {
        return struct.get(n_logprobs$LAYOUT, n_logprobs$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t n_logprobs
     * }
     */
    public static void n_logprobs(MemorySegment struct, int fieldValue) {
        struct.set(n_logprobs$LAYOUT, n_logprobs$OFFSET, fieldValue);
    }

    private static final AddressLayout tokens$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("tokens"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const int32_t *tokens
     * }
     */
    public static final AddressLayout tokens$layout() {
        return tokens$LAYOUT;
    }

    private static final long tokens$OFFSET = 16;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const int32_t *tokens
     * }
     */
    public static final long tokens$offset() {
        return tokens$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const int32_t *tokens
     * }
     */
    public static MemorySegment tokens(MemorySegment struct) {
        return struct.get(tokens$LAYOUT, tokens$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const int32_t *tokens
     * }
     */
    public static void tokens(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(tokens$LAYOUT, tokens$OFFSET, fieldValue);
    }

    private static final GroupLayout text$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("text"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct turbo_text text
     * }
     */
    public static final GroupLayout text$layout() {
        return text$LAYOUT;
    }

    private static final long text$OFFSET = 24;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct turbo_text text
     * }
     */
    public static final long text$offset() {
        return text$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct turbo_text text
     * }
     */
    public static MemorySegment text(MemorySegment struct) {
        return struct.asSlice(text$OFFSET, text$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct turbo_text text
     * }
     */
    public static void text(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, text$OFFSET, text$LAYOUT.byteSize());
    }

    private static final AddressLayout logprobs$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("logprobs"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const float *logprobs
     * }
     */
    public static final AddressLayout logprobs$layout() {
        return logprobs$LAYOUT;
    }

    private static final long logprobs$OFFSET = 40;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const float *logprobs
     * }
     */
    public static final long logprobs$offset() {
        return logprobs$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const float *logprobs
     * }
     */
    public static MemorySegment logprobs(MemorySegment struct) {
        return struct.get(logprobs$LAYOUT, logprobs$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const float *logprobs
     * }
     */
    public static void logprobs(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(logprobs$LAYOUT, logprobs$OFFSET, fieldValue);
    }

    private static final OfInt done$LAYOUT = (OfInt)$LAYOUT.select(groupElement("done"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t done
     * }
     */
    public static final OfInt done$layout() {
        return done$LAYOUT;
    }

    private static final long done$OFFSET = 48;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t done
     * }
     */
    public static final long done$offset() {
        return done$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t done
     * }
     */
    public static int done(MemorySegment struct) {
        return struct.get(done$LAYOUT, done$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t done
     * }
     */
    public static void done(MemorySegment struct, int fieldValue) {
        struct.set(done$LAYOUT, done$OFFSET, fieldValue);
    }

    private static final OfInt finish_reason$LAYOUT = (OfInt)$LAYOUT.select(groupElement("finish_reason"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t finish_reason
     * }
     */
    public static final OfInt finish_reason$layout() {
        return finish_reason$LAYOUT;
    }

    private static final long finish_reason$OFFSET = 52;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t finish_reason
     * }
     */
    public static final long finish_reason$offset() {
        return finish_reason$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t finish_reason
     * }
     */
    public static int finish_reason(MemorySegment struct) {
        return struct.get(finish_reason$LAYOUT, finish_reason$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t finish_reason
     * }
     */
    public static void finish_reason(MemorySegment struct, int fieldValue) {
        struct.set(finish_reason$LAYOUT, finish_reason$OFFSET, fieldValue);
    }

    private static final OfInt prompt_tokens$LAYOUT = (OfInt)$LAYOUT.select(groupElement("prompt_tokens"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t prompt_tokens
     * }
     */
    public static final OfInt prompt_tokens$layout() {
        return prompt_tokens$LAYOUT;
    }

    private static final long prompt_tokens$OFFSET = 56;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t prompt_tokens
     * }
     */
    public static final long prompt_tokens$offset() {
        return prompt_tokens$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t prompt_tokens
     * }
     */
    public static int prompt_tokens(MemorySegment struct) {
        return struct.get(prompt_tokens$LAYOUT, prompt_tokens$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t prompt_tokens
     * }
     */
    public static void prompt_tokens(MemorySegment struct, int fieldValue) {
        struct.set(prompt_tokens$LAYOUT, prompt_tokens$OFFSET, fieldValue);
    }

    private static final OfInt generated_tokens$LAYOUT = (OfInt)$LAYOUT.select(groupElement("generated_tokens"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t generated_tokens
     * }
     */
    public static final OfInt generated_tokens$layout() {
        return generated_tokens$LAYOUT;
    }

    private static final long generated_tokens$OFFSET = 60;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t generated_tokens
     * }
     */
    public static final long generated_tokens$offset() {
        return generated_tokens$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t generated_tokens
     * }
     */
    public static int generated_tokens(MemorySegment struct) {
        return struct.get(generated_tokens$LAYOUT, generated_tokens$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t generated_tokens
     * }
     */
    public static void generated_tokens(MemorySegment struct, int fieldValue) {
        struct.set(generated_tokens$LAYOUT, generated_tokens$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

