// Generated by jextract

package ai.pipestream.turbo.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct turbo_span {
 *     uint64_t byte_start;
 *     uint64_t byte_end;
 *     uint32_t row;
 *     uint32_t label;
 *     float score;
 *     uint32_t reserved;
 * }
 * }
 */
public class turbo_span {

    turbo_span() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        TurboNative.C_LONG.withName("byte_start"),
        TurboNative.C_LONG.withName("byte_end"),
        TurboNative.C_INT.withName("row"),
        TurboNative.C_INT.withName("label"),
        TurboNative.C_FLOAT.withName("score"),
        TurboNative.C_INT.withName("reserved")
    ).withName("turbo_span");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfLong byte_start$LAYOUT = (OfLong)$LAYOUT.select(groupElement("byte_start"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint64_t byte_start
     * }
     */
    public static final OfLong byte_start$layout() {
        return byte_start$LAYOUT;
    }

    private static final long byte_start$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint64_t byte_start
     * }
     */
    public static final long byte_start$offset() {
        return byte_start$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint64_t byte_start
     * }
     */
    public static long byte_start(MemorySegment struct) {
        return struct.get(byte_start$LAYOUT, byte_start$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint64_t byte_start
     * }
     */
    public static void byte_start(MemorySegment struct, long fieldValue) {
        struct.set(byte_start$LAYOUT, byte_start$OFFSET, fieldValue);
    }

    private static final OfLong byte_end$LAYOUT = (OfLong)$LAYOUT.select(groupElement("byte_end"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint64_t byte_end
     * }
     */
    public static final OfLong byte_end$layout() {
        return byte_end$LAYOUT;
    }

    private static final long byte_end$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint64_t byte_end
     * }
     */
    public static final long byte_end$offset() {
        return byte_end$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint64_t byte_end
     * }
     */
    public static long byte_end(MemorySegment struct) {
        return struct.get(byte_end$LAYOUT, byte_end$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint64_t byte_end
     * }
     */
    public static void byte_end(MemorySegment struct, long fieldValue) {
        struct.set(byte_end$LAYOUT, byte_end$OFFSET, fieldValue);
    }

    private static final OfInt row$LAYOUT = (OfInt)$LAYOUT.select(groupElement("row"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t row
     * }
     */
    public static final OfInt row$layout() {
        return row$LAYOUT;
    }

    private static final long row$OFFSET = 16;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t row
     * }
     */
    public static final long row$offset() {
        return row$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t row
     * }
     */
    public static int row(MemorySegment struct) {
        return struct.get(row$LAYOUT, row$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t row
     * }
     */
    public static void row(MemorySegment struct, int fieldValue) {
        struct.set(row$LAYOUT, row$OFFSET, fieldValue);
    }

    private static final OfInt label$LAYOUT = (OfInt)$LAYOUT.select(groupElement("label"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t label
     * }
     */
    public static final OfInt label$layout() {
        return label$LAYOUT;
    }

    private static final long label$OFFSET = 20;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t label
     * }
     */
    public static final long label$offset() {
        return label$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t label
     * }
     */
    public static int label(MemorySegment struct) {
        return struct.get(label$LAYOUT, label$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t label
     * }
     */
    public static void label(MemorySegment struct, int fieldValue) {
        struct.set(label$LAYOUT, label$OFFSET, fieldValue);
    }

    private static final OfFloat score$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("score"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float score
     * }
     */
    public static final OfFloat score$layout() {
        return score$LAYOUT;
    }

    private static final long score$OFFSET = 24;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float score
     * }
     */
    public static final long score$offset() {
        return score$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float score
     * }
     */
    public static float score(MemorySegment struct) {
        return struct.get(score$LAYOUT, score$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float score
     * }
     */
    public static void score(MemorySegment struct, float fieldValue) {
        struct.set(score$LAYOUT, score$OFFSET, fieldValue);
    }

    private static final OfInt reserved$LAYOUT = (OfInt)$LAYOUT.select(groupElement("reserved"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t reserved
     * }
     */
    public static final OfInt reserved$layout() {
        return reserved$LAYOUT;
    }

    private static final long reserved$OFFSET = 28;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t reserved
     * }
     */
    public static final long reserved$offset() {
        return reserved$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t reserved
     * }
     */
    public static int reserved(MemorySegment struct) {
        return struct.get(reserved$LAYOUT, reserved$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t reserved
     * }
     */
    public static void reserved(MemorySegment struct, int fieldValue) {
        struct.set(reserved$LAYOUT, reserved$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

