// Generated by jextract

package ai.pipestream.turbo.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct turbo_encode_options {
 *     uint32_t struct_size;
 *     uint32_t add_special_tokens;
 *     uint32_t truncate;
 *     uint32_t max_tokens;
 *     uint32_t pad_to;
 *     uint32_t prompt_role;
 * }
 * }
 */
public class turbo_encode_options {

    turbo_encode_options() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        TurboNative.C_INT.withName("struct_size"),
        TurboNative.C_INT.withName("add_special_tokens"),
        TurboNative.C_INT.withName("truncate"),
        TurboNative.C_INT.withName("max_tokens"),
        TurboNative.C_INT.withName("pad_to"),
        TurboNative.C_INT.withName("prompt_role")
    ).withName("turbo_encode_options");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt struct_size$LAYOUT = (OfInt)$LAYOUT.select(groupElement("struct_size"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t struct_size
     * }
     */
    public static final OfInt struct_size$layout() {
        return struct_size$LAYOUT;
    }

    private static final long struct_size$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t struct_size
     * }
     */
    public static final long struct_size$offset() {
        return struct_size$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t struct_size
     * }
     */
    public static int struct_size(MemorySegment struct) {
        return struct.get(struct_size$LAYOUT, struct_size$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t struct_size
     * }
     */
    public static void struct_size(MemorySegment struct, int fieldValue) {
        struct.set(struct_size$LAYOUT, struct_size$OFFSET, fieldValue);
    }

    private static final OfInt add_special_tokens$LAYOUT = (OfInt)$LAYOUT.select(groupElement("add_special_tokens"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t add_special_tokens
     * }
     */
    public static final OfInt add_special_tokens$layout() {
        return add_special_tokens$LAYOUT;
    }

    private static final long add_special_tokens$OFFSET = 4;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t add_special_tokens
     * }
     */
    public static final long add_special_tokens$offset() {
        return add_special_tokens$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t add_special_tokens
     * }
     */
    public static int add_special_tokens(MemorySegment struct) {
        return struct.get(add_special_tokens$LAYOUT, add_special_tokens$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t add_special_tokens
     * }
     */
    public static void add_special_tokens(MemorySegment struct, int fieldValue) {
        struct.set(add_special_tokens$LAYOUT, add_special_tokens$OFFSET, fieldValue);
    }

    private static final OfInt truncate$LAYOUT = (OfInt)$LAYOUT.select(groupElement("truncate"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t truncate
     * }
     */
    public static final OfInt truncate$layout() {
        return truncate$LAYOUT;
    }

    private static final long truncate$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t truncate
     * }
     */
    public static final long truncate$offset() {
        return truncate$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t truncate
     * }
     */
    public static int truncate(MemorySegment struct) {
        return struct.get(truncate$LAYOUT, truncate$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t truncate
     * }
     */
    public static void truncate(MemorySegment struct, int fieldValue) {
        struct.set(truncate$LAYOUT, truncate$OFFSET, fieldValue);
    }

    private static final OfInt max_tokens$LAYOUT = (OfInt)$LAYOUT.select(groupElement("max_tokens"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t max_tokens
     * }
     */
    public static final OfInt max_tokens$layout() {
        return max_tokens$LAYOUT;
    }

    private static final long max_tokens$OFFSET = 12;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t max_tokens
     * }
     */
    public static final long max_tokens$offset() {
        return max_tokens$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t max_tokens
     * }
     */
    public static int max_tokens(MemorySegment struct) {
        return struct.get(max_tokens$LAYOUT, max_tokens$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t max_tokens
     * }
     */
    public static void max_tokens(MemorySegment struct, int fieldValue) {
        struct.set(max_tokens$LAYOUT, max_tokens$OFFSET, fieldValue);
    }

    private static final OfInt pad_to$LAYOUT = (OfInt)$LAYOUT.select(groupElement("pad_to"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t pad_to
     * }
     */
    public static final OfInt pad_to$layout() {
        return pad_to$LAYOUT;
    }

    private static final long pad_to$OFFSET = 16;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t pad_to
     * }
     */
    public static final long pad_to$offset() {
        return pad_to$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t pad_to
     * }
     */
    public static int pad_to(MemorySegment struct) {
        return struct.get(pad_to$LAYOUT, pad_to$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t pad_to
     * }
     */
    public static void pad_to(MemorySegment struct, int fieldValue) {
        struct.set(pad_to$LAYOUT, pad_to$OFFSET, fieldValue);
    }

    private static final OfInt prompt_role$LAYOUT = (OfInt)$LAYOUT.select(groupElement("prompt_role"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t prompt_role
     * }
     */
    public static final OfInt prompt_role$layout() {
        return prompt_role$LAYOUT;
    }

    private static final long prompt_role$OFFSET = 20;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t prompt_role
     * }
     */
    public static final long prompt_role$offset() {
        return prompt_role$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t prompt_role
     * }
     */
    public static int prompt_role(MemorySegment struct) {
        return struct.get(prompt_role$LAYOUT, prompt_role$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t prompt_role
     * }
     */
    public static void prompt_role(MemorySegment struct, int fieldValue) {
        struct.set(prompt_role$LAYOUT, prompt_role$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

