// Generated by jextract

package ai.pipestream.turbo.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct turbo_device_selector {
 *     uint32_t struct_size;
 *     uint32_t policy;
 *     uint32_t kind_mask;
 *     uint32_t ordinal;
 *     struct turbo_text provider_id;
 *     struct turbo_text vendor;
 * }
 * }
 */
public class turbo_device_selector {

    turbo_device_selector() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        TurboNative.C_INT.withName("struct_size"),
        TurboNative.C_INT.withName("policy"),
        TurboNative.C_INT.withName("kind_mask"),
        TurboNative.C_INT.withName("ordinal"),
        turbo_text.layout().withName("provider_id"),
        turbo_text.layout().withName("vendor")
    ).withName("turbo_device_selector");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt struct_size$LAYOUT = (OfInt)$LAYOUT.select(groupElement("struct_size"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t struct_size
     * }
     */
    public static final OfInt struct_size$layout() {
        return struct_size$LAYOUT;
    }

    private static final long struct_size$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t struct_size
     * }
     */
    public static final long struct_size$offset() {
        return struct_size$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t struct_size
     * }
     */
    public static int struct_size(MemorySegment struct) {
        return struct.get(struct_size$LAYOUT, struct_size$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t struct_size
     * }
     */
    public static void struct_size(MemorySegment struct, int fieldValue) {
        struct.set(struct_size$LAYOUT, struct_size$OFFSET, fieldValue);
    }

    private static final OfInt policy$LAYOUT = (OfInt)$LAYOUT.select(groupElement("policy"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t policy
     * }
     */
    public static final OfInt policy$layout() {
        return policy$LAYOUT;
    }

    private static final long policy$OFFSET = 4;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t policy
     * }
     */
    public static final long policy$offset() {
        return policy$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t policy
     * }
     */
    public static int policy(MemorySegment struct) {
        return struct.get(policy$LAYOUT, policy$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t policy
     * }
     */
    public static void policy(MemorySegment struct, int fieldValue) {
        struct.set(policy$LAYOUT, policy$OFFSET, fieldValue);
    }

    private static final OfInt kind_mask$LAYOUT = (OfInt)$LAYOUT.select(groupElement("kind_mask"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t kind_mask
     * }
     */
    public static final OfInt kind_mask$layout() {
        return kind_mask$LAYOUT;
    }

    private static final long kind_mask$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t kind_mask
     * }
     */
    public static final long kind_mask$offset() {
        return kind_mask$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t kind_mask
     * }
     */
    public static int kind_mask(MemorySegment struct) {
        return struct.get(kind_mask$LAYOUT, kind_mask$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t kind_mask
     * }
     */
    public static void kind_mask(MemorySegment struct, int fieldValue) {
        struct.set(kind_mask$LAYOUT, kind_mask$OFFSET, fieldValue);
    }

    private static final OfInt ordinal$LAYOUT = (OfInt)$LAYOUT.select(groupElement("ordinal"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t ordinal
     * }
     */
    public static final OfInt ordinal$layout() {
        return ordinal$LAYOUT;
    }

    private static final long ordinal$OFFSET = 12;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t ordinal
     * }
     */
    public static final long ordinal$offset() {
        return ordinal$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t ordinal
     * }
     */
    public static int ordinal(MemorySegment struct) {
        return struct.get(ordinal$LAYOUT, ordinal$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t ordinal
     * }
     */
    public static void ordinal(MemorySegment struct, int fieldValue) {
        struct.set(ordinal$LAYOUT, ordinal$OFFSET, fieldValue);
    }

    private static final GroupLayout provider_id$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("provider_id"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct turbo_text provider_id
     * }
     */
    public static final GroupLayout provider_id$layout() {
        return provider_id$LAYOUT;
    }

    private static final long provider_id$OFFSET = 16;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct turbo_text provider_id
     * }
     */
    public static final long provider_id$offset() {
        return provider_id$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct turbo_text provider_id
     * }
     */
    public static MemorySegment provider_id(MemorySegment struct) {
        return struct.asSlice(provider_id$OFFSET, provider_id$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct turbo_text provider_id
     * }
     */
    public static void provider_id(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, provider_id$OFFSET, provider_id$LAYOUT.byteSize());
    }

    private static final GroupLayout vendor$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("vendor"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct turbo_text vendor
     * }
     */
    public static final GroupLayout vendor$layout() {
        return vendor$LAYOUT;
    }

    private static final long vendor$OFFSET = 32;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct turbo_text vendor
     * }
     */
    public static final long vendor$offset() {
        return vendor$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct turbo_text vendor
     * }
     */
    public static MemorySegment vendor(MemorySegment struct) {
        return struct.asSlice(vendor$OFFSET, vendor$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct turbo_text vendor
     * }
     */
    public static void vendor(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, vendor$OFFSET, vendor$LAYOUT.byteSize());
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

