// Generated by jextract

package ai.pipestream.turbo.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct turbo_runtime_desc {
 *     uint32_t struct_size;
 *     uint32_t flags;
 *     uint32_t n_provider_paths;
 *     uint32_t reserved;
 *     const struct turbo_text *provider_paths;
 *     turbo_log_fn log;
 *     void *log_user_data;
 * }
 * }
 */
public class turbo_runtime_desc {

    turbo_runtime_desc() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        TurboNative.C_INT.withName("struct_size"),
        TurboNative.C_INT.withName("flags"),
        TurboNative.C_INT.withName("n_provider_paths"),
        TurboNative.C_INT.withName("reserved"),
        TurboNative.C_POINTER.withName("provider_paths"),
        TurboNative.C_POINTER.withName("log"),
        TurboNative.C_POINTER.withName("log_user_data")
    ).withName("turbo_runtime_desc");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt struct_size$LAYOUT = (OfInt)$LAYOUT.select(groupElement("struct_size"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t struct_size
     * }
     */
    public static final OfInt struct_size$layout() {
        return struct_size$LAYOUT;
    }

    private static final long struct_size$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t struct_size
     * }
     */
    public static final long struct_size$offset() {
        return struct_size$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t struct_size
     * }
     */
    public static int struct_size(MemorySegment struct) {
        return struct.get(struct_size$LAYOUT, struct_size$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t struct_size
     * }
     */
    public static void struct_size(MemorySegment struct, int fieldValue) {
        struct.set(struct_size$LAYOUT, struct_size$OFFSET, fieldValue);
    }

    private static final OfInt flags$LAYOUT = (OfInt)$LAYOUT.select(groupElement("flags"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t flags
     * }
     */
    public static final OfInt flags$layout() {
        return flags$LAYOUT;
    }

    private static final long flags$OFFSET = 4;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t flags
     * }
     */
    public static final long flags$offset() {
        return flags$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t flags
     * }
     */
    public static int flags(MemorySegment struct) {
        return struct.get(flags$LAYOUT, flags$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t flags
     * }
     */
    public static void flags(MemorySegment struct, int fieldValue) {
        struct.set(flags$LAYOUT, flags$OFFSET, fieldValue);
    }

    private static final OfInt n_provider_paths$LAYOUT = (OfInt)$LAYOUT.select(groupElement("n_provider_paths"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t n_provider_paths
     * }
     */
    public static final OfInt n_provider_paths$layout() {
        return n_provider_paths$LAYOUT;
    }

    private static final long n_provider_paths$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t n_provider_paths
     * }
     */
    public static final long n_provider_paths$offset() {
        return n_provider_paths$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t n_provider_paths
     * }
     */
    public static int n_provider_paths(MemorySegment struct) {
        return struct.get(n_provider_paths$LAYOUT, n_provider_paths$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t n_provider_paths
     * }
     */
    public static void n_provider_paths(MemorySegment struct, int fieldValue) {
        struct.set(n_provider_paths$LAYOUT, n_provider_paths$OFFSET, fieldValue);
    }

    private static final OfInt reserved$LAYOUT = (OfInt)$LAYOUT.select(groupElement("reserved"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t reserved
     * }
     */
    public static final OfInt reserved$layout() {
        return reserved$LAYOUT;
    }

    private static final long reserved$OFFSET = 12;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t reserved
     * }
     */
    public static final long reserved$offset() {
        return reserved$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t reserved
     * }
     */
    public static int reserved(MemorySegment struct) {
        return struct.get(reserved$LAYOUT, reserved$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t reserved
     * }
     */
    public static void reserved(MemorySegment struct, int fieldValue) {
        struct.set(reserved$LAYOUT, reserved$OFFSET, fieldValue);
    }

    private static final AddressLayout provider_paths$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("provider_paths"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const struct turbo_text *provider_paths
     * }
     */
    public static final AddressLayout provider_paths$layout() {
        return provider_paths$LAYOUT;
    }

    private static final long provider_paths$OFFSET = 16;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const struct turbo_text *provider_paths
     * }
     */
    public static final long provider_paths$offset() {
        return provider_paths$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const struct turbo_text *provider_paths
     * }
     */
    public static MemorySegment provider_paths(MemorySegment struct) {
        return struct.get(provider_paths$LAYOUT, provider_paths$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const struct turbo_text *provider_paths
     * }
     */
    public static void provider_paths(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(provider_paths$LAYOUT, provider_paths$OFFSET, fieldValue);
    }

    private static final AddressLayout log$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("log"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * turbo_log_fn log
     * }
     */
    public static final AddressLayout log$layout() {
        return log$LAYOUT;
    }

    private static final long log$OFFSET = 24;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * turbo_log_fn log
     * }
     */
    public static final long log$offset() {
        return log$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * turbo_log_fn log
     * }
     */
    public static MemorySegment log(MemorySegment struct) {
        return struct.get(log$LAYOUT, log$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * turbo_log_fn log
     * }
     */
    public static void log(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(log$LAYOUT, log$OFFSET, fieldValue);
    }

    private static final AddressLayout log_user_data$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("log_user_data"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void *log_user_data
     * }
     */
    public static final AddressLayout log_user_data$layout() {
        return log_user_data$LAYOUT;
    }

    private static final long log_user_data$OFFSET = 32;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void *log_user_data
     * }
     */
    public static final long log_user_data$offset() {
        return log_user_data$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void *log_user_data
     * }
     */
    public static MemorySegment log_user_data(MemorySegment struct) {
        return struct.get(log_user_data$LAYOUT, log_user_data$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void *log_user_data
     * }
     */
    public static void log_user_data(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(log_user_data$LAYOUT, log_user_data$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

