// Generated by jextract

package ai.pipestream.turbo.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct turbo_session_stats {
 *     uint32_t struct_size;
 *     uint32_t reserved;
 *     uint64_t runs;
 *     uint64_t host_allocs;
 *     uint64_t h2d_bytes;
 *     uint64_t d2h_bytes;
 *     uint64_t input_bytes;
 *     uint64_t output_bytes;
 *     uint64_t provider_allocs;
 * }
 * }
 */
public class turbo_session_stats {

    turbo_session_stats() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        TurboNative.C_INT.withName("struct_size"),
        TurboNative.C_INT.withName("reserved"),
        TurboNative.C_LONG.withName("runs"),
        TurboNative.C_LONG.withName("host_allocs"),
        TurboNative.C_LONG.withName("h2d_bytes"),
        TurboNative.C_LONG.withName("d2h_bytes"),
        TurboNative.C_LONG.withName("input_bytes"),
        TurboNative.C_LONG.withName("output_bytes"),
        TurboNative.C_LONG.withName("provider_allocs")
    ).withName("turbo_session_stats");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt struct_size$LAYOUT = (OfInt)$LAYOUT.select(groupElement("struct_size"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t struct_size
     * }
     */
    public static final OfInt struct_size$layout() {
        return struct_size$LAYOUT;
    }

    private static final long struct_size$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t struct_size
     * }
     */
    public static final long struct_size$offset() {
        return struct_size$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t struct_size
     * }
     */
    public static int struct_size(MemorySegment struct) {
        return struct.get(struct_size$LAYOUT, struct_size$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t struct_size
     * }
     */
    public static void struct_size(MemorySegment struct, int fieldValue) {
        struct.set(struct_size$LAYOUT, struct_size$OFFSET, fieldValue);
    }

    private static final OfInt reserved$LAYOUT = (OfInt)$LAYOUT.select(groupElement("reserved"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t reserved
     * }
     */
    public static final OfInt reserved$layout() {
        return reserved$LAYOUT;
    }

    private static final long reserved$OFFSET = 4;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t reserved
     * }
     */
    public static final long reserved$offset() {
        return reserved$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t reserved
     * }
     */
    public static int reserved(MemorySegment struct) {
        return struct.get(reserved$LAYOUT, reserved$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t reserved
     * }
     */
    public static void reserved(MemorySegment struct, int fieldValue) {
        struct.set(reserved$LAYOUT, reserved$OFFSET, fieldValue);
    }

    private static final OfLong runs$LAYOUT = (OfLong)$LAYOUT.select(groupElement("runs"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint64_t runs
     * }
     */
    public static final OfLong runs$layout() {
        return runs$LAYOUT;
    }

    private static final long runs$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint64_t runs
     * }
     */
    public static final long runs$offset() {
        return runs$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint64_t runs
     * }
     */
    public static long runs(MemorySegment struct) {
        return struct.get(runs$LAYOUT, runs$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint64_t runs
     * }
     */
    public static void runs(MemorySegment struct, long fieldValue) {
        struct.set(runs$LAYOUT, runs$OFFSET, fieldValue);
    }

    private static final OfLong host_allocs$LAYOUT = (OfLong)$LAYOUT.select(groupElement("host_allocs"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint64_t host_allocs
     * }
     */
    public static final OfLong host_allocs$layout() {
        return host_allocs$LAYOUT;
    }

    private static final long host_allocs$OFFSET = 16;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint64_t host_allocs
     * }
     */
    public static final long host_allocs$offset() {
        return host_allocs$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint64_t host_allocs
     * }
     */
    public static long host_allocs(MemorySegment struct) {
        return struct.get(host_allocs$LAYOUT, host_allocs$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint64_t host_allocs
     * }
     */
    public static void host_allocs(MemorySegment struct, long fieldValue) {
        struct.set(host_allocs$LAYOUT, host_allocs$OFFSET, fieldValue);
    }

    private static final OfLong h2d_bytes$LAYOUT = (OfLong)$LAYOUT.select(groupElement("h2d_bytes"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint64_t h2d_bytes
     * }
     */
    public static final OfLong h2d_bytes$layout() {
        return h2d_bytes$LAYOUT;
    }

    private static final long h2d_bytes$OFFSET = 24;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint64_t h2d_bytes
     * }
     */
    public static final long h2d_bytes$offset() {
        return h2d_bytes$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint64_t h2d_bytes
     * }
     */
    public static long h2d_bytes(MemorySegment struct) {
        return struct.get(h2d_bytes$LAYOUT, h2d_bytes$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint64_t h2d_bytes
     * }
     */
    public static void h2d_bytes(MemorySegment struct, long fieldValue) {
        struct.set(h2d_bytes$LAYOUT, h2d_bytes$OFFSET, fieldValue);
    }

    private static final OfLong d2h_bytes$LAYOUT = (OfLong)$LAYOUT.select(groupElement("d2h_bytes"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint64_t d2h_bytes
     * }
     */
    public static final OfLong d2h_bytes$layout() {
        return d2h_bytes$LAYOUT;
    }

    private static final long d2h_bytes$OFFSET = 32;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint64_t d2h_bytes
     * }
     */
    public static final long d2h_bytes$offset() {
        return d2h_bytes$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint64_t d2h_bytes
     * }
     */
    public static long d2h_bytes(MemorySegment struct) {
        return struct.get(d2h_bytes$LAYOUT, d2h_bytes$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint64_t d2h_bytes
     * }
     */
    public static void d2h_bytes(MemorySegment struct, long fieldValue) {
        struct.set(d2h_bytes$LAYOUT, d2h_bytes$OFFSET, fieldValue);
    }

    private static final OfLong input_bytes$LAYOUT = (OfLong)$LAYOUT.select(groupElement("input_bytes"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint64_t input_bytes
     * }
     */
    public static final OfLong input_bytes$layout() {
        return input_bytes$LAYOUT;
    }

    private static final long input_bytes$OFFSET = 40;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint64_t input_bytes
     * }
     */
    public static final long input_bytes$offset() {
        return input_bytes$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint64_t input_bytes
     * }
     */
    public static long input_bytes(MemorySegment struct) {
        return struct.get(input_bytes$LAYOUT, input_bytes$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint64_t input_bytes
     * }
     */
    public static void input_bytes(MemorySegment struct, long fieldValue) {
        struct.set(input_bytes$LAYOUT, input_bytes$OFFSET, fieldValue);
    }

    private static final OfLong output_bytes$LAYOUT = (OfLong)$LAYOUT.select(groupElement("output_bytes"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint64_t output_bytes
     * }
     */
    public static final OfLong output_bytes$layout() {
        return output_bytes$LAYOUT;
    }

    private static final long output_bytes$OFFSET = 48;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint64_t output_bytes
     * }
     */
    public static final long output_bytes$offset() {
        return output_bytes$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint64_t output_bytes
     * }
     */
    public static long output_bytes(MemorySegment struct) {
        return struct.get(output_bytes$LAYOUT, output_bytes$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint64_t output_bytes
     * }
     */
    public static void output_bytes(MemorySegment struct, long fieldValue) {
        struct.set(output_bytes$LAYOUT, output_bytes$OFFSET, fieldValue);
    }

    private static final OfLong provider_allocs$LAYOUT = (OfLong)$LAYOUT.select(groupElement("provider_allocs"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint64_t provider_allocs
     * }
     */
    public static final OfLong provider_allocs$layout() {
        return provider_allocs$LAYOUT;
    }

    private static final long provider_allocs$OFFSET = 56;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint64_t provider_allocs
     * }
     */
    public static final long provider_allocs$offset() {
        return provider_allocs$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint64_t provider_allocs
     * }
     */
    public static long provider_allocs(MemorySegment struct) {
        return struct.get(provider_allocs$LAYOUT, provider_allocs$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint64_t provider_allocs
     * }
     */
    public static void provider_allocs(MemorySegment struct, long fieldValue) {
        struct.set(provider_allocs$LAYOUT, provider_allocs$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

