// Generated by jextract

package ai.pipestream.turbo.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct turbo_chunk {
 *     uint64_t byte_start;
 *     uint64_t byte_end;
 *     uint32_t paragraph;
 *     uint32_t n_tokens;
 * }
 * }
 */
public class turbo_chunk {

    turbo_chunk() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        TurboNative.C_LONG.withName("byte_start"),
        TurboNative.C_LONG.withName("byte_end"),
        TurboNative.C_INT.withName("paragraph"),
        TurboNative.C_INT.withName("n_tokens")
    ).withName("turbo_chunk");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfLong byte_start$LAYOUT = (OfLong)$LAYOUT.select(groupElement("byte_start"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint64_t byte_start
     * }
     */
    public static final OfLong byte_start$layout() {
        return byte_start$LAYOUT;
    }

    private static final long byte_start$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint64_t byte_start
     * }
     */
    public static final long byte_start$offset() {
        return byte_start$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint64_t byte_start
     * }
     */
    public static long byte_start(MemorySegment struct) {
        return struct.get(byte_start$LAYOUT, byte_start$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint64_t byte_start
     * }
     */
    public static void byte_start(MemorySegment struct, long fieldValue) {
        struct.set(byte_start$LAYOUT, byte_start$OFFSET, fieldValue);
    }

    private static final OfLong byte_end$LAYOUT = (OfLong)$LAYOUT.select(groupElement("byte_end"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint64_t byte_end
     * }
     */
    public static final OfLong byte_end$layout() {
        return byte_end$LAYOUT;
    }

    private static final long byte_end$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint64_t byte_end
     * }
     */
    public static final long byte_end$offset() {
        return byte_end$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint64_t byte_end
     * }
     */
    public static long byte_end(MemorySegment struct) {
        return struct.get(byte_end$LAYOUT, byte_end$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint64_t byte_end
     * }
     */
    public static void byte_end(MemorySegment struct, long fieldValue) {
        struct.set(byte_end$LAYOUT, byte_end$OFFSET, fieldValue);
    }

    private static final OfInt paragraph$LAYOUT = (OfInt)$LAYOUT.select(groupElement("paragraph"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t paragraph
     * }
     */
    public static final OfInt paragraph$layout() {
        return paragraph$LAYOUT;
    }

    private static final long paragraph$OFFSET = 16;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t paragraph
     * }
     */
    public static final long paragraph$offset() {
        return paragraph$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t paragraph
     * }
     */
    public static int paragraph(MemorySegment struct) {
        return struct.get(paragraph$LAYOUT, paragraph$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t paragraph
     * }
     */
    public static void paragraph(MemorySegment struct, int fieldValue) {
        struct.set(paragraph$LAYOUT, paragraph$OFFSET, fieldValue);
    }

    private static final OfInt n_tokens$LAYOUT = (OfInt)$LAYOUT.select(groupElement("n_tokens"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t n_tokens
     * }
     */
    public static final OfInt n_tokens$layout() {
        return n_tokens$LAYOUT;
    }

    private static final long n_tokens$OFFSET = 20;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t n_tokens
     * }
     */
    public static final long n_tokens$offset() {
        return n_tokens$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t n_tokens
     * }
     */
    public static int n_tokens(MemorySegment struct) {
        return struct.get(n_tokens$LAYOUT, n_tokens$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t n_tokens
     * }
     */
    public static void n_tokens(MemorySegment struct, int fieldValue) {
        struct.set(n_tokens$LAYOUT, n_tokens$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

