// Generated by jextract

package ai.pipestream.turbo.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef void (*turbo_log_fn)(void *, uint32_t, struct turbo_text {
 *     const char *ptr;
 *     uint64_t len;
 * })
 * }
 */
public class turbo_log_fn {

    turbo_log_fn() {
        // Should not be called directly
    }

    /**
     * The function pointer signature, expressed as a functional interface
     */
    public interface Function {
        void apply(MemorySegment user_data, int level, MemorySegment message);
    }

    private static final FunctionDescriptor $DESC = FunctionDescriptor.ofVoid(
        TurboNative.C_POINTER,
        TurboNative.C_INT,
        turbo_text.layout()
    );

    /**
     * The descriptor of this function pointer
     */
    public static FunctionDescriptor descriptor() {
        return $DESC;
    }

    private static final MethodHandle UP$MH = TurboNative.upcallHandle(turbo_log_fn.Function.class, "apply", $DESC);

    /**
     * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
     * The lifetime of the returned segment is managed by {@code arena}
     */
    public static MemorySegment allocate(turbo_log_fn.Function fi, Arena arena) {
        return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
    }

    private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

    /**
     * Invoke the upcall stub {@code funcPtr}, with given parameters
     */
    public static void invoke(MemorySegment funcPtr,MemorySegment user_data, int level, MemorySegment message) {
        try {
             DOWN$MH.invokeExact(funcPtr, user_data, level, message);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
}

