//! C ABI types and constants for Turbo.
//!
//! This crate is the single source of the public C header
//! (`include/turbo/turbo.h`, generated by cbindgen from `turbo-capi`, which
//! re-exports everything here). Every type is `#[repr(C)]`, every enumeration
//! in ABI position is a `u32` with named constants, every public struct starts
//! with `struct_size`, and every length is fixed-width.
//!
//! Rules (see PLAN.md section 4.3):
//! - A caller sets `struct_size = sizeof(struct)` for the version it compiled
//!   against. The library reads only fields below that size. Appended fields
//!   must have a zero value meaning "old behavior".
//! - Strings are UTF-8 pointer+length views ([`turbo_text`]). Fixed `char`
//!   arrays in output structs are NUL-terminated UTF-8.
//! - Handles are opaque and reference counted inside the library. Child
//!   handles retain their parents.
//! - Errors are caller-owned ([`turbo_error`]); no thread-local or shared
//!   error state exists.

#![no_std]
#![allow(non_camel_case_types)]
#![deny(missing_docs)]

use core::ffi::c_char;
use core::ffi::c_void;

pub mod provider;
pub mod versioned;
pub use provider::*;
pub use versioned::Versioned;

/// ABI version. Bumped only for a breaking layout or semantic change.
pub const TURBO_ABI_VERSION: u32 = 2;

// ---------------------------------------------------------------------------
// Status codes
// ---------------------------------------------------------------------------
//
// Graded so callers can branch on the hundreds digit:
//   0x000 ok
//   0x1xx argument / contract violation by the caller
//   0x2xx unsupported on this device, model, or option (capability)
//   0x3xx resource (memory, busy, capacity)
//   0x4xx device / runtime / provider failure
//   0x5xx bundle integrity
//   0x6xx internal

/// Success.
pub const TURBO_OK: i32 = 0;
/// A caller argument is invalid; `turbo_error.field` may name it.
pub const TURBO_E_INVALID_ARGUMENT: i32 = 0x100;
/// A descriptor's `struct_size` is not one this library understands.
pub const TURBO_E_INVALID_STRUCT_SIZE: i32 = 0x101;
/// A text view is not valid UTF-8.
pub const TURBO_E_INVALID_UTF8: i32 = 0x102;
/// A handle is null or of the wrong kind.
pub const TURBO_E_INVALID_HANDLE: i32 = 0x103;
/// A shape, stride, or byte count is inconsistent or overflows.
pub const TURBO_E_INVALID_SHAPE: i32 = 0x104;
/// The operation is not valid in the handle's current state (for example
/// `run` before any input was written, or use after cancel).
pub const TURBO_E_INVALID_STATE: i32 = 0x105;
/// A constant (dtype, task, option value) is outside the known set.
pub const TURBO_E_INVALID_ENUM: i32 = 0x106;
/// The requested combination is unsupported here; see `message`.
pub const TURBO_E_UNSUPPORTED: i32 = 0x200;
/// An option field is not honored by this provider for this model;
/// `turbo_error.field` is the 1-based field index in the options struct.
pub const TURBO_E_UNSUPPORTED_OPTION: i32 = 0x201;
/// The task is not offered on this device for this model.
pub const TURBO_E_UNSUPPORTED_TASK: i32 = 0x202;
/// The dtype is not supported in the requested placement.
pub const TURBO_E_UNSUPPORTED_DTYPE: i32 = 0x203;
/// The placement is not supported by this device.
pub const TURBO_E_UNSUPPORTED_PLACEMENT: i32 = 0x204;
/// Declared in the header but not implemented in this build. Never a silent fallback.
pub const TURBO_E_NOT_IMPLEMENTED: i32 = 0x205;
/// The modality is not offered on this device for this model.
pub const TURBO_E_UNSUPPORTED_MODALITY: i32 = 0x206;
/// Allocation failed.
pub const TURBO_E_OUT_OF_MEMORY: i32 = 0x300;
/// The session or generation has an operation or result lease in flight.
pub const TURBO_E_BUSY: i32 = 0x301;
/// The provider is refusing new work; retry later.
pub const TURBO_E_OVERLOADED: i32 = 0x302;
/// The request exceeds a declared capacity (batch, sequence, output size).
pub const TURBO_E_CAPACITY: i32 = 0x303;
/// No device matches the selector.
pub const TURBO_E_DEVICE_NOT_FOUND: i32 = 0x400;
/// The device exists but cannot be used (driver missing, busy, failed probe).
pub const TURBO_E_DEVICE_UNAVAILABLE: i32 = 0x401;
/// The vendor runtime reported an error; `message` carries its text.
pub const TURBO_E_RUNTIME: i32 = 0x402;
/// A provider library could not be loaded or did not export the entry point.
pub const TURBO_E_PROVIDER_LOAD: i32 = 0x403;
/// A provider library targets a different ABI version.
pub const TURBO_E_ABI_MISMATCH: i32 = 0x404;
/// The operation was cancelled by the caller.
pub const TURBO_E_CANCELLED: i32 = 0x405;
/// The bundle directory or a required file is missing.
pub const TURBO_E_BUNDLE_NOT_FOUND: i32 = 0x500;
/// The bundle manifest is malformed or declares an unknown version.
pub const TURBO_E_BUNDLE_INVALID: i32 = 0x501;
/// A bundle file does not match its recorded hash.
pub const TURBO_E_BUNDLE_INTEGRITY: i32 = 0x502;
/// The bundle is valid but no artifact in it is loadable by this provider.
pub const TURBO_E_BUNDLE_NO_ARTIFACT: i32 = 0x503;
/// A bug in the library or provider.
pub const TURBO_E_INTERNAL: i32 = 0x600;
/// A panic or exception was caught at the language boundary.
pub const TURBO_E_PANIC: i32 = 0x601;

// ---------------------------------------------------------------------------
// Enumerations (u32 constants)
// ---------------------------------------------------------------------------

/// Device kind: CPU.
pub const TURBO_DEVICE_CPU: u32 = 1;
/// Device kind: discrete GPU.
pub const TURBO_DEVICE_GPU: u32 = 2;
/// Device kind: integrated GPU.
pub const TURBO_DEVICE_IGPU: u32 = 3;
/// Device kind: neural processing unit.
pub const TURBO_DEVICE_NPU: u32 = 4;
/// Device kind: other accelerator.
pub const TURBO_DEVICE_ACCEL: u32 = 5;

/// Task: dense text embedding.
pub const TURBO_TASK_EMBED: u32 = 1;
/// Task: cross-encoder reranking.
pub const TURBO_TASK_RERANK: u32 = 2;
/// Task: sequence classification with labels.
pub const TURBO_TASK_CLASSIFY: u32 = 3;
/// Task: per-token classification with span aggregation.
pub const TURBO_TASK_TOKEN_CLASSIFY: u32 = 4;
/// Task: causal generation.
pub const TURBO_TASK_GENERATE: u32 = 5;
/// Task: tokenize / detokenize.
pub const TURBO_TASK_TOKENIZE: u32 = 6;
/// Task: generic named-tensor execution.
pub const TURBO_TASK_RUN: u32 = 7;
/// Task: source chunking (host utility).
pub const TURBO_TASK_CHUNK: u32 = 8;

/// Modality: text.
pub const TURBO_MODALITY_TEXT: u32 = 1;
/// Modality: audio.
pub const TURBO_MODALITY_AUDIO: u32 = 2;
/// Modality: image.
pub const TURBO_MODALITY_IMAGE: u32 = 3;
/// Modality: video.
pub const TURBO_MODALITY_VIDEO: u32 = 4;

/// Capability status: not offered.
pub const TURBO_CAP_UNSUPPORTED: u32 = 0;
/// Capability status: planned, code path may exist but is not qualified.
pub const TURBO_CAP_PLANNED: u32 = 1;
/// Capability status: works, not yet qualified with receipts.
pub const TURBO_CAP_EXPERIMENTAL: u32 = 2;
/// Capability status: qualified with conformance, precision, and benchmark receipts.
pub const TURBO_CAP_SUPPORTED: u32 = 3;

/// Model kind: embedder.
pub const TURBO_MODEL_EMBEDDING: u32 = 1;
/// Model kind: cross-encoder reranker.
pub const TURBO_MODEL_RERANKER: u32 = 2;
/// Model kind: sequence classifier.
pub const TURBO_MODEL_CLASSIFIER: u32 = 3;
/// Model kind: token classifier.
pub const TURBO_MODEL_TOKEN_CLASSIFIER: u32 = 4;
/// Model kind: generative language model.
pub const TURBO_MODEL_GENERATIVE: u32 = 5;
/// Model kind: generic graph with named inputs and outputs.
pub const TURBO_MODEL_GENERIC: u32 = 6;

/// Element type: boolean (one byte).
pub const TURBO_DTYPE_BOOL: u32 = 1;
/// Element type: unsigned 8-bit.
pub const TURBO_DTYPE_U8: u32 = 2;
/// Element type: unsigned 16-bit.
pub const TURBO_DTYPE_U16: u32 = 3;
/// Element type: unsigned 32-bit.
pub const TURBO_DTYPE_U32: u32 = 4;
/// Element type: unsigned 64-bit.
pub const TURBO_DTYPE_U64: u32 = 5;
/// Element type: signed 8-bit.
pub const TURBO_DTYPE_I8: u32 = 6;
/// Element type: signed 16-bit.
pub const TURBO_DTYPE_I16: u32 = 7;
/// Element type: signed 32-bit.
pub const TURBO_DTYPE_I32: u32 = 8;
/// Element type: signed 64-bit.
pub const TURBO_DTYPE_I64: u32 = 9;
/// Element type: IEEE half.
pub const TURBO_DTYPE_F16: u32 = 10;
/// Element type: bfloat16.
pub const TURBO_DTYPE_BF16: u32 = 11;
/// Element type: IEEE single.
pub const TURBO_DTYPE_F32: u32 = 12;
/// Element type: IEEE double.
pub const TURBO_DTYPE_F64: u32 = 13;
/// Element type: length-prefixed byte strings (KServe BYTES): each element is
/// a little-endian `uint32_t` length followed by that many bytes.
pub const TURBO_DTYPE_BYTES: u32 = 14;

/// Placement: pageable host memory.
pub const TURBO_PLACE_HOST: u32 = 1;
/// Placement: page-locked host memory visible to the device.
pub const TURBO_PLACE_PINNED: u32 = 2;
/// Placement: device memory.
pub const TURBO_PLACE_DEVICE: u32 = 3;
/// Placement: memory shared between host and device (unified / USM shared).
pub const TURBO_PLACE_SHARED: u32 = 4;

/// Device selection policy: the host's best accelerator; never CPU.
pub const TURBO_SELECT_AUTO: u32 = 0;
/// Device selection policy: exactly the device the selector names.
pub const TURBO_SELECT_EXPLICIT: u32 = 1;

/// Pipeline stage index: tokenization.
pub const TURBO_STAGE_TOKENIZE: u32 = 0;
/// Pipeline stage index: encoder / model forward.
pub const TURBO_STAGE_ENCODE: u32 = 1;
/// Pipeline stage index: pooling.
pub const TURBO_STAGE_POOL: u32 = 2;
/// Pipeline stage index: normalization.
pub const TURBO_STAGE_NORMALIZE: u32 = 3;
/// Pipeline stage index: post-processing (softmax, aggregation, sampling).
pub const TURBO_STAGE_POSTPROCESS: u32 = 4;
/// Number of pipeline stages reported.
pub const TURBO_STAGE_COUNT: usize = 5;

/// Stage placement: the stage does not apply to this model.
pub const TURBO_STAGE_UNUSED: u32 = 0;
/// Stage placement: runs on the host.
pub const TURBO_STAGE_HOST: u32 = 1;
/// Stage placement: runs on the device as a separate step.
pub const TURBO_STAGE_DEVICE: u32 = 2;
/// Stage placement: fused into the device graph with adjacent stages.
pub const TURBO_STAGE_FUSED: u32 = 3;

/// Option value meaning "use the model contract".
pub const TURBO_OPT_MODEL: u32 = 0;

/// Truncation: as the model contract says (`TURBO_OPT_MODEL`). The bundle
/// contract carries no truncation field today, so every text provider
/// resolves MODEL to RIGHT (the BERT convention: keep the head of the
/// text); a provider that resolved it differently would say so in its
/// README and its capability notes.
pub const TURBO_TRUNCATE_MODEL: u32 = 0;
/// Truncation: never; over-length input is an error.
pub const TURBO_TRUNCATE_NONE: u32 = 1;
/// Truncation: drop tokens from the end.
pub const TURBO_TRUNCATE_RIGHT: u32 = 2;
/// Truncation: drop tokens from the start.
pub const TURBO_TRUNCATE_LEFT: u32 = 3;

/// Prompt role: no prefix.
pub const TURBO_PROMPT_NONE: u32 = 0;
/// Prompt role: apply the bundle's query prefix.
pub const TURBO_PROMPT_QUERY: u32 = 1;
/// Prompt role: apply the bundle's document prefix.
pub const TURBO_PROMPT_DOCUMENT: u32 = 2;

/// Normalization: as the model contract says.
pub const TURBO_NORMALIZE_MODEL: u32 = 0;
/// Normalization: none.
pub const TURBO_NORMALIZE_NONE: u32 = 1;
/// Normalization: L2.
pub const TURBO_NORMALIZE_L2: u32 = 2;

/// Pooling: as the model contract says.
pub const TURBO_POOLING_MODEL: u32 = 0;
/// Pooling: masked mean.
pub const TURBO_POOLING_MEAN: u32 = 1;
/// Pooling: first token.
pub const TURBO_POOLING_CLS: u32 = 2;
/// Pooling: last non-padding token.
pub const TURBO_POOLING_LAST: u32 = 3;

/// Output dtype: as the model contract says.
pub const TURBO_OUTPUT_MODEL: u32 = 0;
/// Output dtype: FP32.
pub const TURBO_OUTPUT_F32: u32 = 1;
/// Output dtype: FP16.
pub const TURBO_OUTPUT_F16: u32 = 2;
/// Output dtype: int8 quantized.
pub const TURBO_OUTPUT_I8: u32 = 3;

/// Token-classification aggregation: as the model contract says.
pub const TURBO_AGGREGATE_MODEL: u32 = 0;
/// Token-classification aggregation: none, per-token labels only.
pub const TURBO_AGGREGATE_NONE: u32 = 1;
/// Token-classification aggregation: merge consecutive same-label tokens.
pub const TURBO_AGGREGATE_SIMPLE: u32 = 2;
/// Token-classification aggregation: label of the first sub-token wins.
pub const TURBO_AGGREGATE_FIRST: u32 = 3;
/// Token-classification aggregation: highest-scoring sub-token wins.
pub const TURBO_AGGREGATE_MAX: u32 = 4;

/// Generation finish reason: not finished.
pub const TURBO_FINISH_NONE: u32 = 0;
/// Generation finish reason: end-of-sequence token.
pub const TURBO_FINISH_EOS: u32 = 1;
/// Generation finish reason: a stop string or stop token matched.
pub const TURBO_FINISH_STOP: u32 = 2;
/// Generation finish reason: `max_new_tokens` reached.
pub const TURBO_FINISH_LENGTH: u32 = 3;
/// Generation finish reason: cancelled by the caller.
pub const TURBO_FINISH_CANCELLED: u32 = 4;

/// Structured output: none.
pub const TURBO_STRUCTURED_NONE: u32 = 0;
/// Structured output: constrain to a JSON schema (text is the schema).
pub const TURBO_STRUCTURED_JSON_SCHEMA: u32 = 1;
/// Structured output: constrain to a grammar (text is GBNF).
pub const TURBO_STRUCTURED_GRAMMAR: u32 = 2;

/// Push-generation callback return: keep generating.
pub const TURBO_STREAM_CONTINUE: u32 = 0;
/// Push-generation callback return: stop after this chunk.
pub const TURBO_STREAM_STOP: u32 = 1;

/// Native handle kind: host pointer.
pub const TURBO_HANDLE_HOST_PTR: u32 = 1;
/// Native handle kind: CUDA device pointer (`aux` = device ordinal).
pub const TURBO_HANDLE_CUDA_PTR: u32 = 2;
/// Native handle kind: OpenCL `cl_mem` (`aux` = `cl_context`).
pub const TURBO_HANDLE_CL_MEM: u32 = 3;
/// Native handle kind: Level Zero USM pointer (`aux` = `ze_context_handle_t`).
pub const TURBO_HANDLE_ZE_USM: u32 = 4;
/// Native handle kind: Metal `MTLBuffer` (`aux` = `MTLDevice`).
pub const TURBO_HANDLE_MTL_BUFFER: u32 = 5;
/// Native handle kind: Linux DMA-BUF file descriptor.
pub const TURBO_HANDLE_DMABUF_FD: u32 = 6;

/// I/O direction: model input.
pub const TURBO_IO_INPUT: u32 = 1;
/// I/O direction: model output.
pub const TURBO_IO_OUTPUT: u32 = 2;

/// Runtime flag: do not scan the default provider search path.
pub const TURBO_RUNTIME_NO_DEFAULT_PROVIDERS: u32 = 1 << 0;

// ---------------------------------------------------------------------------
// Capability bits (u64)
// ---------------------------------------------------------------------------

/// The device can execute asynchronously (`turbo_session_submit` + fences).
pub const TURBO_CAP_ASYNC: u64 = 0x1;
/// Caller host memory can be imported without a copy.
pub const TURBO_CAP_HOST_PTR_IMPORT: u64 = 0x2;
/// Results can stay resident on the device and be exported.
pub const TURBO_CAP_DEVICE_RESULT: u64 = 0x4;
/// A caller-owned queue/stream can be imported.
pub const TURBO_CAP_EXTERNAL_QUEUE: u64 = 0x8;
/// DMA-BUF import.
pub const TURBO_CAP_DMABUF: u64 = 0x10;
/// Host and device share one address space (unified / USM shared).
pub const TURBO_CAP_UNIFIED_MEMORY: u64 = 0x20;
/// Sessions may run any shape up to their maximum without recompiling.
pub const TURBO_CAP_DYNAMIC_SHAPE: u64 = 0x40;
/// Sessions on one model share weights.
pub const TURBO_CAP_WEIGHT_SHARING: u64 = 0x80;
/// Tokenization runs on the device from raw UTF-8.
pub const TURBO_CAP_DEVICE_TOKENIZE: u64 = 0x100;
/// Post-processing (softmax, aggregation) runs on the device.
pub const TURBO_CAP_DEVICE_POSTPROCESS: u64 = 0x200;
/// Deterministic results across runs for the same inputs and seed.
pub const TURBO_CAP_DETERMINISTIC: u64 = 0x400;

/// Option `truncate` is honored.
pub const TURBO_CAP_OPT_TRUNCATE: u64 = 0x10000;
/// Option `max_tokens` is honored.
pub const TURBO_CAP_OPT_MAX_TOKENS: u64 = 0x20000;
/// Option `prompt_role` is honored.
pub const TURBO_CAP_OPT_PROMPT_ROLE: u64 = 0x40000;
/// Option `normalize` may differ from the model contract.
pub const TURBO_CAP_OPT_NORMALIZE: u64 = 0x80000;
/// Option `pooling` may differ from the model contract.
pub const TURBO_CAP_OPT_POOLING_OVERRIDE: u64 = 0x100000;
/// Option `output_dim` (Matryoshka truncation) is honored.
pub const TURBO_CAP_OPT_OUTPUT_DIM: u64 = 0x200000;
/// Option `output_dtype` is honored.
pub const TURBO_CAP_OPT_OUTPUT_DTYPE: u64 = 0x400000;
/// Rerank `top_n` and sorted output are computed by the provider.
pub const TURBO_CAP_OPT_TOP_N: u64 = 0x800000;
/// Token-classification `aggregation` may differ from the model contract.
pub const TURBO_CAP_OPT_AGGREGATION: u64 = 0x1000000;
/// Rerank and classify `raw_scores` (logits instead of activated scores) is honored.
pub const TURBO_CAP_OPT_RAW_SCORES: u64 = 0x2000000;

/// Generation: structured output as a GBNF grammar (`structured_kind =
/// TURBO_STRUCTURED_GRAMMAR`); a JSON schema needs `TURBO_CAP_OPT_GEN_JSON_SCHEMA` too.
pub const TURBO_CAP_OPT_GEN_STRUCTURED: u64 = 0x100000000;
/// Generation: tool definitions in the prompt template.
pub const TURBO_CAP_OPT_GEN_TOOLS: u64 = 0x200000000;
/// Generation: `n_sequences > 1`.
pub const TURBO_CAP_OPT_GEN_N: u64 = 0x400000000;
/// Generation: `logit_bias`.
pub const TURBO_CAP_OPT_GEN_LOGIT_BIAS: u64 = 0x800000000;
/// Generation: presence / frequency / repeat penalties.
pub const TURBO_CAP_OPT_GEN_PENALTIES: u64 = 0x1000000000;
/// Generation: per-token logprobs.
pub const TURBO_CAP_OPT_GEN_LOGPROBS: u64 = 0x2000000000;
/// Generation: stop strings (as opposed to stop token ids only).
pub const TURBO_CAP_OPT_GEN_STOP_STRINGS: u64 = 0x4000000000;
/// Generation: `seed` is honored (implies reproducible sampling).
pub const TURBO_CAP_OPT_GEN_SEED: u64 = 0x8000000000;
/// Generation: sampling controls `temperature`, `top_k`, `top_p`, `min_p`.
pub const TURBO_CAP_OPT_GEN_SAMPLING: u64 = 0x10000000000;
/// Generation: `min_new_tokens`.
pub const TURBO_CAP_OPT_GEN_MIN_TOKENS: u64 = 0x20000000000;
/// Generation: `echo` (the prompt is included in the output text).
pub const TURBO_CAP_OPT_GEN_ECHO: u64 = 0x40000000000;
/// Generation: stop token ids.
pub const TURBO_CAP_OPT_GEN_STOP_TOKENS: u64 = 0x80000000000;
/// Generation: `structured_kind = TURBO_STRUCTURED_JSON_SCHEMA` (the
/// provider turns a JSON schema into a constraint itself). Needs
/// `TURBO_CAP_OPT_GEN_STRUCTURED` as well; that bit alone covers GBNF.
pub const TURBO_CAP_OPT_GEN_JSON_SCHEMA: u64 = 0x100000000000;

// ---------------------------------------------------------------------------
// Views and errors
// ---------------------------------------------------------------------------

/// UTF-8 view. `ptr` may be NULL only when `len == 0`. Not NUL-terminated.
#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct turbo_text {
    /// Start of the bytes.
    pub ptr: *const c_char,
    /// Byte length.
    pub len: u64,
}

/// Key / value pair of UTF-8 views, used for provider options and request parameters.
#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct turbo_kv {
    /// Option name.
    pub key: turbo_text,
    /// Option value.
    pub value: turbo_text,
}

/// Length of `turbo_error.message` including the terminating NUL.
pub const TURBO_ERROR_MESSAGE_LEN: usize = 496;

/// Caller-owned error record. On success `code == 0` and `message[0] == 0`.
/// The message is always NUL-terminated UTF-8. `field` is the 1-based index
/// of the offending field in the descriptor for `TURBO_E_UNSUPPORTED_OPTION`
/// and `TURBO_E_INVALID_ARGUMENT`, otherwise 0. May be NULL in any call, in
/// which case only the status code is returned.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct turbo_error {
    /// `sizeof(turbo_error)`.
    pub struct_size: u32,
    /// Status code.
    pub code: i32,
    /// Offending field index, or 0.
    pub field: u32,
    /// NUL-terminated message.
    pub message: [c_char; TURBO_ERROR_MESSAGE_LEN],
}

// ---------------------------------------------------------------------------
// Opaque handles
// ---------------------------------------------------------------------------

/// Library instance owning the provider registry. Thread-safe.
pub struct turbo_runtime {
    _private: [u8; 0],
}
/// Device plus memory domain. Thread-safe.
pub struct turbo_context {
    _private: [u8; 0],
}
/// Typed memory in a placement. Retains its context.
pub struct turbo_buffer {
    _private: [u8; 0],
}
/// Loaded model. Immutable. Retains its context.
pub struct turbo_model {
    _private: [u8; 0],
}
/// Execution workspace with a fixed maximum shape. Single owner. Retains its model.
pub struct turbo_session {
    _private: [u8; 0],
}
/// Leased output of the last operation on a session. Retains its session.
pub struct turbo_result {
    _private: [u8; 0],
}
/// Streaming generation state. Single owner. Retains its model.
pub struct turbo_generation {
    _private: [u8; 0],
}
/// Tokenizer loaded from a bundle. Thread-safe.
pub struct turbo_tokenizer {
    _private: [u8; 0],
}
/// Chunk plan over caller-owned text.
pub struct turbo_chunk_plan {
    _private: [u8; 0],
}

// ---------------------------------------------------------------------------
// Runtime and devices
// ---------------------------------------------------------------------------

/// Log callback: `level` 0 error, 1 warn, 2 info, 3 debug; `message` is a UTF-8 view valid for the call.
pub type turbo_log_fn = Option<unsafe extern "C" fn(user_data: *mut c_void, level: u32, message: turbo_text)>;

/// Runtime creation descriptor.
#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct turbo_runtime_desc {
    /// `sizeof(turbo_runtime_desc)`.
    pub struct_size: u32,
    /// `TURBO_RUNTIME_*` flags.
    pub flags: u32,
    /// Number of explicit provider library paths.
    pub n_provider_paths: u32,
    /// Reserved; must be 0.
    pub reserved: u32,
    /// Explicit provider library paths (loaded in order, errors reported).
    pub provider_paths: *const turbo_text,
    /// Optional log sink.
    pub log: turbo_log_fn,
    /// Passed to `log`.
    pub log_user_data: *mut c_void,
}

/// Device selector for `turbo_runtime_select_device`.
#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct turbo_device_selector {
    /// `sizeof(turbo_device_selector)`.
    pub struct_size: u32,
    /// `TURBO_SELECT_AUTO` or `TURBO_SELECT_EXPLICIT`.
    pub policy: u32,
    /// Bitmask of accepted `TURBO_DEVICE_*` kinds shifted (`1 << kind`); 0 = any non-CPU for AUTO.
    pub kind_mask: u32,
    /// Ordinal within the provider (EXPLICIT only).
    pub ordinal: u32,
    /// Provider id, empty = any.
    pub provider_id: turbo_text,
    /// Vendor substring, empty = any.
    pub vendor: turbo_text,
}

/// Static device description.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct turbo_device_info {
    /// `sizeof(turbo_device_info)`.
    pub struct_size: u32,
    /// `TURBO_DEVICE_*`.
    pub kind: u32,
    /// Ordinal within the provider.
    pub ordinal: u32,
    /// PCI vendor id where known, else 0.
    pub vendor_id: u32,
    /// `TURBO_CAP_*` bits.
    pub caps: u64,
    /// Total device memory in bytes, 0 if unknown.
    pub memory_total: u64,
    /// Free device memory in bytes at query time, 0 if unknown.
    pub memory_free: u64,
    /// Human-readable device name.
    pub name: [c_char; 128],
    /// Vendor name.
    pub vendor: [c_char; 64],
    /// Provider id (for example `cuda`, `openvino`, `mock`).
    pub provider_id: [c_char; 32],
    /// Provider library version.
    pub provider_version: [c_char; 32],
    /// Vendor runtime version.
    pub runtime_version: [c_char; 64],
    /// Driver version, empty if not applicable.
    pub driver_version: [c_char; 64],
}

/// One cell of the capability matrix for (device, task, modality).
#[repr(C)]
#[derive(Clone, Copy)]
pub struct turbo_capability {
    /// `sizeof(turbo_capability)`.
    pub struct_size: u32,
    /// `TURBO_CAP_UNSUPPORTED` .. `TURBO_CAP_SUPPORTED`.
    pub status: u32,
    /// Compute dtype used (`TURBO_DTYPE_*`), 0 if not applicable.
    pub dtype: u32,
    /// Reference dtype the precision figures are measured against, 0 if none.
    pub reference_dtype: u32,
    /// Measured cosine-similarity floor against the reference; 0 if unmeasured.
    pub cosine_floor: f32,
    /// Measured maximum absolute error against the reference; 0 if unmeasured.
    pub max_abs_error: f32,
    /// 1 if results are bit-reproducible across runs.
    pub deterministic: u32,
    /// Reserved; 0.
    pub reserved: u32,
    /// Free-text qualification note (receipt id, limits).
    pub notes: [c_char; 128],
}

// ---------------------------------------------------------------------------
// Contexts and buffers
// ---------------------------------------------------------------------------

/// Context creation descriptor.
#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct turbo_context_desc {
    /// `sizeof(turbo_context_desc)`.
    pub struct_size: u32,
    /// Reserved; 0.
    pub flags: u32,
    /// Number of provider options.
    pub n_options: u32,
    /// Reserved; 0.
    pub reserved: u32,
    /// Provider options (unknown keys are rejected).
    pub options: *const turbo_kv,
    /// Extension chain for external queue import; NULL otherwise.
    pub next: *const c_void,
}

/// Maximum tensor rank.
pub const TURBO_MAX_RANK: usize = 8;

/// Buffer description. `strides` are in bytes; all-zero means packed row-major.
#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct turbo_buffer_desc {
    /// `sizeof(turbo_buffer_desc)`.
    pub struct_size: u32,
    /// `TURBO_PLACE_*`.
    pub placement: u32,
    /// `TURBO_DTYPE_*`.
    pub dtype: u32,
    /// Number of dimensions, 0..8.
    pub ndim: u32,
    /// Extent per dimension.
    pub shape: [u64; TURBO_MAX_RANK],
    /// Byte stride per dimension; all zero = packed.
    pub strides: [u64; TURBO_MAX_RANK],
    /// Total bytes; 0 = computed from shape and dtype.
    pub bytes: u64,
    /// Extension chain for imports (`turbo_native_handle`); NULL otherwise.
    pub next: *const c_void,
}

/// Native memory handle for import and export.
#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct turbo_native_handle {
    /// `sizeof(turbo_native_handle)`.
    pub struct_size: u32,
    /// `TURBO_HANDLE_*`.
    pub kind: u32,
    /// Pointer, `cl_mem`, fd, or object handle as an integer.
    pub handle: u64,
    /// Kind-specific auxiliary handle (device ordinal, context).
    pub aux: u64,
    /// Byte offset into the native allocation.
    pub offset: u64,
}

// ---------------------------------------------------------------------------
// Models
// ---------------------------------------------------------------------------

/// Model load descriptor.
#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct turbo_model_desc {
    /// `sizeof(turbo_model_desc)`.
    pub struct_size: u32,
    /// Number of provider options.
    pub n_options: u32,
    /// Provider options (unknown keys are rejected).
    pub options: *const turbo_kv,
    /// Extension chain; NULL.
    pub next: *const c_void,
}

/// What actually loaded: the frozen bundle contract plus placement.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct turbo_model_info {
    /// `sizeof(turbo_model_info)`.
    pub struct_size: u32,
    /// Primary `TURBO_TASK_*`.
    pub task: u32,
    /// `TURBO_MODEL_*`.
    pub kind: u32,
    /// `TURBO_MODALITY_*`.
    pub modality: u32,
    /// Embedding dimension, or 0.
    pub dim: u32,
    /// Number of labels (classifiers), or 0.
    pub n_labels: u32,
    /// `TURBO_POOLING_*` from the contract, or 0.
    pub pooling: u32,
    /// `TURBO_NORMALIZE_*` from the contract, or 0.
    pub normalize: u32,
    /// Maximum sequence length in tokens.
    pub max_seq: u32,
    /// Maximum batch size for sessions on this model.
    pub max_batch: u32,
    /// Compute dtype actually used.
    pub dtype_used: u32,
    /// 1 if every applicable stage runs on the device.
    pub fully_accelerated: u32,
    /// `TURBO_STAGE_*` placement per stage index.
    pub stage_placement: [u32; TURBO_STAGE_COUNT],
    /// Number of named inputs (RUN task).
    pub n_inputs: u32,
    /// Number of named outputs (RUN task).
    pub n_outputs: u32,
    /// Vocabulary size, or 0.
    pub vocab_size: u32,
    /// Model identifier from the bundle.
    pub model_id: [c_char; 128],
    /// Revision from the bundle.
    pub revision: [c_char; 64],
    /// Hex SHA-256 of the tokenizer file, or empty.
    pub tokenizer_sha256: [c_char; 72],
    /// Provider that loaded it.
    pub provider_id: [c_char; 32],
    /// Query prefix from the contract, or empty.
    pub prefix_query: [c_char; 128],
    /// Document prefix from the contract, or empty.
    pub prefix_document: [c_char; 128],
}

/// Named tensor description for RUN models. `shape` entries of -1 are dynamic.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct turbo_tensor_info {
    /// `sizeof(turbo_tensor_info)`.
    pub struct_size: u32,
    /// `TURBO_DTYPE_*`.
    pub dtype: u32,
    /// Rank.
    pub ndim: u32,
    /// Reserved; 0.
    pub reserved: u32,
    /// Extents; -1 = dynamic.
    pub shape: [i64; TURBO_MAX_RANK],
    /// Tensor name.
    pub name: [c_char; 64],
}

// ---------------------------------------------------------------------------
// Sessions
// ---------------------------------------------------------------------------

/// Session creation descriptor.
#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct turbo_session_desc {
    /// `sizeof(turbo_session_desc)`.
    pub struct_size: u32,
    /// Maximum batch; 0 = model default.
    pub max_batch: u32,
    /// Maximum sequence length; 0 = model default.
    pub max_seq: u32,
    /// Number of provider options.
    pub n_options: u32,
    /// Provider options (unknown keys are rejected).
    pub options: *const turbo_kv,
    /// Extension chain; NULL.
    pub next: *const c_void,
}

/// Per-call embedding options. Every field maps to a capability bit;
/// `TURBO_OPT_MODEL` (0) means "as the bundle contract says".
#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct turbo_embed_options {
    /// `sizeof(turbo_embed_options)`.
    pub struct_size: u32,
    /// `TURBO_TRUNCATE_*`.
    pub truncate: u32,
    /// Token budget; 0 = model.
    pub max_tokens: u32,
    /// `TURBO_PROMPT_*`.
    pub prompt_role: u32,
    /// `TURBO_NORMALIZE_*`.
    pub normalize: u32,
    /// `TURBO_POOLING_*`.
    pub pooling: u32,
    /// Output dimension (Matryoshka); 0 = model.
    pub output_dim: u32,
    /// `TURBO_OUTPUT_*`.
    pub output_dtype: u32,
}

/// Per-call rerank options.
#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct turbo_rerank_options {
    /// `sizeof(turbo_rerank_options)`.
    pub struct_size: u32,
    /// `TURBO_TRUNCATE_*`.
    pub truncate: u32,
    /// Token budget per pair; 0 = model.
    pub max_tokens: u32,
    /// Return only the best `top_n` (0 = all).
    pub top_n: u32,
    /// 1 = also produce the sorted index output.
    pub return_sorted: u32,
    /// 1 = raw logits instead of sigmoid scores. Gated by `TURBO_CAP_OPT_RAW_SCORES`.
    pub raw_scores: u32,
}

/// Per-call classification options.
#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct turbo_classify_options {
    /// `sizeof(turbo_classify_options)`.
    pub struct_size: u32,
    /// `TURBO_TRUNCATE_*`.
    pub truncate: u32,
    /// Token budget; 0 = model.
    pub max_tokens: u32,
    /// `TURBO_AGGREGATE_*` (token classification only).
    pub aggregation: u32,
    /// 1 = raw logits instead of activated scores. Gated by `TURBO_CAP_OPT_RAW_SCORES`.
    pub raw_scores: u32,
    /// Reserved; 0.
    pub reserved: u32,
}

/// Per-call RUN options: the KServe per-request parameters map.
#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct turbo_run_options {
    /// `sizeof(turbo_run_options)`.
    pub struct_size: u32,
    /// Number of parameters.
    pub n_params: u32,
    /// Parameters.
    pub params: *const turbo_kv,
}

/// Caller-prepared token batch. Row-major `[batch, seq]` i32 arrays;
/// `row_stride` is in elements (0 = `seq`). `types` may be NULL (all zero).
#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct turbo_token_batch {
    /// `sizeof(turbo_token_batch)`.
    pub struct_size: u32,
    /// Rows.
    pub batch: u32,
    /// Columns.
    pub seq: u32,
    /// Elements between row starts; 0 = `seq`.
    pub row_stride: u32,
    /// Token ids.
    pub ids: *const i32,
    /// Attention mask (0/1).
    pub mask: *const i32,
    /// Token type ids, or NULL.
    pub types: *const i32,
}

/// Session byte and allocation counters. Adapter-level only; provider
/// internals are reported separately by the provider where available.
#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct turbo_session_stats {
    /// `sizeof(turbo_session_stats)`.
    pub struct_size: u32,
    /// Reserved; 0.
    pub reserved: u32,
    /// Completed runs.
    pub runs: u64,
    /// Host heap allocations made by the adapter on the run path since
    /// warmup, or `UINT64_MAX` when the adapter does not count them.
    pub host_allocs: u64,
    /// Explicit host-to-device bytes.
    pub h2d_bytes: u64,
    /// Explicit device-to-host bytes.
    pub d2h_bytes: u64,
    /// Bytes of bound input storage.
    pub input_bytes: u64,
    /// Bytes of bound output storage.
    pub output_bytes: u64,
    /// Provider-internal allocations on the run path, or `UINT64_MAX` if unknown.
    pub provider_allocs: u64,
}

// ---------------------------------------------------------------------------
// Results
// ---------------------------------------------------------------------------

/// Result summary. `n_outputs` is 1 for embeddings and scores; classifiers
/// and RUN models may have several.
#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct turbo_result_info {
    /// `sizeof(turbo_result_info)`.
    pub struct_size: u32,
    /// Number of output tensors.
    pub n_outputs: u32,
    /// Rows in output 0.
    pub batch: u32,
    /// Columns in output 0 (dimension, labels, or 1 for scores).
    pub dim: u32,
    /// `TURBO_DTYPE_*` of output 0.
    pub dtype: u32,
    /// `TURBO_PLACE_*` of output 0.
    pub placement: u32,
    /// Bytes in output 0.
    pub bytes: u64,
}

/// One aggregated span from token classification.
#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct turbo_span {
    /// Byte offset of the span start in the original input row.
    pub byte_start: u64,
    /// Byte offset one past the span end.
    pub byte_end: u64,
    /// Input row.
    pub row: u32,
    /// Label index into the bundle's label list.
    pub label: u32,
    /// Score.
    pub score: f32,
    /// Reserved; 0.
    pub reserved: u32,
}

// ---------------------------------------------------------------------------
// Generation
// ---------------------------------------------------------------------------

/// One chat message for template application.
#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct turbo_message {
    /// Role (`system`, `user`, `assistant`, `tool`).
    pub role: turbo_text,
    /// Content.
    pub content: turbo_text,
}

/// Logit bias entry.
#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct turbo_logit_bias {
    /// Token id.
    pub token: i32,
    /// Additive bias.
    pub bias: f32,
}

/// Generation descriptor. Capability-gated fields are marked; an unsupported
/// non-zero field fails with `TURBO_E_UNSUPPORTED_OPTION` naming it.
#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct turbo_generate_desc {
    /// `sizeof(turbo_generate_desc)`.
    pub struct_size: u32,
    /// Maximum new tokens; 0 = model default.
    pub max_new_tokens: u32,
    /// Minimum new tokens before EOS is allowed. Gated by `TURBO_CAP_OPT_GEN_MIN_TOKENS`.
    pub min_new_tokens: u32,
    /// Sequences to generate; 0 or 1 = one. Gated by `TURBO_CAP_OPT_GEN_N`.
    pub n_sequences: u32,
    /// Sampling temperature; 0 = greedy. Gated by `TURBO_CAP_OPT_GEN_SAMPLING`.
    pub temperature: f32,
    /// Top-k; 0 = off. Gated by `TURBO_CAP_OPT_GEN_SAMPLING`.
    pub top_k: u32,
    /// Top-p; 0 or 1 = off. Gated by `TURBO_CAP_OPT_GEN_SAMPLING`.
    pub top_p: f32,
    /// Min-p; 0 = off. Gated by `TURBO_CAP_OPT_GEN_SAMPLING`.
    pub min_p: f32,
    /// Repeat penalty; 0 or 1 = off. Gated by `TURBO_CAP_OPT_GEN_PENALTIES`.
    pub repeat_penalty: f32,
    /// Presence penalty; 0 = off. Gated.
    pub presence_penalty: f32,
    /// Frequency penalty; 0 = off. Gated.
    pub frequency_penalty: f32,
    /// 1 = use `seed`. Gated by `TURBO_CAP_OPT_GEN_SEED`.
    pub has_seed: u32,
    /// Random seed.
    pub seed: u64,
    /// Number of stop strings. Gated by `TURBO_CAP_OPT_GEN_STOP_STRINGS`.
    /// The stream ends with `TURBO_FINISH_STOP` when the generated text
    /// would contain one; the text delivered ends before the match, and the
    /// matched string and whatever followed it in the same piece are never
    /// delivered. Text that could still complete a stop string is held back
    /// until it cannot, so a match spanning pieces is caught too.
    pub n_stop: u32,
    /// Number of stop token ids. Gated by `TURBO_CAP_OPT_GEN_STOP_TOKENS`.
    pub n_stop_tokens: u32,
    /// Stop strings.
    pub stop: *const turbo_text,
    /// Stop token ids.
    pub stop_tokens: *const i32,
    /// Number of logit bias entries. Gated by `TURBO_CAP_OPT_GEN_LOGIT_BIAS`.
    pub n_logit_bias: u32,
    /// Top logprobs per token to return; 0 = none. Gated by `TURBO_CAP_OPT_GEN_LOGPROBS`.
    pub logprobs: u32,
    /// Logit bias entries.
    pub logit_bias: *const turbo_logit_bias,
    /// `TURBO_STRUCTURED_*`. Gated by `TURBO_CAP_OPT_GEN_STRUCTURED`.
    pub structured_kind: u32,
    /// 1 = include the prompt in the output text. Gated by `TURBO_CAP_OPT_GEN_ECHO`.
    pub echo: u32,
    /// Schema or grammar text.
    pub structured: turbo_text,
    /// Number of tool definitions (JSON). Gated by `TURBO_CAP_OPT_GEN_TOOLS`.
    pub n_tools: u32,
    /// Number of provider options.
    pub n_options: u32,
    /// Tool definitions.
    pub tools: *const turbo_text,
    /// Provider options (unknown keys are rejected).
    pub options: *const turbo_kv,
}

/// One step of generation. Pointers are valid until the next `step`, `cancel`, or `release`.
#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct turbo_generation_chunk {
    /// `sizeof(turbo_generation_chunk)`.
    pub struct_size: u32,
    /// Sequence index (0 unless `n_sequences > 1`).
    pub sequence: u32,
    /// Number of new token ids in this chunk.
    pub n_tokens: u32,
    /// Number of logprob entries (`n_tokens * logprobs`).
    pub n_logprobs: u32,
    /// New token ids.
    pub tokens: *const i32,
    /// Decoded text for the new tokens (may be empty mid-codepoint).
    pub text: turbo_text,
    /// Logprobs, or NULL.
    pub logprobs: *const f32,
    /// 1 when this sequence is finished.
    pub done: u32,
    /// `TURBO_FINISH_*` when `done`.
    pub finish_reason: u32,
    /// Prompt tokens consumed (reported on the first chunk).
    pub prompt_tokens: u32,
    /// Total generated tokens so far in this sequence.
    pub generated_tokens: u32,
}

/// Push-generation callback. Return `TURBO_STREAM_CONTINUE` or `TURBO_STREAM_STOP`.
pub type turbo_stream_fn =
    Option<unsafe extern "C" fn(user_data: *mut c_void, chunk: *const turbo_generation_chunk) -> u32>;

// ---------------------------------------------------------------------------
// Tokenizer and chunker
// ---------------------------------------------------------------------------

/// Tokenizer encode options.
#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct turbo_encode_options {
    /// `sizeof(turbo_encode_options)`.
    pub struct_size: u32,
    /// 1 = add special tokens (default when the whole struct is NULL).
    pub add_special_tokens: u32,
    /// `TURBO_TRUNCATE_*`.
    pub truncate: u32,
    /// Token budget including specials; 0 = model max.
    pub max_tokens: u32,
    /// Pad every row to this many tokens; 0 = no padding.
    pub pad_to: u32,
    /// `TURBO_PROMPT_*`.
    pub prompt_role: u32,
}

/// Static facts about a tokenizer.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct turbo_tokenizer_info {
    /// `sizeof(turbo_tokenizer_info)`.
    pub struct_size: u32,
    /// Vocabulary size including added tokens.
    pub vocab_size: u32,
    /// Bundle `max_seq`.
    pub max_seq: u32,
    /// Special tokens added to one sequence.
    pub specials_per_sequence: u32,
    /// Pad id, or -1.
    pub pad_id: i32,
    /// Beginning-of-sequence / `[CLS]` id, or -1.
    pub bos_id: i32,
    /// End-of-sequence / `[SEP]` id, or -1.
    pub eos_id: i32,
    /// Unknown-token id, or -1.
    pub unk_id: i32,
    /// Tokenizer kind (`wordpiece`, `bpe`, `unigram`, ...).
    pub kind: [c_char; 32],
    /// Hex SHA-256 of the tokenizer file, or empty.
    pub sha256: [c_char; 72],
}

/// Chunk planner configuration.
#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct turbo_chunk_desc {
    /// `sizeof(turbo_chunk_desc)`.
    pub struct_size: u32,
    /// Model sequence capacity.
    pub max_tokens: u32,
    /// Tokens held back for specials and prefixes.
    pub reserved_tokens: u32,
    /// Upper bound on shared tokens between consecutive chunks of one paragraph.
    pub overlap_tokens: u32,
}

/// One planned chunk: half-open byte range into the original text.
#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct turbo_chunk {
    /// Byte offset of the chunk start.
    pub byte_start: u64,
    /// Byte offset one past the end.
    pub byte_end: u64,
    /// Paragraph index.
    pub paragraph: u32,
    /// Content tokens in the chunk under the supplied tokenizer.
    pub n_tokens: u32,
}

// ---------------------------------------------------------------------------
// Provider plugin entry point (types only; the vtable lives in turbo_provider.h)
// ---------------------------------------------------------------------------

/// Name of the symbol a provider library exports.
pub const TURBO_PROVIDER_ENTRY_SYMBOL: &str = "turbo_provider_get";

#[cfg(test)]
mod tests {
    use super::*;
    use core::mem::size_of;

    #[test]
    fn error_is_fixed_size() {
        assert_eq!(size_of::<turbo_error>(), 4 + 4 + 4 + TURBO_ERROR_MESSAGE_LEN);
    }

    #[test]
    fn text_is_two_words() {
        assert_eq!(size_of::<turbo_text>(), 16);
    }

    #[test]
    fn status_grades_do_not_overlap() {
        for (code, grade) in [
            (TURBO_E_INVALID_ARGUMENT, 0x100),
            (TURBO_E_UNSUPPORTED, 0x200),
            (TURBO_E_OUT_OF_MEMORY, 0x300),
            (TURBO_E_DEVICE_NOT_FOUND, 0x400),
            (TURBO_E_BUNDLE_NOT_FOUND, 0x500),
            (TURBO_E_INTERNAL, 0x600),
        ] {
            assert_eq!(code & 0xF00, grade);
        }
    }
}
