#!/usr/bin/env python3
"""Regenerate crates/turbo-abi/src/versioned.rs from the ABI struct field lists."""
import re, subprocess, sys, pathlib
root = pathlib.Path(__file__).resolve().parent.parent
structs = []
for f in ['crates/turbo-abi/src/lib.rs', 'crates/turbo-abi/src/provider.rs']:
    s = (root / f).read_text()
    for m in re.finditer(r'pub struct (turbo_\w+) \{(.*?)\n\}', s, re.S):
        name, body = m.group(1), m.group(2)
        fields = re.findall(r'^\s*pub (\w+):', body, re.M)
        if fields and fields[0] == 'struct_size':
            structs.append((name, fields))
out = ['//! Known `struct_size` values per ABI struct.',
'//!',
'//! A caller declares the layout it was compiled against through',
'//! `struct_size`. The library accepts a size only when it is the end of a',
'//! field the struct has ever had (fields are only ever appended), so an',
'//! accepted prefix never ends inside a field. Not every accepted prefix is',
'//! a layout that shipped: a count field can precede the pointer it counts,',
'//! and a prefix that ends between them is accepted. That is safe because',
'//! the bytes beyond `struct_size` are never read: the prefix is copied into',
'//! a zeroed full struct, the pointer reads NULL, and every consumer',
'//! refuses NULL with a non-zero count (`abi_convert.rs`). That is the',
'//! invariant these tables rely on.',
'//! Everything else is `TURBO_E_INVALID_STRUCT_SIZE`.',
'//!',
'//! Generated from the field lists of `lib.rs` and `provider.rs` by',
'//! `scripts/gen-versioned.py`; regenerate when a struct changes.',
'',
'use core::mem::{offset_of, size_of};',
'',
'/// An ABI struct that starts with `uint32_t struct_size`.',
'pub trait Versioned {',
'    /// Every accepted `struct_size`, ascending, ending with the current size.',
"    const SIZES: &'static [usize];",
'',
'    /// True when `size` is a layout this library understands.',
'    fn size_is_known(size: u32) -> bool {',
'        Self::SIZES.contains(&(size as usize))',
'    }',
'}',
'']
for name, fields in structs:
    ends = [f'offset_of!(super::{name}, {f})' for f in fields[2:]] + [f'size_of::<super::{name}>()']
    out.append(f'impl Versioned for super::{name} {{')
    out.append("    const SIZES: &'static [usize] = &[")
    out += [f'        {e},' for e in ends]
    out.append('    ];')
    out.append('}')
    out.append('')
target = root / 'crates/turbo-abi/src/versioned.rs'
# Format with the repository's rustfmt settings so the committed file is
# byte-identical to what `cargo fmt` would produce.
tmp = target.with_name('versioned.gen.rs')
tmp.write_text('\n'.join(out) + '\n')
subprocess.run(['rustfmt', '--edition', '2021', str(tmp)], check=True)
text = tmp.read_text()
tmp.unlink()

# The same tables for the C++ providers (OpenVINO, Hailo): one overload per
# struct, selected by a null pointer of the struct type, so
# `check_size<T>` in turbo_provider_common.hpp applies exactly the rule the
# Rust core applies.
hpp = ['// SPDX-License-Identifier: Apache-2.0',
'//',
'// Known `struct_size` values per ABI struct, for the C++ providers. The',
'// same rule as crates/turbo-abi/src/versioned.rs: a size is accepted only',
'// when it is the end of a field the struct has ever had (fields are only',
'// appended), so an accepted prefix never ends inside a field. A prefix',
'// that ends before a pointer whose count precedes it is safe because the',
'// caller-owned bytes beyond `struct_size` are never read: the provider',
'// copies the declared prefix into a zeroed full struct, so the pointer',
'// reads NULL and every consumer refuses NULL with a non-zero count.',
'//',
'// Generated by scripts/gen-versioned.py; do not edit.',
'#pragma once',
'',
'#include "turbo/turbo_provider.h"',
'#include "turbo/turbo_types.h"',
'',
'#include <cstddef>',
'#include <cstdint>',
'',
'namespace turbo_versioned {',
'']
for name, fields in structs:
    ends = [f'offsetof({name}, {f})' for f in fields[2:]] + [f'sizeof({name})']
    hpp.append(f'inline bool size_is_known(const {name} *, uint32_t size) {{')
    hpp.append('    static const size_t sizes[] = {')
    hpp += [f'        {e},' for e in ends]
    hpp.append('    };')
    hpp.append('    for (size_t s : sizes) {')
    hpp.append('        if (s == size) {')
    hpp.append('            return true;')
    hpp.append('        }')
    hpp.append('    }')
    hpp.append('    return false;')
    hpp.append('}')
    hpp.append('')
hpp.append('} // namespace turbo_versioned')
hpp_text = '\n'.join(hpp) + '\n'
hpp_target = root / 'native/provider_common/turbo_versioned.hpp'

if '--check' in sys.argv:
    if target.read_text() != text:
        sys.exit('versioned.rs is stale; run scripts/gen-versioned.py')
    if not hpp_target.exists() or hpp_target.read_text() != hpp_text:
        sys.exit('native/provider_common/turbo_versioned.hpp is stale; run scripts/gen-versioned.py')
    sys.exit(0)
target.write_text(text)
hpp_target.write_text(hpp_text)
