#!/usr/bin/env python3
"""Generate the Unicode data the core's native WordPiece tokenizer needs.

Writes crates/turbo-core/src/unicode_data.rs: the full canonical (NFD)
decomposition of every code point that has one, the canonical combining
class of every code point with a non-zero class, and the general
categories the BERT normalizer tests (nonspacing marks, control, format,
punctuation, space separators), from Python's unicodedata.

Usage: scripts/gen-unicode-nfd.py [--check]
"""
import sys
import unicodedata
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / "crates" / "turbo-core" / "src" / "unicode_data.rs"


def nfd(cp: int) -> list[int]:
    return [ord(c) for c in unicodedata.normalize("NFD", chr(cp))]


def ranges(pred) -> list[tuple[int, int]]:
    out = []
    start = None
    prev = None
    for cp in range(0x110000):
        if pred(cp):
            if start is None:
                start = cp
            prev = cp
        elif start is not None:
            out.append((start, prev))
            start = None
    if start is not None:
        out.append((start, prev))
    return out


def main() -> int:
    decomp = []
    for cp in range(0x110000):
        if 0xD800 <= cp <= 0xDFFF:
            continue
        d = nfd(cp)
        if d != [cp]:
            decomp.append((cp, d))
    ccc = [(cp, unicodedata.combining(chr(cp))) for cp in range(0x110000) if not 0xD800 <= cp <= 0xDFFF and unicodedata.combining(chr(cp)) != 0]
    cat = lambda cp: unicodedata.category(chr(cp)) if not 0xD800 <= cp <= 0xDFFF else "Cs"
    mn = ranges(lambda cp: cat(cp) == "Mn")
    control = ranges(lambda cp: cat(cp) in ("Cc", "Cf"))
    punct = ranges(lambda cp: cat(cp).startswith("P"))
    space = ranges(lambda cp: cat(cp) == "Zs")
    lines = [
        "// Generated by scripts/gen-unicode-nfd.py from Python's unicodedata",
        f"// (Unicode {unicodedata.unidata_version}). Do not edit by hand.",
        "//",
        "// Canonical decompositions (full NFD), canonical combining classes and",
        "// the general categories the BERT normalizer tests.",
        "",
        "/// `(code point, NFD sequence)` for every code point whose NFD form differs from itself, sorted by code point.",
        "pub static NFD: &[(u32, &[u32])] = &[",
    ]
    for cp, d in decomp:
        lines.append(f"    (0x{cp:X}, &[{', '.join(f'0x{x:X}' for x in d)}]),")
    lines.append("];")
    lines.append("")
    lines.append("/// `(code point, canonical combining class)` for every non-zero class, sorted by code point.")
    lines.append("pub static COMBINING_CLASS: &[(u32, u8)] = &[")
    for cp, c in ccc:
        lines.append(f"    (0x{cp:X}, {c}),")
    lines.append("];")
    for name, doc, rs in (
        ("MARK_NONSPACING", "General category Mn", mn),
        ("CONTROL", "General categories Cc and Cf", control),
        ("PUNCTUATION", "General categories P*", punct),
        ("SPACE_SEPARATOR", "General category Zs", space),
    ):
        lines.append("")
        lines.append(f"/// {doc}, as inclusive `(first, last)` ranges sorted by `first`.")
        lines.append(f"pub static {name}: &[(u32, u32)] = &[")
        lines.append("    " + " ".join(f"(0x{a:X}, 0x{b:X})," for a, b in rs))
        lines.append("];")
    text = "\n".join(lines) + "\n"
    if "--check" in sys.argv:
        if OUT.read_text() != text:
            print(f"{OUT} is out of date; run scripts/gen-unicode-nfd.py", file=sys.stderr)
            return 1
        print(f"{OUT} is up to date")
        return 0
    OUT.write_text(text)
    print(f"wrote {OUT} ({len(decomp)} decompositions, {len(ccc)} combining classes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
