#!/usr/bin/env python3
"""Generate the native BERT category predicates from unicode_categories 0.1.1."""

from __future__ import annotations

import argparse
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "third_party/unicode_categories/tables.rs"
OUTPUT = ROOT / "native/wordpiece/bert_unicode_categories.hpp"
PUNCTUATION = (
    "PUNCTUATION_CONNECTOR",
    "PUNCTUATION_DASH",
    "PUNCTUATION_CLOSE",
    "PUNCTUATION_FINAL_QUOTE",
    "PUNCTUATION_INITIAL_QUOTE",
    "PUNCTUATION_OTHER",
    "PUNCTUATION_OPEN",
)
PRIVATE_USE = ((0xE000, 0xF8FF), (0xF0000, 0xFFFFD), (0x100000, 0x10FFFD))


def read_tables(source: Path) -> dict[str, set[int]]:
    text = source.read_text(encoding="utf-8")
    tables: dict[str, set[int]] = {}
    for name, body in re.findall(
        r"pub static ([A-Z_]+)\s*:.*?=\s*&\[(.*?)\];", text, re.DOTALL
    ):
        tables[name] = {int(value, 16) for value in re.findall(r"\\u\{([0-9A-Fa-f]+)\}", body)}
    required = {"OTHER_CONTROL", "OTHER_FORMAT", "OTHER_PRIVATE_USE", "MARK_NONSPACING", *PUNCTUATION}
    missing = required - tables.keys()
    if missing:
        raise ValueError(f"missing source tables: {sorted(missing)}")
    return tables


def expand_ranges(ranges: list[tuple[int, int]]) -> set[int]:
    return {value for first, last in ranges for value in range(first, last + 1)}


def compact(values: set[int]) -> list[tuple[int, int]]:
    ordered = sorted(values)
    if not ordered:
        return []
    ranges: list[tuple[int, int]] = []
    first = last = ordered[0]
    for value in ordered[1:]:
        if value == last + 1:
            last = value
        else:
            ranges.append((first, last))
            first = last = value
    ranges.append((first, last))
    assert all(a <= b and (i == 0 or ranges[i - 1][1] + 1 < a) for i, (a, b) in enumerate(ranges))
    assert expand_ranges(ranges) == values
    return ranges


def in_ranges(codepoint: int, ranges: list[tuple[int, int]]) -> bool:
    lo, hi = 0, len(ranges)
    while lo < hi:
        mid = lo + (hi - lo) // 2
        first, last = ranges[mid]
        if codepoint < first:
            hi = mid
        elif codepoint > last:
            lo = mid + 1
        else:
            return True
    return False


def verify_exhaustively(values: set[int], ranges: list[tuple[int, int]]) -> None:
    for codepoint in range(0x110000):
        assert in_ranges(codepoint, ranges) == (codepoint in values)


def emit_array(name: str, ranges: list[tuple[int, int]]) -> str:
    rows = "\n".join(f"    {{0x{first:X}u, 0x{last:X}u}}," for first, last in ranges)
    return f"inline constexpr Range {name}[] = {{\n{rows}\n}};"


def generate(source: Path) -> str:
    tables = read_tables(source)
    other = tables["OTHER_CONTROL"] | tables["OTHER_FORMAT"] | tables["OTHER_PRIVATE_USE"]
    other |= expand_ranges(list(PRIVATE_USE))
    mark = tables["MARK_NONSPACING"]
    punctuation = set().union(*(tables[name] for name in PUNCTUATION))
    source_categories = {"kOther": other, "kMarkNonspacing": mark, "kPunctuation": punctuation}
    categories = {name: compact(values) for name, values in source_categories.items()}
    for name, values in source_categories.items():
        verify_exhaustively(values, categories[name])
    return """// Generated by scripts/generate-bert-unicode-categories.py.
// Source: unicode_categories 0.1.1 src/tables.rs (vendored in third_party).
// Do not edit manually.
#pragma once

#include <cstddef>
#include <cstdint>

namespace wordpiece_unicode {
struct Range {
    uint32_t first;
    uint32_t last;
};

template <std::size_t N>
constexpr bool in_ranges(uint32_t codepoint, const Range (&ranges)[N]) {
    std::size_t lo = 0;
    std::size_t hi = N;
    while (lo < hi) {
        const std::size_t mid = lo + (hi - lo) / 2;
        if (codepoint < ranges[mid].first) {
            hi = mid;
        } else if (codepoint > ranges[mid].last) {
            lo = mid + 1;
        } else {
            return true;
        }
    }
    return false;
}

""" + "\n\n".join(emit_array(name, ranges) for name, ranges in categories.items()) + """

constexpr bool is_other(uint32_t codepoint) {
    return in_ranges(codepoint, kOther);
}

constexpr bool is_mark_nonspacing(uint32_t codepoint) {
    return in_ranges(codepoint, kMarkNonspacing);
}

constexpr bool is_punctuation(uint32_t codepoint) {
    return in_ranges(codepoint, kPunctuation);
}
} // namespace wordpiece_unicode
"""


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source", type=Path, default=SOURCE)
    parser.add_argument("--output", type=Path, default=OUTPUT)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    generated = generate(args.source)
    if args.check:
        if not args.output.exists() or args.output.read_text(encoding="utf-8") != generated:
            raise SystemExit(f"generated output differs: {args.output}")
    else:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(generated, encoding="utf-8")


if __name__ == "__main__":
    main()
