#!/usr/bin/env bash
# Prepare a local llama-cpp-sys-2 checkout that can compile GGML_SYCL.
#
# crates.io's llama-cpp-sys-2 packages llama.cpp *without* ggml-sycl/**, so
# GGML_SYCL=ON fails at cmake unless those sources are injected. This script
# downloads the crate, pulls ggml-sycl from the matching llama.cpp commit,
# and writes .cargo/config.toml so cargo uses the patched crate. No python3.
#
# Pins (llama-cpp-2 0.1.156):
#   crate git     63e549708237b16b39018288582655539e0a9d5b
#   llama.cpp     e79e4bf660e19f2ad851e06c6913f7a8c5852621
#
# Idempotent. Run once per host (or after bumping llama-cpp-2).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
VENDOR="$ROOT/vendor/llama-cpp-sys-2"
CARGO_CFG="$ROOT/.cargo/config.toml"
VERSION="${LLAMA_CPP_SYS_VERSION:-0.1.156}"
# Submodule SHA of llama.cpp inside llama-cpp-sys-2 0.1.156
# (utilityai/llama-cpp-rs @ 63e54970).
LLAMA_CPP_COMMIT="${LLAMA_CPP_COMMIT:-e79e4bf660e19f2ad851e06c6913f7a8c5852621}"
USER_AGENT="inferstream-setup-llamacpp-sycl/1.0"
CRATE_URL="https://static.crates.io/crates/llama-cpp-sys-2/llama-cpp-sys-2-${VERSION}.crate"
SYCL_TARBALL_URL="https://codeload.github.com/ggml-org/llama.cpp/tar.gz/${LLAMA_CPP_COMMIT}"

command -v curl >/dev/null || { echo "error: curl required" >&2; exit 1; }

if [ -f "$VENDOR/llama.cpp/ggml/src/ggml-sycl/CMakeLists.txt" ] \
    && [ -f "$CARGO_CFG" ] && grep -q 'llama-cpp-sys-2' "$CARGO_CFG"; then
    echo "ok: vendor already has ggml-sycl ($VENDOR)"
    exit 0
fi

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

echo "--- downloading llama-cpp-sys-2 $VERSION ---"
curl -fL --retry 5 -A "$USER_AGENT" -o "$TMP/crate.tgz" "$CRATE_URL"
mkdir -p "$TMP/crate"
tar -xzf "$TMP/crate.tgz" -C "$TMP/crate"
SRC="$(find "$TMP/crate" -maxdepth 1 -type d -name "llama-cpp-sys-2-${VERSION}" | head -n1)"
[ -n "$SRC" ] || SRC="$(find "$TMP/crate" -maxdepth 1 -type d -name 'llama-cpp-sys-2-*' | head -n1)"
if [ -z "$SRC" ] || [ ! -d "$SRC/llama.cpp" ]; then
    echo "error: unexpected crate layout" >&2
    ls -la "$TMP/crate" >&2
    exit 1
fi

echo "--- installing vendor copy -> $VENDOR ---"
rm -rf "$VENDOR"
mkdir -p "$(dirname "$VENDOR")"
cp -a "$SRC" "$VENDOR"
chmod -R u+w "$VENDOR"

SYCL_DEST="$VENDOR/llama.cpp/ggml/src/ggml-sycl"
if [ ! -f "$SYCL_DEST/CMakeLists.txt" ]; then
    echo "--- downloading ggml-sycl from ggml-org/llama.cpp@${LLAMA_CPP_COMMIT:0:12} ---"
    curl -fL --retry 5 -A "$USER_AGENT" -o "$TMP/llama.cpp.tgz" "$SYCL_TARBALL_URL"
    mkdir -p "$TMP/llama"
    tar -xzf "$TMP/llama.cpp.tgz" -C "$TMP/llama"
    FOUND="$(find "$TMP/llama" -type d -name ggml-sycl | head -n1)"
    if [ -z "$FOUND" ] || [ ! -f "$FOUND/CMakeLists.txt" ]; then
        echo "error: ggml-sycl/CMakeLists.txt missing in llama.cpp@$LLAMA_CPP_COMMIT" >&2
        exit 1
    fi
    rm -rf "$SYCL_DEST"
    cp -a "$FOUND" "$SYCL_DEST"
fi

if ! grep -q 'ggml-sycl' "$VENDOR/Cargo.toml"; then
    echo "--- patching vendor Cargo.toml include ---"
    if grep -q 'ggml-hip' "$VENDOR/Cargo.toml"; then
        sed -i '/ggml-hip/a\ "/llama.cpp/ggml/src/ggml-sycl/**/*",' "$VENDOR/Cargo.toml"
    else
        echo "error: unexpected llama-cpp-sys-2 Cargo.toml layout" >&2
        exit 1
    fi
fi

mkdir -p "$ROOT/.cargo"
if [ ! -f "$CARGO_CFG" ] || ! grep -q 'llama-cpp-sys-2' "$CARGO_CFG"; then
    echo "--- writing $CARGO_CFG ---"
    {
        echo
        echo "# Generated by scripts/setup-llamacpp-sycl.sh — crates.io omits ggml-sycl."
        echo "[patch.crates-io]"
        echo 'llama-cpp-sys-2 = { path = "vendor/llama-cpp-sys-2" }'
    } >> "$CARGO_CFG"
fi

echo
echo "ok: SYCL-capable llama-cpp-sys-2 at $VENDOR"
echo "    ggml-sycl from llama.cpp $LLAMA_CPP_COMMIT"
echo "build with (icpx as rustc linker; no python3):"
echo "  scripts/build-intel.sh"
