// Generated by jextract

package ai.pipestream.turbo.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct turbo_chunk_desc {
 *     uint32_t struct_size;
 *     uint32_t max_tokens;
 *     uint32_t reserved_tokens;
 *     uint32_t overlap_tokens;
 * }
 * }
 */
public class turbo_chunk_desc {

    turbo_chunk_desc() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        TurboNative.C_INT.withName("struct_size"),
        TurboNative.C_INT.withName("max_tokens"),
        TurboNative.C_INT.withName("reserved_tokens"),
        TurboNative.C_INT.withName("overlap_tokens")
    ).withName("turbo_chunk_desc");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt struct_size$LAYOUT = (OfInt)$LAYOUT.select(groupElement("struct_size"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t struct_size
     * }
     */
    public static final OfInt struct_size$layout() {
        return struct_size$LAYOUT;
    }

    private static final long struct_size$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t struct_size
     * }
     */
    public static final long struct_size$offset() {
        return struct_size$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t struct_size
     * }
     */
    public static int struct_size(MemorySegment struct) {
        return struct.get(struct_size$LAYOUT, struct_size$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t struct_size
     * }
     */
    public static void struct_size(MemorySegment struct, int fieldValue) {
        struct.set(struct_size$LAYOUT, struct_size$OFFSET, fieldValue);
    }

    private static final OfInt max_tokens$LAYOUT = (OfInt)$LAYOUT.select(groupElement("max_tokens"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t max_tokens
     * }
     */
    public static final OfInt max_tokens$layout() {
        return max_tokens$LAYOUT;
    }

    private static final long max_tokens$OFFSET = 4;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t max_tokens
     * }
     */
    public static final long max_tokens$offset() {
        return max_tokens$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t max_tokens
     * }
     */
    public static int max_tokens(MemorySegment struct) {
        return struct.get(max_tokens$LAYOUT, max_tokens$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t max_tokens
     * }
     */
    public static void max_tokens(MemorySegment struct, int fieldValue) {
        struct.set(max_tokens$LAYOUT, max_tokens$OFFSET, fieldValue);
    }

    private static final OfInt reserved_tokens$LAYOUT = (OfInt)$LAYOUT.select(groupElement("reserved_tokens"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t reserved_tokens
     * }
     */
    public static final OfInt reserved_tokens$layout() {
        return reserved_tokens$LAYOUT;
    }

    private static final long reserved_tokens$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t reserved_tokens
     * }
     */
    public static final long reserved_tokens$offset() {
        return reserved_tokens$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t reserved_tokens
     * }
     */
    public static int reserved_tokens(MemorySegment struct) {
        return struct.get(reserved_tokens$LAYOUT, reserved_tokens$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t reserved_tokens
     * }
     */
    public static void reserved_tokens(MemorySegment struct, int fieldValue) {
        struct.set(reserved_tokens$LAYOUT, reserved_tokens$OFFSET, fieldValue);
    }

    private static final OfInt overlap_tokens$LAYOUT = (OfInt)$LAYOUT.select(groupElement("overlap_tokens"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t overlap_tokens
     * }
     */
    public static final OfInt overlap_tokens$layout() {
        return overlap_tokens$LAYOUT;
    }

    private static final long overlap_tokens$OFFSET = 12;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t overlap_tokens
     * }
     */
    public static final long overlap_tokens$offset() {
        return overlap_tokens$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t overlap_tokens
     * }
     */
    public static int overlap_tokens(MemorySegment struct) {
        return struct.get(overlap_tokens$LAYOUT, overlap_tokens$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t overlap_tokens
     * }
     */
    public static void overlap_tokens(MemorySegment struct, int fieldValue) {
        struct.set(overlap_tokens$LAYOUT, overlap_tokens$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

