// Generated by jextract

package ai.pipestream.turbo.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct turbo_device_info {
 *     uint32_t struct_size;
 *     uint32_t kind;
 *     uint32_t ordinal;
 *     uint32_t vendor_id;
 *     uint64_t caps;
 *     uint64_t memory_total;
 *     uint64_t memory_free;
 *     char name[128];
 *     char vendor[64];
 *     char provider_id[32];
 *     char provider_version[32];
 *     char runtime_version[64];
 *     char driver_version[64];
 * }
 * }
 */
public class turbo_device_info {

    turbo_device_info() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        TurboNative.C_INT.withName("struct_size"),
        TurboNative.C_INT.withName("kind"),
        TurboNative.C_INT.withName("ordinal"),
        TurboNative.C_INT.withName("vendor_id"),
        TurboNative.C_LONG.withName("caps"),
        TurboNative.C_LONG.withName("memory_total"),
        TurboNative.C_LONG.withName("memory_free"),
        MemoryLayout.sequenceLayout(128, TurboNative.C_CHAR).withName("name"),
        MemoryLayout.sequenceLayout(64, TurboNative.C_CHAR).withName("vendor"),
        MemoryLayout.sequenceLayout(32, TurboNative.C_CHAR).withName("provider_id"),
        MemoryLayout.sequenceLayout(32, TurboNative.C_CHAR).withName("provider_version"),
        MemoryLayout.sequenceLayout(64, TurboNative.C_CHAR).withName("runtime_version"),
        MemoryLayout.sequenceLayout(64, TurboNative.C_CHAR).withName("driver_version")
    ).withName("turbo_device_info");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt struct_size$LAYOUT = (OfInt)$LAYOUT.select(groupElement("struct_size"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t struct_size
     * }
     */
    public static final OfInt struct_size$layout() {
        return struct_size$LAYOUT;
    }

    private static final long struct_size$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t struct_size
     * }
     */
    public static final long struct_size$offset() {
        return struct_size$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t struct_size
     * }
     */
    public static int struct_size(MemorySegment struct) {
        return struct.get(struct_size$LAYOUT, struct_size$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t struct_size
     * }
     */
    public static void struct_size(MemorySegment struct, int fieldValue) {
        struct.set(struct_size$LAYOUT, struct_size$OFFSET, fieldValue);
    }

    private static final OfInt kind$LAYOUT = (OfInt)$LAYOUT.select(groupElement("kind"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t kind
     * }
     */
    public static final OfInt kind$layout() {
        return kind$LAYOUT;
    }

    private static final long kind$OFFSET = 4;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t kind
     * }
     */
    public static final long kind$offset() {
        return kind$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t kind
     * }
     */
    public static int kind(MemorySegment struct) {
        return struct.get(kind$LAYOUT, kind$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t kind
     * }
     */
    public static void kind(MemorySegment struct, int fieldValue) {
        struct.set(kind$LAYOUT, kind$OFFSET, fieldValue);
    }

    private static final OfInt ordinal$LAYOUT = (OfInt)$LAYOUT.select(groupElement("ordinal"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t ordinal
     * }
     */
    public static final OfInt ordinal$layout() {
        return ordinal$LAYOUT;
    }

    private static final long ordinal$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t ordinal
     * }
     */
    public static final long ordinal$offset() {
        return ordinal$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t ordinal
     * }
     */
    public static int ordinal(MemorySegment struct) {
        return struct.get(ordinal$LAYOUT, ordinal$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t ordinal
     * }
     */
    public static void ordinal(MemorySegment struct, int fieldValue) {
        struct.set(ordinal$LAYOUT, ordinal$OFFSET, fieldValue);
    }

    private static final OfInt vendor_id$LAYOUT = (OfInt)$LAYOUT.select(groupElement("vendor_id"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t vendor_id
     * }
     */
    public static final OfInt vendor_id$layout() {
        return vendor_id$LAYOUT;
    }

    private static final long vendor_id$OFFSET = 12;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t vendor_id
     * }
     */
    public static final long vendor_id$offset() {
        return vendor_id$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t vendor_id
     * }
     */
    public static int vendor_id(MemorySegment struct) {
        return struct.get(vendor_id$LAYOUT, vendor_id$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t vendor_id
     * }
     */
    public static void vendor_id(MemorySegment struct, int fieldValue) {
        struct.set(vendor_id$LAYOUT, vendor_id$OFFSET, fieldValue);
    }

    private static final OfLong caps$LAYOUT = (OfLong)$LAYOUT.select(groupElement("caps"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint64_t caps
     * }
     */
    public static final OfLong caps$layout() {
        return caps$LAYOUT;
    }

    private static final long caps$OFFSET = 16;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint64_t caps
     * }
     */
    public static final long caps$offset() {
        return caps$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint64_t caps
     * }
     */
    public static long caps(MemorySegment struct) {
        return struct.get(caps$LAYOUT, caps$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint64_t caps
     * }
     */
    public static void caps(MemorySegment struct, long fieldValue) {
        struct.set(caps$LAYOUT, caps$OFFSET, fieldValue);
    }

    private static final OfLong memory_total$LAYOUT = (OfLong)$LAYOUT.select(groupElement("memory_total"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint64_t memory_total
     * }
     */
    public static final OfLong memory_total$layout() {
        return memory_total$LAYOUT;
    }

    private static final long memory_total$OFFSET = 24;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint64_t memory_total
     * }
     */
    public static final long memory_total$offset() {
        return memory_total$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint64_t memory_total
     * }
     */
    public static long memory_total(MemorySegment struct) {
        return struct.get(memory_total$LAYOUT, memory_total$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint64_t memory_total
     * }
     */
    public static void memory_total(MemorySegment struct, long fieldValue) {
        struct.set(memory_total$LAYOUT, memory_total$OFFSET, fieldValue);
    }

    private static final OfLong memory_free$LAYOUT = (OfLong)$LAYOUT.select(groupElement("memory_free"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint64_t memory_free
     * }
     */
    public static final OfLong memory_free$layout() {
        return memory_free$LAYOUT;
    }

    private static final long memory_free$OFFSET = 32;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint64_t memory_free
     * }
     */
    public static final long memory_free$offset() {
        return memory_free$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint64_t memory_free
     * }
     */
    public static long memory_free(MemorySegment struct) {
        return struct.get(memory_free$LAYOUT, memory_free$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint64_t memory_free
     * }
     */
    public static void memory_free(MemorySegment struct, long fieldValue) {
        struct.set(memory_free$LAYOUT, memory_free$OFFSET, fieldValue);
    }

    private static final SequenceLayout name$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("name"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * char name[128]
     * }
     */
    public static final SequenceLayout name$layout() {
        return name$LAYOUT;
    }

    private static final long name$OFFSET = 40;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * char name[128]
     * }
     */
    public static final long name$offset() {
        return name$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * char name[128]
     * }
     */
    public static MemorySegment name(MemorySegment struct) {
        return struct.asSlice(name$OFFSET, name$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * char name[128]
     * }
     */
    public static void name(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, name$OFFSET, name$LAYOUT.byteSize());
    }

    private static long[] name$DIMS = { 128 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * char name[128]
     * }
     */
    public static long[] name$dimensions() {
        return name$DIMS;
    }
    private static final VarHandle name$ELEM_HANDLE = name$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * char name[128]
     * }
     */
    public static byte name(MemorySegment struct, long index0) {
        return (byte)name$ELEM_HANDLE.get(struct, 0L, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * char name[128]
     * }
     */
    public static void name(MemorySegment struct, long index0, byte fieldValue) {
        name$ELEM_HANDLE.set(struct, 0L, index0, fieldValue);
    }

    private static final SequenceLayout vendor$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("vendor"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * char vendor[64]
     * }
     */
    public static final SequenceLayout vendor$layout() {
        return vendor$LAYOUT;
    }

    private static final long vendor$OFFSET = 168;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * char vendor[64]
     * }
     */
    public static final long vendor$offset() {
        return vendor$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * char vendor[64]
     * }
     */
    public static MemorySegment vendor(MemorySegment struct) {
        return struct.asSlice(vendor$OFFSET, vendor$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * char vendor[64]
     * }
     */
    public static void vendor(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, vendor$OFFSET, vendor$LAYOUT.byteSize());
    }

    private static long[] vendor$DIMS = { 64 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * char vendor[64]
     * }
     */
    public static long[] vendor$dimensions() {
        return vendor$DIMS;
    }
    private static final VarHandle vendor$ELEM_HANDLE = vendor$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * char vendor[64]
     * }
     */
    public static byte vendor(MemorySegment struct, long index0) {
        return (byte)vendor$ELEM_HANDLE.get(struct, 0L, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * char vendor[64]
     * }
     */
    public static void vendor(MemorySegment struct, long index0, byte fieldValue) {
        vendor$ELEM_HANDLE.set(struct, 0L, index0, fieldValue);
    }

    private static final SequenceLayout provider_id$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("provider_id"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * char provider_id[32]
     * }
     */
    public static final SequenceLayout provider_id$layout() {
        return provider_id$LAYOUT;
    }

    private static final long provider_id$OFFSET = 232;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * char provider_id[32]
     * }
     */
    public static final long provider_id$offset() {
        return provider_id$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * char provider_id[32]
     * }
     */
    public static MemorySegment provider_id(MemorySegment struct) {
        return struct.asSlice(provider_id$OFFSET, provider_id$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * char provider_id[32]
     * }
     */
    public static void provider_id(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, provider_id$OFFSET, provider_id$LAYOUT.byteSize());
    }

    private static long[] provider_id$DIMS = { 32 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * char provider_id[32]
     * }
     */
    public static long[] provider_id$dimensions() {
        return provider_id$DIMS;
    }
    private static final VarHandle provider_id$ELEM_HANDLE = provider_id$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * char provider_id[32]
     * }
     */
    public static byte provider_id(MemorySegment struct, long index0) {
        return (byte)provider_id$ELEM_HANDLE.get(struct, 0L, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * char provider_id[32]
     * }
     */
    public static void provider_id(MemorySegment struct, long index0, byte fieldValue) {
        provider_id$ELEM_HANDLE.set(struct, 0L, index0, fieldValue);
    }

    private static final SequenceLayout provider_version$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("provider_version"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * char provider_version[32]
     * }
     */
    public static final SequenceLayout provider_version$layout() {
        return provider_version$LAYOUT;
    }

    private static final long provider_version$OFFSET = 264;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * char provider_version[32]
     * }
     */
    public static final long provider_version$offset() {
        return provider_version$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * char provider_version[32]
     * }
     */
    public static MemorySegment provider_version(MemorySegment struct) {
        return struct.asSlice(provider_version$OFFSET, provider_version$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * char provider_version[32]
     * }
     */
    public static void provider_version(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, provider_version$OFFSET, provider_version$LAYOUT.byteSize());
    }

    private static long[] provider_version$DIMS = { 32 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * char provider_version[32]
     * }
     */
    public static long[] provider_version$dimensions() {
        return provider_version$DIMS;
    }
    private static final VarHandle provider_version$ELEM_HANDLE = provider_version$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * char provider_version[32]
     * }
     */
    public static byte provider_version(MemorySegment struct, long index0) {
        return (byte)provider_version$ELEM_HANDLE.get(struct, 0L, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * char provider_version[32]
     * }
     */
    public static void provider_version(MemorySegment struct, long index0, byte fieldValue) {
        provider_version$ELEM_HANDLE.set(struct, 0L, index0, fieldValue);
    }

    private static final SequenceLayout runtime_version$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("runtime_version"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * char runtime_version[64]
     * }
     */
    public static final SequenceLayout runtime_version$layout() {
        return runtime_version$LAYOUT;
    }

    private static final long runtime_version$OFFSET = 296;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * char runtime_version[64]
     * }
     */
    public static final long runtime_version$offset() {
        return runtime_version$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * char runtime_version[64]
     * }
     */
    public static MemorySegment runtime_version(MemorySegment struct) {
        return struct.asSlice(runtime_version$OFFSET, runtime_version$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * char runtime_version[64]
     * }
     */
    public static void runtime_version(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, runtime_version$OFFSET, runtime_version$LAYOUT.byteSize());
    }

    private static long[] runtime_version$DIMS = { 64 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * char runtime_version[64]
     * }
     */
    public static long[] runtime_version$dimensions() {
        return runtime_version$DIMS;
    }
    private static final VarHandle runtime_version$ELEM_HANDLE = runtime_version$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * char runtime_version[64]
     * }
     */
    public static byte runtime_version(MemorySegment struct, long index0) {
        return (byte)runtime_version$ELEM_HANDLE.get(struct, 0L, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * char runtime_version[64]
     * }
     */
    public static void runtime_version(MemorySegment struct, long index0, byte fieldValue) {
        runtime_version$ELEM_HANDLE.set(struct, 0L, index0, fieldValue);
    }

    private static final SequenceLayout driver_version$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("driver_version"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * char driver_version[64]
     * }
     */
    public static final SequenceLayout driver_version$layout() {
        return driver_version$LAYOUT;
    }

    private static final long driver_version$OFFSET = 360;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * char driver_version[64]
     * }
     */
    public static final long driver_version$offset() {
        return driver_version$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * char driver_version[64]
     * }
     */
    public static MemorySegment driver_version(MemorySegment struct) {
        return struct.asSlice(driver_version$OFFSET, driver_version$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * char driver_version[64]
     * }
     */
    public static void driver_version(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, driver_version$OFFSET, driver_version$LAYOUT.byteSize());
    }

    private static long[] driver_version$DIMS = { 64 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * char driver_version[64]
     * }
     */
    public static long[] driver_version$dimensions() {
        return driver_version$DIMS;
    }
    private static final VarHandle driver_version$ELEM_HANDLE = driver_version$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * char driver_version[64]
     * }
     */
    public static byte driver_version(MemorySegment struct, long index0) {
        return (byte)driver_version$ELEM_HANDLE.get(struct, 0L, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * char driver_version[64]
     * }
     */
    public static void driver_version(MemorySegment struct, long index0, byte fieldValue) {
        driver_version$ELEM_HANDLE.set(struct, 0L, index0, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

