// Generated by jextract

package ai.pipestream.turbo.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct turbo_tensor_info {
 *     uint32_t struct_size;
 *     uint32_t dtype;
 *     uint32_t ndim;
 *     uint32_t reserved;
 *     int64_t shape[8];
 *     char name[64];
 * }
 * }
 */
public class turbo_tensor_info {

    turbo_tensor_info() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        TurboNative.C_INT.withName("struct_size"),
        TurboNative.C_INT.withName("dtype"),
        TurboNative.C_INT.withName("ndim"),
        TurboNative.C_INT.withName("reserved"),
        MemoryLayout.sequenceLayout(8, TurboNative.C_LONG).withName("shape"),
        MemoryLayout.sequenceLayout(64, TurboNative.C_CHAR).withName("name")
    ).withName("turbo_tensor_info");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt struct_size$LAYOUT = (OfInt)$LAYOUT.select(groupElement("struct_size"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t struct_size
     * }
     */
    public static final OfInt struct_size$layout() {
        return struct_size$LAYOUT;
    }

    private static final long struct_size$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t struct_size
     * }
     */
    public static final long struct_size$offset() {
        return struct_size$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t struct_size
     * }
     */
    public static int struct_size(MemorySegment struct) {
        return struct.get(struct_size$LAYOUT, struct_size$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t struct_size
     * }
     */
    public static void struct_size(MemorySegment struct, int fieldValue) {
        struct.set(struct_size$LAYOUT, struct_size$OFFSET, fieldValue);
    }

    private static final OfInt dtype$LAYOUT = (OfInt)$LAYOUT.select(groupElement("dtype"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t dtype
     * }
     */
    public static final OfInt dtype$layout() {
        return dtype$LAYOUT;
    }

    private static final long dtype$OFFSET = 4;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t dtype
     * }
     */
    public static final long dtype$offset() {
        return dtype$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t dtype
     * }
     */
    public static int dtype(MemorySegment struct) {
        return struct.get(dtype$LAYOUT, dtype$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t dtype
     * }
     */
    public static void dtype(MemorySegment struct, int fieldValue) {
        struct.set(dtype$LAYOUT, dtype$OFFSET, fieldValue);
    }

    private static final OfInt ndim$LAYOUT = (OfInt)$LAYOUT.select(groupElement("ndim"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t ndim
     * }
     */
    public static final OfInt ndim$layout() {
        return ndim$LAYOUT;
    }

    private static final long ndim$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t ndim
     * }
     */
    public static final long ndim$offset() {
        return ndim$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t ndim
     * }
     */
    public static int ndim(MemorySegment struct) {
        return struct.get(ndim$LAYOUT, ndim$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t ndim
     * }
     */
    public static void ndim(MemorySegment struct, int fieldValue) {
        struct.set(ndim$LAYOUT, ndim$OFFSET, fieldValue);
    }

    private static final OfInt reserved$LAYOUT = (OfInt)$LAYOUT.select(groupElement("reserved"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t reserved
     * }
     */
    public static final OfInt reserved$layout() {
        return reserved$LAYOUT;
    }

    private static final long reserved$OFFSET = 12;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t reserved
     * }
     */
    public static final long reserved$offset() {
        return reserved$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t reserved
     * }
     */
    public static int reserved(MemorySegment struct) {
        return struct.get(reserved$LAYOUT, reserved$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t reserved
     * }
     */
    public static void reserved(MemorySegment struct, int fieldValue) {
        struct.set(reserved$LAYOUT, reserved$OFFSET, fieldValue);
    }

    private static final SequenceLayout shape$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("shape"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int64_t shape[8]
     * }
     */
    public static final SequenceLayout shape$layout() {
        return shape$LAYOUT;
    }

    private static final long shape$OFFSET = 16;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int64_t shape[8]
     * }
     */
    public static final long shape$offset() {
        return shape$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int64_t shape[8]
     * }
     */
    public static MemorySegment shape(MemorySegment struct) {
        return struct.asSlice(shape$OFFSET, shape$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int64_t shape[8]
     * }
     */
    public static void shape(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, shape$OFFSET, shape$LAYOUT.byteSize());
    }

    private static long[] shape$DIMS = { 8 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * int64_t shape[8]
     * }
     */
    public static long[] shape$dimensions() {
        return shape$DIMS;
    }
    private static final VarHandle shape$ELEM_HANDLE = shape$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * int64_t shape[8]
     * }
     */
    public static long shape(MemorySegment struct, long index0) {
        return (long)shape$ELEM_HANDLE.get(struct, 0L, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * int64_t shape[8]
     * }
     */
    public static void shape(MemorySegment struct, long index0, long fieldValue) {
        shape$ELEM_HANDLE.set(struct, 0L, index0, fieldValue);
    }

    private static final SequenceLayout name$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("name"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * char name[64]
     * }
     */
    public static final SequenceLayout name$layout() {
        return name$LAYOUT;
    }

    private static final long name$OFFSET = 80;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * char name[64]
     * }
     */
    public static final long name$offset() {
        return name$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * char name[64]
     * }
     */
    public static MemorySegment name(MemorySegment struct) {
        return struct.asSlice(name$OFFSET, name$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * char name[64]
     * }
     */
    public static void name(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, name$OFFSET, name$LAYOUT.byteSize());
    }

    private static long[] name$DIMS = { 64 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * char name[64]
     * }
     */
    public static long[] name$dimensions() {
        return name$DIMS;
    }
    private static final VarHandle name$ELEM_HANDLE = name$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * char name[64]
     * }
     */
    public static byte name(MemorySegment struct, long index0) {
        return (byte)name$ELEM_HANDLE.get(struct, 0L, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * char name[64]
     * }
     */
    public static void name(MemorySegment struct, long index0, byte fieldValue) {
        name$ELEM_HANDLE.set(struct, 0L, index0, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

