// Generated by jextract

package ai.pipestream.turbo.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct turbo_buffer_desc {
 *     uint32_t struct_size;
 *     uint32_t placement;
 *     uint32_t dtype;
 *     uint32_t ndim;
 *     uint64_t shape[8];
 *     uint64_t strides[8];
 *     uint64_t bytes;
 *     const void *next;
 * }
 * }
 */
public class turbo_buffer_desc {

    turbo_buffer_desc() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        TurboNative.C_INT.withName("struct_size"),
        TurboNative.C_INT.withName("placement"),
        TurboNative.C_INT.withName("dtype"),
        TurboNative.C_INT.withName("ndim"),
        MemoryLayout.sequenceLayout(8, TurboNative.C_LONG).withName("shape"),
        MemoryLayout.sequenceLayout(8, TurboNative.C_LONG).withName("strides"),
        TurboNative.C_LONG.withName("bytes"),
        TurboNative.C_POINTER.withName("next")
    ).withName("turbo_buffer_desc");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt struct_size$LAYOUT = (OfInt)$LAYOUT.select(groupElement("struct_size"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t struct_size
     * }
     */
    public static final OfInt struct_size$layout() {
        return struct_size$LAYOUT;
    }

    private static final long struct_size$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t struct_size
     * }
     */
    public static final long struct_size$offset() {
        return struct_size$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t struct_size
     * }
     */
    public static int struct_size(MemorySegment struct) {
        return struct.get(struct_size$LAYOUT, struct_size$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t struct_size
     * }
     */
    public static void struct_size(MemorySegment struct, int fieldValue) {
        struct.set(struct_size$LAYOUT, struct_size$OFFSET, fieldValue);
    }

    private static final OfInt placement$LAYOUT = (OfInt)$LAYOUT.select(groupElement("placement"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t placement
     * }
     */
    public static final OfInt placement$layout() {
        return placement$LAYOUT;
    }

    private static final long placement$OFFSET = 4;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t placement
     * }
     */
    public static final long placement$offset() {
        return placement$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t placement
     * }
     */
    public static int placement(MemorySegment struct) {
        return struct.get(placement$LAYOUT, placement$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t placement
     * }
     */
    public static void placement(MemorySegment struct, int fieldValue) {
        struct.set(placement$LAYOUT, placement$OFFSET, fieldValue);
    }

    private static final OfInt dtype$LAYOUT = (OfInt)$LAYOUT.select(groupElement("dtype"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t dtype
     * }
     */
    public static final OfInt dtype$layout() {
        return dtype$LAYOUT;
    }

    private static final long dtype$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t dtype
     * }
     */
    public static final long dtype$offset() {
        return dtype$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t dtype
     * }
     */
    public static int dtype(MemorySegment struct) {
        return struct.get(dtype$LAYOUT, dtype$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t dtype
     * }
     */
    public static void dtype(MemorySegment struct, int fieldValue) {
        struct.set(dtype$LAYOUT, dtype$OFFSET, fieldValue);
    }

    private static final OfInt ndim$LAYOUT = (OfInt)$LAYOUT.select(groupElement("ndim"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t ndim
     * }
     */
    public static final OfInt ndim$layout() {
        return ndim$LAYOUT;
    }

    private static final long ndim$OFFSET = 12;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t ndim
     * }
     */
    public static final long ndim$offset() {
        return ndim$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t ndim
     * }
     */
    public static int ndim(MemorySegment struct) {
        return struct.get(ndim$LAYOUT, ndim$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t ndim
     * }
     */
    public static void ndim(MemorySegment struct, int fieldValue) {
        struct.set(ndim$LAYOUT, ndim$OFFSET, fieldValue);
    }

    private static final SequenceLayout shape$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("shape"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint64_t shape[8]
     * }
     */
    public static final SequenceLayout shape$layout() {
        return shape$LAYOUT;
    }

    private static final long shape$OFFSET = 16;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint64_t shape[8]
     * }
     */
    public static final long shape$offset() {
        return shape$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint64_t shape[8]
     * }
     */
    public static MemorySegment shape(MemorySegment struct) {
        return struct.asSlice(shape$OFFSET, shape$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint64_t shape[8]
     * }
     */
    public static void shape(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, shape$OFFSET, shape$LAYOUT.byteSize());
    }

    private static long[] shape$DIMS = { 8 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * uint64_t shape[8]
     * }
     */
    public static long[] shape$dimensions() {
        return shape$DIMS;
    }
    private static final VarHandle shape$ELEM_HANDLE = shape$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * uint64_t shape[8]
     * }
     */
    public static long shape(MemorySegment struct, long index0) {
        return (long)shape$ELEM_HANDLE.get(struct, 0L, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * uint64_t shape[8]
     * }
     */
    public static void shape(MemorySegment struct, long index0, long fieldValue) {
        shape$ELEM_HANDLE.set(struct, 0L, index0, fieldValue);
    }

    private static final SequenceLayout strides$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("strides"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint64_t strides[8]
     * }
     */
    public static final SequenceLayout strides$layout() {
        return strides$LAYOUT;
    }

    private static final long strides$OFFSET = 80;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint64_t strides[8]
     * }
     */
    public static final long strides$offset() {
        return strides$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint64_t strides[8]
     * }
     */
    public static MemorySegment strides(MemorySegment struct) {
        return struct.asSlice(strides$OFFSET, strides$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint64_t strides[8]
     * }
     */
    public static void strides(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, strides$OFFSET, strides$LAYOUT.byteSize());
    }

    private static long[] strides$DIMS = { 8 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * uint64_t strides[8]
     * }
     */
    public static long[] strides$dimensions() {
        return strides$DIMS;
    }
    private static final VarHandle strides$ELEM_HANDLE = strides$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * uint64_t strides[8]
     * }
     */
    public static long strides(MemorySegment struct, long index0) {
        return (long)strides$ELEM_HANDLE.get(struct, 0L, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * uint64_t strides[8]
     * }
     */
    public static void strides(MemorySegment struct, long index0, long fieldValue) {
        strides$ELEM_HANDLE.set(struct, 0L, index0, fieldValue);
    }

    private static final OfLong bytes$LAYOUT = (OfLong)$LAYOUT.select(groupElement("bytes"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint64_t bytes
     * }
     */
    public static final OfLong bytes$layout() {
        return bytes$LAYOUT;
    }

    private static final long bytes$OFFSET = 144;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint64_t bytes
     * }
     */
    public static final long bytes$offset() {
        return bytes$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint64_t bytes
     * }
     */
    public static long bytes(MemorySegment struct) {
        return struct.get(bytes$LAYOUT, bytes$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint64_t bytes
     * }
     */
    public static void bytes(MemorySegment struct, long fieldValue) {
        struct.set(bytes$LAYOUT, bytes$OFFSET, fieldValue);
    }

    private static final AddressLayout next$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("next"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const void *next
     * }
     */
    public static final AddressLayout next$layout() {
        return next$LAYOUT;
    }

    private static final long next$OFFSET = 152;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const void *next
     * }
     */
    public static final long next$offset() {
        return next$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const void *next
     * }
     */
    public static MemorySegment next(MemorySegment struct) {
        return struct.get(next$LAYOUT, next$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const void *next
     * }
     */
    public static void next(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(next$LAYOUT, next$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

