/* SPDX-License-Identifier: Apache-2.0 */

#ifndef TURBO_TYPES_H
#define TURBO_TYPES_H

/* Generated by cbindgen from crates/turbo-abi. Do not edit; run scripts/gen-header.sh. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include <stddef.h>
#include <stdint.h>
#include <stdbool.h>
/* Opaque, reference-counted handles. Only ever used behind pointers. */
typedef struct turbo_runtime turbo_runtime;
typedef struct turbo_context turbo_context;
typedef struct turbo_buffer turbo_buffer;
typedef struct turbo_model turbo_model;
typedef struct turbo_session turbo_session;
typedef struct turbo_result turbo_result;
typedef struct turbo_generation turbo_generation;
typedef struct turbo_tokenizer turbo_tokenizer;
typedef struct turbo_chunk_plan turbo_chunk_plan;


/**
 * ABI version. Bumped only for a breaking layout or semantic change.
 */
#define TURBO_ABI_VERSION 2

/**
 * Success.
 */
#define TURBO_OK 0

/**
 * A caller argument is invalid; `turbo_error.field` may name it.
 */
#define TURBO_E_INVALID_ARGUMENT 256

/**
 * A descriptor's `struct_size` is not one this library understands.
 */
#define TURBO_E_INVALID_STRUCT_SIZE 257

/**
 * A text view is not valid UTF-8.
 */
#define TURBO_E_INVALID_UTF8 258

/**
 * A handle is null or of the wrong kind.
 */
#define TURBO_E_INVALID_HANDLE 259

/**
 * A shape, stride, or byte count is inconsistent or overflows.
 */
#define TURBO_E_INVALID_SHAPE 260

/**
 * The operation is not valid in the handle's current state (for example
 * `run` before any input was written, or use after cancel).
 */
#define TURBO_E_INVALID_STATE 261

/**
 * A constant (dtype, task, option value) is outside the known set.
 */
#define TURBO_E_INVALID_ENUM 262

/**
 * The requested combination is unsupported here; see `message`.
 */
#define TURBO_E_UNSUPPORTED 512

/**
 * An option field is not honored by this provider for this model;
 * `turbo_error.field` is the 1-based field index in the options struct.
 */
#define TURBO_E_UNSUPPORTED_OPTION 513

/**
 * The task is not offered on this device for this model.
 */
#define TURBO_E_UNSUPPORTED_TASK 514

/**
 * The dtype is not supported in the requested placement.
 */
#define TURBO_E_UNSUPPORTED_DTYPE 515

/**
 * The placement is not supported by this device.
 */
#define TURBO_E_UNSUPPORTED_PLACEMENT 516

/**
 * Declared in the header but not implemented in this build. Never a silent fallback.
 */
#define TURBO_E_NOT_IMPLEMENTED 517

/**
 * The modality is not offered on this device for this model.
 */
#define TURBO_E_UNSUPPORTED_MODALITY 518

/**
 * Allocation failed.
 */
#define TURBO_E_OUT_OF_MEMORY 768

/**
 * The session or generation has an operation or result lease in flight.
 */
#define TURBO_E_BUSY 769

/**
 * The provider is refusing new work; retry later.
 */
#define TURBO_E_OVERLOADED 770

/**
 * The request exceeds a declared capacity (batch, sequence, output size).
 */
#define TURBO_E_CAPACITY 771

/**
 * No device matches the selector.
 */
#define TURBO_E_DEVICE_NOT_FOUND 1024

/**
 * The device exists but cannot be used (driver missing, busy, failed probe).
 */
#define TURBO_E_DEVICE_UNAVAILABLE 1025

/**
 * The vendor runtime reported an error; `message` carries its text.
 */
#define TURBO_E_RUNTIME 1026

/**
 * A provider library could not be loaded or did not export the entry point.
 */
#define TURBO_E_PROVIDER_LOAD 1027

/**
 * A provider library targets a different ABI version.
 */
#define TURBO_E_ABI_MISMATCH 1028

/**
 * The operation was cancelled by the caller.
 */
#define TURBO_E_CANCELLED 1029

/**
 * The bundle directory or a required file is missing.
 */
#define TURBO_E_BUNDLE_NOT_FOUND 1280

/**
 * The bundle manifest is malformed or declares an unknown version.
 */
#define TURBO_E_BUNDLE_INVALID 1281

/**
 * A bundle file does not match its recorded hash.
 */
#define TURBO_E_BUNDLE_INTEGRITY 1282

/**
 * The bundle is valid but no artifact in it is loadable by this provider.
 */
#define TURBO_E_BUNDLE_NO_ARTIFACT 1283

/**
 * A bug in the library or provider.
 */
#define TURBO_E_INTERNAL 1536

/**
 * A panic or exception was caught at the language boundary.
 */
#define TURBO_E_PANIC 1537

/**
 * Device kind: CPU.
 */
#define TURBO_DEVICE_CPU 1

/**
 * Device kind: discrete GPU.
 */
#define TURBO_DEVICE_GPU 2

/**
 * Device kind: integrated GPU.
 */
#define TURBO_DEVICE_IGPU 3

/**
 * Device kind: neural processing unit.
 */
#define TURBO_DEVICE_NPU 4

/**
 * Device kind: other accelerator.
 */
#define TURBO_DEVICE_ACCEL 5

/**
 * Task: dense text embedding.
 */
#define TURBO_TASK_EMBED 1

/**
 * Task: cross-encoder reranking.
 */
#define TURBO_TASK_RERANK 2

/**
 * Task: sequence classification with labels.
 */
#define TURBO_TASK_CLASSIFY 3

/**
 * Task: per-token classification with span aggregation.
 */
#define TURBO_TASK_TOKEN_CLASSIFY 4

/**
 * Task: causal generation.
 */
#define TURBO_TASK_GENERATE 5

/**
 * Task: tokenize / detokenize.
 */
#define TURBO_TASK_TOKENIZE 6

/**
 * Task: generic named-tensor execution.
 */
#define TURBO_TASK_RUN 7

/**
 * Task: source chunking (host utility).
 */
#define TURBO_TASK_CHUNK 8

/**
 * Modality: text.
 */
#define TURBO_MODALITY_TEXT 1

/**
 * Modality: audio.
 */
#define TURBO_MODALITY_AUDIO 2

/**
 * Modality: image.
 */
#define TURBO_MODALITY_IMAGE 3

/**
 * Modality: video.
 */
#define TURBO_MODALITY_VIDEO 4

/**
 * Capability status: not offered.
 */
#define TURBO_CAP_UNSUPPORTED 0

/**
 * Capability status: planned, code path may exist but is not qualified.
 */
#define TURBO_CAP_PLANNED 1

/**
 * Capability status: works, not yet qualified with receipts.
 */
#define TURBO_CAP_EXPERIMENTAL 2

/**
 * Capability status: qualified with conformance, precision, and benchmark receipts.
 */
#define TURBO_CAP_SUPPORTED 3

/**
 * Model kind: embedder.
 */
#define TURBO_MODEL_EMBEDDING 1

/**
 * Model kind: cross-encoder reranker.
 */
#define TURBO_MODEL_RERANKER 2

/**
 * Model kind: sequence classifier.
 */
#define TURBO_MODEL_CLASSIFIER 3

/**
 * Model kind: token classifier.
 */
#define TURBO_MODEL_TOKEN_CLASSIFIER 4

/**
 * Model kind: generative language model.
 */
#define TURBO_MODEL_GENERATIVE 5

/**
 * Model kind: generic graph with named inputs and outputs.
 */
#define TURBO_MODEL_GENERIC 6

/**
 * Element type: boolean (one byte).
 */
#define TURBO_DTYPE_BOOL 1

/**
 * Element type: unsigned 8-bit.
 */
#define TURBO_DTYPE_U8 2

/**
 * Element type: unsigned 16-bit.
 */
#define TURBO_DTYPE_U16 3

/**
 * Element type: unsigned 32-bit.
 */
#define TURBO_DTYPE_U32 4

/**
 * Element type: unsigned 64-bit.
 */
#define TURBO_DTYPE_U64 5

/**
 * Element type: signed 8-bit.
 */
#define TURBO_DTYPE_I8 6

/**
 * Element type: signed 16-bit.
 */
#define TURBO_DTYPE_I16 7

/**
 * Element type: signed 32-bit.
 */
#define TURBO_DTYPE_I32 8

/**
 * Element type: signed 64-bit.
 */
#define TURBO_DTYPE_I64 9

/**
 * Element type: IEEE half.
 */
#define TURBO_DTYPE_F16 10

/**
 * Element type: bfloat16.
 */
#define TURBO_DTYPE_BF16 11

/**
 * Element type: IEEE single.
 */
#define TURBO_DTYPE_F32 12

/**
 * Element type: IEEE double.
 */
#define TURBO_DTYPE_F64 13

/**
 * Element type: length-prefixed byte strings (KServe BYTES): each element is
 * a little-endian `uint32_t` length followed by that many bytes.
 */
#define TURBO_DTYPE_BYTES 14

/**
 * Placement: pageable host memory.
 */
#define TURBO_PLACE_HOST 1

/**
 * Placement: page-locked host memory visible to the device.
 */
#define TURBO_PLACE_PINNED 2

/**
 * Placement: device memory.
 */
#define TURBO_PLACE_DEVICE 3

/**
 * Placement: memory shared between host and device (unified / USM shared).
 */
#define TURBO_PLACE_SHARED 4

/**
 * Device selection policy: the host's best accelerator; never CPU.
 */
#define TURBO_SELECT_AUTO 0

/**
 * Device selection policy: exactly the device the selector names.
 */
#define TURBO_SELECT_EXPLICIT 1

/**
 * Pipeline stage index: tokenization.
 */
#define TURBO_STAGE_TOKENIZE 0

/**
 * Pipeline stage index: encoder / model forward.
 */
#define TURBO_STAGE_ENCODE 1

/**
 * Pipeline stage index: pooling.
 */
#define TURBO_STAGE_POOL 2

/**
 * Pipeline stage index: normalization.
 */
#define TURBO_STAGE_NORMALIZE 3

/**
 * Pipeline stage index: post-processing (softmax, aggregation, sampling).
 */
#define TURBO_STAGE_POSTPROCESS 4

/**
 * Number of pipeline stages reported.
 */
#define TURBO_STAGE_COUNT 5

/**
 * Stage placement: the stage does not apply to this model.
 */
#define TURBO_STAGE_UNUSED 0

/**
 * Stage placement: runs on the host.
 */
#define TURBO_STAGE_HOST 1

/**
 * Stage placement: runs on the device as a separate step.
 */
#define TURBO_STAGE_DEVICE 2

/**
 * Stage placement: fused into the device graph with adjacent stages.
 */
#define TURBO_STAGE_FUSED 3

/**
 * Option value meaning "use the model contract".
 */
#define TURBO_OPT_MODEL 0

/**
 * Truncation: as the model contract says (`TURBO_OPT_MODEL`).
 */
#define TURBO_TRUNCATE_MODEL 0

/**
 * Truncation: never; over-length input is an error.
 */
#define TURBO_TRUNCATE_NONE 1

/**
 * Truncation: drop tokens from the end.
 */
#define TURBO_TRUNCATE_RIGHT 2

/**
 * Truncation: drop tokens from the start.
 */
#define TURBO_TRUNCATE_LEFT 3

/**
 * Prompt role: no prefix.
 */
#define TURBO_PROMPT_NONE 0

/**
 * Prompt role: apply the bundle's query prefix.
 */
#define TURBO_PROMPT_QUERY 1

/**
 * Prompt role: apply the bundle's document prefix.
 */
#define TURBO_PROMPT_DOCUMENT 2

/**
 * Normalization: as the model contract says.
 */
#define TURBO_NORMALIZE_MODEL 0

/**
 * Normalization: none.
 */
#define TURBO_NORMALIZE_NONE 1

/**
 * Normalization: L2.
 */
#define TURBO_NORMALIZE_L2 2

/**
 * Pooling: as the model contract says.
 */
#define TURBO_POOLING_MODEL 0

/**
 * Pooling: masked mean.
 */
#define TURBO_POOLING_MEAN 1

/**
 * Pooling: first token.
 */
#define TURBO_POOLING_CLS 2

/**
 * Pooling: last non-padding token.
 */
#define TURBO_POOLING_LAST 3

/**
 * Output dtype: as the model contract says.
 */
#define TURBO_OUTPUT_MODEL 0

/**
 * Output dtype: FP32.
 */
#define TURBO_OUTPUT_F32 1

/**
 * Output dtype: FP16.
 */
#define TURBO_OUTPUT_F16 2

/**
 * Output dtype: int8 quantized.
 */
#define TURBO_OUTPUT_I8 3

/**
 * Token-classification aggregation: as the model contract says.
 */
#define TURBO_AGGREGATE_MODEL 0

/**
 * Token-classification aggregation: none, per-token labels only.
 */
#define TURBO_AGGREGATE_NONE 1

/**
 * Token-classification aggregation: merge consecutive same-label tokens.
 */
#define TURBO_AGGREGATE_SIMPLE 2

/**
 * Token-classification aggregation: label of the first sub-token wins.
 */
#define TURBO_AGGREGATE_FIRST 3

/**
 * Token-classification aggregation: highest-scoring sub-token wins.
 */
#define TURBO_AGGREGATE_MAX 4

/**
 * Generation finish reason: not finished.
 */
#define TURBO_FINISH_NONE 0

/**
 * Generation finish reason: end-of-sequence token.
 */
#define TURBO_FINISH_EOS 1

/**
 * Generation finish reason: a stop string or stop token matched.
 */
#define TURBO_FINISH_STOP 2

/**
 * Generation finish reason: `max_new_tokens` reached.
 */
#define TURBO_FINISH_LENGTH 3

/**
 * Generation finish reason: cancelled by the caller.
 */
#define TURBO_FINISH_CANCELLED 4

/**
 * Structured output: none.
 */
#define TURBO_STRUCTURED_NONE 0

/**
 * Structured output: constrain to a JSON schema (text is the schema).
 */
#define TURBO_STRUCTURED_JSON_SCHEMA 1

/**
 * Structured output: constrain to a grammar (text is GBNF).
 */
#define TURBO_STRUCTURED_GRAMMAR 2

/**
 * Push-generation callback return: keep generating.
 */
#define TURBO_STREAM_CONTINUE 0

/**
 * Push-generation callback return: stop after this chunk.
 */
#define TURBO_STREAM_STOP 1

/**
 * Native handle kind: host pointer.
 */
#define TURBO_HANDLE_HOST_PTR 1

/**
 * Native handle kind: CUDA device pointer (`aux` = device ordinal).
 */
#define TURBO_HANDLE_CUDA_PTR 2

/**
 * Native handle kind: OpenCL `cl_mem` (`aux` = `cl_context`).
 */
#define TURBO_HANDLE_CL_MEM 3

/**
 * Native handle kind: Level Zero USM pointer (`aux` = `ze_context_handle_t`).
 */
#define TURBO_HANDLE_ZE_USM 4

/**
 * Native handle kind: Metal `MTLBuffer` (`aux` = `MTLDevice`).
 */
#define TURBO_HANDLE_MTL_BUFFER 5

/**
 * Native handle kind: Linux DMA-BUF file descriptor.
 */
#define TURBO_HANDLE_DMABUF_FD 6

/**
 * I/O direction: model input.
 */
#define TURBO_IO_INPUT 1

/**
 * I/O direction: model output.
 */
#define TURBO_IO_OUTPUT 2

/**
 * Runtime flag: do not scan the default provider search path.
 */
#define TURBO_RUNTIME_NO_DEFAULT_PROVIDERS (1 << 0)

/**
 * The device can execute asynchronously (`turbo_session_submit` + fences).
 */
#define TURBO_CAP_ASYNC 1

/**
 * Caller host memory can be imported without a copy.
 */
#define TURBO_CAP_HOST_PTR_IMPORT 2

/**
 * Results can stay resident on the device and be exported.
 */
#define TURBO_CAP_DEVICE_RESULT 4

/**
 * A caller-owned queue/stream can be imported.
 */
#define TURBO_CAP_EXTERNAL_QUEUE 8

/**
 * DMA-BUF import.
 */
#define TURBO_CAP_DMABUF 16

/**
 * Host and device share one address space (unified / USM shared).
 */
#define TURBO_CAP_UNIFIED_MEMORY 32

/**
 * Sessions may run any shape up to their maximum without recompiling.
 */
#define TURBO_CAP_DYNAMIC_SHAPE 64

/**
 * Sessions on one model share weights.
 */
#define TURBO_CAP_WEIGHT_SHARING 128

/**
 * Tokenization runs on the device from raw UTF-8.
 */
#define TURBO_CAP_DEVICE_TOKENIZE 256

/**
 * Post-processing (softmax, aggregation) runs on the device.
 */
#define TURBO_CAP_DEVICE_POSTPROCESS 512

/**
 * Deterministic results across runs for the same inputs and seed.
 */
#define TURBO_CAP_DETERMINISTIC 1024

/**
 * Option `truncate` is honored.
 */
#define TURBO_CAP_OPT_TRUNCATE 65536

/**
 * Option `max_tokens` is honored.
 */
#define TURBO_CAP_OPT_MAX_TOKENS 131072

/**
 * Option `prompt_role` is honored.
 */
#define TURBO_CAP_OPT_PROMPT_ROLE 262144

/**
 * Option `normalize` may differ from the model contract.
 */
#define TURBO_CAP_OPT_NORMALIZE 524288

/**
 * Option `pooling` may differ from the model contract.
 */
#define TURBO_CAP_OPT_POOLING_OVERRIDE 1048576

/**
 * Option `output_dim` (Matryoshka truncation) is honored.
 */
#define TURBO_CAP_OPT_OUTPUT_DIM 2097152

/**
 * Option `output_dtype` is honored.
 */
#define TURBO_CAP_OPT_OUTPUT_DTYPE 4194304

/**
 * Rerank `top_n` and sorted output are computed by the provider.
 */
#define TURBO_CAP_OPT_TOP_N 8388608

/**
 * Token-classification `aggregation` may differ from the model contract.
 */
#define TURBO_CAP_OPT_AGGREGATION 16777216

/**
 * Rerank and classify `raw_scores` (logits instead of activated scores) is honored.
 */
#define TURBO_CAP_OPT_RAW_SCORES 33554432

/**
 * Generation: structured output (JSON schema / grammar).
 */
#define TURBO_CAP_OPT_GEN_STRUCTURED 4294967296

/**
 * Generation: tool definitions in the prompt template.
 */
#define TURBO_CAP_OPT_GEN_TOOLS 8589934592

/**
 * Generation: `n_sequences > 1`.
 */
#define TURBO_CAP_OPT_GEN_N 17179869184

/**
 * Generation: `logit_bias`.
 */
#define TURBO_CAP_OPT_GEN_LOGIT_BIAS 34359738368

/**
 * Generation: presence / frequency / repeat penalties.
 */
#define TURBO_CAP_OPT_GEN_PENALTIES 68719476736

/**
 * Generation: per-token logprobs.
 */
#define TURBO_CAP_OPT_GEN_LOGPROBS 137438953472

/**
 * Generation: stop strings (as opposed to stop token ids only).
 */
#define TURBO_CAP_OPT_GEN_STOP_STRINGS 274877906944

/**
 * Generation: `seed` is honored (implies reproducible sampling).
 */
#define TURBO_CAP_OPT_GEN_SEED 549755813888

/**
 * Generation: sampling controls `temperature`, `top_k`, `top_p`, `min_p`.
 */
#define TURBO_CAP_OPT_GEN_SAMPLING 1099511627776

/**
 * Generation: `min_new_tokens`.
 */
#define TURBO_CAP_OPT_GEN_MIN_TOKENS 2199023255552

/**
 * Generation: `echo` (the prompt is included in the output text).
 */
#define TURBO_CAP_OPT_GEN_ECHO 4398046511104

/**
 * Generation: stop token ids.
 */
#define TURBO_CAP_OPT_GEN_STOP_TOKENS 8796093022208

/**
 * Length of `turbo_error.message` including the terminating NUL.
 */
#define TURBO_ERROR_MESSAGE_LEN 496

/**
 * Maximum tensor rank.
 */
#define TURBO_MAX_RANK 8

/**
 * UTF-8 view. `ptr` may be NULL only when `len == 0`. Not NUL-terminated.
 */
typedef struct turbo_text {
    /**
     * Start of the bytes.
     */
    const char *ptr;
    /**
     * Byte length.
     */
    uint64_t len;
} turbo_text;

/**
 * Key / value pair of UTF-8 views, used for provider options and request parameters.
 */
typedef struct turbo_kv {
    /**
     * Option name.
     */
    struct turbo_text key;
    /**
     * Option value.
     */
    struct turbo_text value;
} turbo_kv;

/**
 * Caller-owned error record. On success `code == 0` and `message[0] == 0`.
 * The message is always NUL-terminated UTF-8. `field` is the 1-based index
 * of the offending field in the descriptor for `TURBO_E_UNSUPPORTED_OPTION`
 * and `TURBO_E_INVALID_ARGUMENT`, otherwise 0. May be NULL in any call, in
 * which case only the status code is returned.
 */
typedef struct turbo_error {
    /**
     * `sizeof(turbo_error)`.
     */
    uint32_t struct_size;
    /**
     * Status code.
     */
    int32_t code;
    /**
     * Offending field index, or 0.
     */
    uint32_t field;
    /**
     * NUL-terminated message.
     */
    char message[TURBO_ERROR_MESSAGE_LEN];
} turbo_error;

/**
 * Log callback: `level` 0 error, 1 warn, 2 info, 3 debug; `message` is a UTF-8 view valid for the call.
 */
typedef void (*turbo_log_fn)(void *user_data,
                             uint32_t level,
                             struct turbo_text message);

/**
 * Runtime creation descriptor.
 */
typedef struct turbo_runtime_desc {
    /**
     * `sizeof(turbo_runtime_desc)`.
     */
    uint32_t struct_size;
    /**
     * `TURBO_RUNTIME_*` flags.
     */
    uint32_t flags;
    /**
     * Number of explicit provider library paths.
     */
    uint32_t n_provider_paths;
    /**
     * Reserved; must be 0.
     */
    uint32_t reserved;
    /**
     * Explicit provider library paths (loaded in order, errors reported).
     */
    const struct turbo_text *provider_paths;
    /**
     * Optional log sink.
     */
    turbo_log_fn log;
    /**
     * Passed to `log`.
     */
    void *log_user_data;
} turbo_runtime_desc;

/**
 * Device selector for `turbo_runtime_select_device`.
 */
typedef struct turbo_device_selector {
    /**
     * `sizeof(turbo_device_selector)`.
     */
    uint32_t struct_size;
    /**
     * `TURBO_SELECT_AUTO` or `TURBO_SELECT_EXPLICIT`.
     */
    uint32_t policy;
    /**
     * Bitmask of accepted `TURBO_DEVICE_*` kinds shifted (`1 << kind`); 0 = any non-CPU for AUTO.
     */
    uint32_t kind_mask;
    /**
     * Ordinal within the provider (EXPLICIT only).
     */
    uint32_t ordinal;
    /**
     * Provider id, empty = any.
     */
    struct turbo_text provider_id;
    /**
     * Vendor substring, empty = any.
     */
    struct turbo_text vendor;
} turbo_device_selector;

/**
 * Static device description.
 */
typedef struct turbo_device_info {
    /**
     * `sizeof(turbo_device_info)`.
     */
    uint32_t struct_size;
    /**
     * `TURBO_DEVICE_*`.
     */
    uint32_t kind;
    /**
     * Ordinal within the provider.
     */
    uint32_t ordinal;
    /**
     * PCI vendor id where known, else 0.
     */
    uint32_t vendor_id;
    /**
     * `TURBO_CAP_*` bits.
     */
    uint64_t caps;
    /**
     * Total device memory in bytes, 0 if unknown.
     */
    uint64_t memory_total;
    /**
     * Free device memory in bytes at query time, 0 if unknown.
     */
    uint64_t memory_free;
    /**
     * Human-readable device name.
     */
    char name[128];
    /**
     * Vendor name.
     */
    char vendor[64];
    /**
     * Provider id (for example `cuda`, `openvino`, `mock`).
     */
    char provider_id[32];
    /**
     * Provider library version.
     */
    char provider_version[32];
    /**
     * Vendor runtime version.
     */
    char runtime_version[64];
    /**
     * Driver version, empty if not applicable.
     */
    char driver_version[64];
} turbo_device_info;

/**
 * One cell of the capability matrix for (device, task, modality).
 */
typedef struct turbo_capability {
    /**
     * `sizeof(turbo_capability)`.
     */
    uint32_t struct_size;
    /**
     * `TURBO_CAP_UNSUPPORTED` .. `TURBO_CAP_SUPPORTED`.
     */
    uint32_t status;
    /**
     * Compute dtype used (`TURBO_DTYPE_*`), 0 if not applicable.
     */
    uint32_t dtype;
    /**
     * Reference dtype the precision figures are measured against, 0 if none.
     */
    uint32_t reference_dtype;
    /**
     * Measured cosine-similarity floor against the reference; 0 if unmeasured.
     */
    float cosine_floor;
    /**
     * Measured maximum absolute error against the reference; 0 if unmeasured.
     */
    float max_abs_error;
    /**
     * 1 if results are bit-reproducible across runs.
     */
    uint32_t deterministic;
    /**
     * Reserved; 0.
     */
    uint32_t reserved;
    /**
     * Free-text qualification note (receipt id, limits).
     */
    char notes[128];
} turbo_capability;

/**
 * Context creation descriptor.
 */
typedef struct turbo_context_desc {
    /**
     * `sizeof(turbo_context_desc)`.
     */
    uint32_t struct_size;
    /**
     * Reserved; 0.
     */
    uint32_t flags;
    /**
     * Number of provider options.
     */
    uint32_t n_options;
    /**
     * Reserved; 0.
     */
    uint32_t reserved;
    /**
     * Provider options (unknown keys are rejected).
     */
    const struct turbo_kv *options;
    /**
     * Extension chain for external queue import; NULL otherwise.
     */
    const void *next;
} turbo_context_desc;

/**
 * Buffer description. `strides` are in bytes; all-zero means packed row-major.
 */
typedef struct turbo_buffer_desc {
    /**
     * `sizeof(turbo_buffer_desc)`.
     */
    uint32_t struct_size;
    /**
     * `TURBO_PLACE_*`.
     */
    uint32_t placement;
    /**
     * `TURBO_DTYPE_*`.
     */
    uint32_t dtype;
    /**
     * Number of dimensions, 0..8.
     */
    uint32_t ndim;
    /**
     * Extent per dimension.
     */
    uint64_t shape[TURBO_MAX_RANK];
    /**
     * Byte stride per dimension; all zero = packed.
     */
    uint64_t strides[TURBO_MAX_RANK];
    /**
     * Total bytes; 0 = computed from shape and dtype.
     */
    uint64_t bytes;
    /**
     * Extension chain for imports (`turbo_native_handle`); NULL otherwise.
     */
    const void *next;
} turbo_buffer_desc;

/**
 * Native memory handle for import and export.
 */
typedef struct turbo_native_handle {
    /**
     * `sizeof(turbo_native_handle)`.
     */
    uint32_t struct_size;
    /**
     * `TURBO_HANDLE_*`.
     */
    uint32_t kind;
    /**
     * Pointer, `cl_mem`, fd, or object handle as an integer.
     */
    uint64_t handle;
    /**
     * Kind-specific auxiliary handle (device ordinal, context).
     */
    uint64_t aux;
    /**
     * Byte offset into the native allocation.
     */
    uint64_t offset;
} turbo_native_handle;

/**
 * Model load descriptor.
 */
typedef struct turbo_model_desc {
    /**
     * `sizeof(turbo_model_desc)`.
     */
    uint32_t struct_size;
    /**
     * Number of provider options.
     */
    uint32_t n_options;
    /**
     * Provider options (unknown keys are rejected).
     */
    const struct turbo_kv *options;
    /**
     * Extension chain; NULL.
     */
    const void *next;
} turbo_model_desc;

/**
 * What actually loaded: the frozen bundle contract plus placement.
 */
typedef struct turbo_model_info {
    /**
     * `sizeof(turbo_model_info)`.
     */
    uint32_t struct_size;
    /**
     * Primary `TURBO_TASK_*`.
     */
    uint32_t task;
    /**
     * `TURBO_MODEL_*`.
     */
    uint32_t kind;
    /**
     * `TURBO_MODALITY_*`.
     */
    uint32_t modality;
    /**
     * Embedding dimension, or 0.
     */
    uint32_t dim;
    /**
     * Number of labels (classifiers), or 0.
     */
    uint32_t n_labels;
    /**
     * `TURBO_POOLING_*` from the contract, or 0.
     */
    uint32_t pooling;
    /**
     * `TURBO_NORMALIZE_*` from the contract, or 0.
     */
    uint32_t normalize;
    /**
     * Maximum sequence length in tokens.
     */
    uint32_t max_seq;
    /**
     * Maximum batch size for sessions on this model.
     */
    uint32_t max_batch;
    /**
     * Compute dtype actually used.
     */
    uint32_t dtype_used;
    /**
     * 1 if every applicable stage runs on the device.
     */
    uint32_t fully_accelerated;
    /**
     * `TURBO_STAGE_*` placement per stage index.
     */
    uint32_t stage_placement[TURBO_STAGE_COUNT];
    /**
     * Number of named inputs (RUN task).
     */
    uint32_t n_inputs;
    /**
     * Number of named outputs (RUN task).
     */
    uint32_t n_outputs;
    /**
     * Vocabulary size, or 0.
     */
    uint32_t vocab_size;
    /**
     * Model identifier from the bundle.
     */
    char model_id[128];
    /**
     * Revision from the bundle.
     */
    char revision[64];
    /**
     * Hex SHA-256 of the tokenizer file, or empty.
     */
    char tokenizer_sha256[72];
    /**
     * Provider that loaded it.
     */
    char provider_id[32];
    /**
     * Query prefix from the contract, or empty.
     */
    char prefix_query[128];
    /**
     * Document prefix from the contract, or empty.
     */
    char prefix_document[128];
} turbo_model_info;

/**
 * Named tensor description for RUN models. `shape` entries of -1 are dynamic.
 */
typedef struct turbo_tensor_info {
    /**
     * `sizeof(turbo_tensor_info)`.
     */
    uint32_t struct_size;
    /**
     * `TURBO_DTYPE_*`.
     */
    uint32_t dtype;
    /**
     * Rank.
     */
    uint32_t ndim;
    /**
     * Reserved; 0.
     */
    uint32_t reserved;
    /**
     * Extents; -1 = dynamic.
     */
    int64_t shape[TURBO_MAX_RANK];
    /**
     * Tensor name.
     */
    char name[64];
} turbo_tensor_info;

/**
 * Session creation descriptor.
 */
typedef struct turbo_session_desc {
    /**
     * `sizeof(turbo_session_desc)`.
     */
    uint32_t struct_size;
    /**
     * Maximum batch; 0 = model default.
     */
    uint32_t max_batch;
    /**
     * Maximum sequence length; 0 = model default.
     */
    uint32_t max_seq;
    /**
     * Number of provider options.
     */
    uint32_t n_options;
    /**
     * Provider options (unknown keys are rejected).
     */
    const struct turbo_kv *options;
    /**
     * Extension chain; NULL.
     */
    const void *next;
} turbo_session_desc;

/**
 * Per-call embedding options. Every field maps to a capability bit;
 * `TURBO_OPT_MODEL` (0) means "as the bundle contract says".
 */
typedef struct turbo_embed_options {
    /**
     * `sizeof(turbo_embed_options)`.
     */
    uint32_t struct_size;
    /**
     * `TURBO_TRUNCATE_*`.
     */
    uint32_t truncate;
    /**
     * Token budget; 0 = model.
     */
    uint32_t max_tokens;
    /**
     * `TURBO_PROMPT_*`.
     */
    uint32_t prompt_role;
    /**
     * `TURBO_NORMALIZE_*`.
     */
    uint32_t normalize;
    /**
     * `TURBO_POOLING_*`.
     */
    uint32_t pooling;
    /**
     * Output dimension (Matryoshka); 0 = model.
     */
    uint32_t output_dim;
    /**
     * `TURBO_OUTPUT_*`.
     */
    uint32_t output_dtype;
} turbo_embed_options;

/**
 * Per-call rerank options.
 */
typedef struct turbo_rerank_options {
    /**
     * `sizeof(turbo_rerank_options)`.
     */
    uint32_t struct_size;
    /**
     * `TURBO_TRUNCATE_*`.
     */
    uint32_t truncate;
    /**
     * Token budget per pair; 0 = model.
     */
    uint32_t max_tokens;
    /**
     * Return only the best `top_n` (0 = all).
     */
    uint32_t top_n;
    /**
     * 1 = also produce the sorted index output.
     */
    uint32_t return_sorted;
    /**
     * 1 = raw logits instead of sigmoid scores. Gated by `TURBO_CAP_OPT_RAW_SCORES`.
     */
    uint32_t raw_scores;
} turbo_rerank_options;

/**
 * Per-call classification options.
 */
typedef struct turbo_classify_options {
    /**
     * `sizeof(turbo_classify_options)`.
     */
    uint32_t struct_size;
    /**
     * `TURBO_TRUNCATE_*`.
     */
    uint32_t truncate;
    /**
     * Token budget; 0 = model.
     */
    uint32_t max_tokens;
    /**
     * `TURBO_AGGREGATE_*` (token classification only).
     */
    uint32_t aggregation;
    /**
     * 1 = raw logits instead of activated scores. Gated by `TURBO_CAP_OPT_RAW_SCORES`.
     */
    uint32_t raw_scores;
    /**
     * Reserved; 0.
     */
    uint32_t reserved;
} turbo_classify_options;

/**
 * Per-call RUN options: the KServe per-request parameters map.
 */
typedef struct turbo_run_options {
    /**
     * `sizeof(turbo_run_options)`.
     */
    uint32_t struct_size;
    /**
     * Number of parameters.
     */
    uint32_t n_params;
    /**
     * Parameters.
     */
    const struct turbo_kv *params;
} turbo_run_options;

/**
 * Caller-prepared token batch. Row-major `[batch, seq]` i32 arrays;
 * `row_stride` is in elements (0 = `seq`). `types` may be NULL (all zero).
 */
typedef struct turbo_token_batch {
    /**
     * `sizeof(turbo_token_batch)`.
     */
    uint32_t struct_size;
    /**
     * Rows.
     */
    uint32_t batch;
    /**
     * Columns.
     */
    uint32_t seq;
    /**
     * Elements between row starts; 0 = `seq`.
     */
    uint32_t row_stride;
    /**
     * Token ids.
     */
    const int32_t *ids;
    /**
     * Attention mask (0/1).
     */
    const int32_t *mask;
    /**
     * Token type ids, or NULL.
     */
    const int32_t *types;
} turbo_token_batch;

/**
 * Session byte and allocation counters. Adapter-level only; provider
 * internals are reported separately by the provider where available.
 */
typedef struct turbo_session_stats {
    /**
     * `sizeof(turbo_session_stats)`.
     */
    uint32_t struct_size;
    /**
     * Reserved; 0.
     */
    uint32_t reserved;
    /**
     * Completed runs.
     */
    uint64_t runs;
    /**
     * Host heap allocations made by the adapter on the run path since
     * warmup, or `UINT64_MAX` when the adapter does not count them.
     */
    uint64_t host_allocs;
    /**
     * Explicit host-to-device bytes.
     */
    uint64_t h2d_bytes;
    /**
     * Explicit device-to-host bytes.
     */
    uint64_t d2h_bytes;
    /**
     * Bytes of bound input storage.
     */
    uint64_t input_bytes;
    /**
     * Bytes of bound output storage.
     */
    uint64_t output_bytes;
    /**
     * Provider-internal allocations on the run path, or `UINT64_MAX` if unknown.
     */
    uint64_t provider_allocs;
} turbo_session_stats;

/**
 * Result summary. `n_outputs` is 1 for embeddings and scores; classifiers
 * and RUN models may have several.
 */
typedef struct turbo_result_info {
    /**
     * `sizeof(turbo_result_info)`.
     */
    uint32_t struct_size;
    /**
     * Number of output tensors.
     */
    uint32_t n_outputs;
    /**
     * Rows in output 0.
     */
    uint32_t batch;
    /**
     * Columns in output 0 (dimension, labels, or 1 for scores).
     */
    uint32_t dim;
    /**
     * `TURBO_DTYPE_*` of output 0.
     */
    uint32_t dtype;
    /**
     * `TURBO_PLACE_*` of output 0.
     */
    uint32_t placement;
    /**
     * Bytes in output 0.
     */
    uint64_t bytes;
} turbo_result_info;

/**
 * One aggregated span from token classification.
 */
typedef struct turbo_span {
    /**
     * Byte offset of the span start in the original input row.
     */
    uint64_t byte_start;
    /**
     * Byte offset one past the span end.
     */
    uint64_t byte_end;
    /**
     * Input row.
     */
    uint32_t row;
    /**
     * Label index into the bundle's label list.
     */
    uint32_t label;
    /**
     * Score.
     */
    float score;
    /**
     * Reserved; 0.
     */
    uint32_t reserved;
} turbo_span;

/**
 * One chat message for template application.
 */
typedef struct turbo_message {
    /**
     * Role (`system`, `user`, `assistant`, `tool`).
     */
    struct turbo_text role;
    /**
     * Content.
     */
    struct turbo_text content;
} turbo_message;

/**
 * Logit bias entry.
 */
typedef struct turbo_logit_bias {
    /**
     * Token id.
     */
    int32_t token;
    /**
     * Additive bias.
     */
    float bias;
} turbo_logit_bias;

/**
 * Generation descriptor. Capability-gated fields are marked; an unsupported
 * non-zero field fails with `TURBO_E_UNSUPPORTED_OPTION` naming it.
 */
typedef struct turbo_generate_desc {
    /**
     * `sizeof(turbo_generate_desc)`.
     */
    uint32_t struct_size;
    /**
     * Maximum new tokens; 0 = model default.
     */
    uint32_t max_new_tokens;
    /**
     * Minimum new tokens before EOS is allowed. Gated by `TURBO_CAP_OPT_GEN_MIN_TOKENS`.
     */
    uint32_t min_new_tokens;
    /**
     * Sequences to generate; 0 or 1 = one. Gated by `TURBO_CAP_OPT_GEN_N`.
     */
    uint32_t n_sequences;
    /**
     * Sampling temperature; 0 = greedy. Gated by `TURBO_CAP_OPT_GEN_SAMPLING`.
     */
    float temperature;
    /**
     * Top-k; 0 = off. Gated by `TURBO_CAP_OPT_GEN_SAMPLING`.
     */
    uint32_t top_k;
    /**
     * Top-p; 0 or 1 = off. Gated by `TURBO_CAP_OPT_GEN_SAMPLING`.
     */
    float top_p;
    /**
     * Min-p; 0 = off. Gated by `TURBO_CAP_OPT_GEN_SAMPLING`.
     */
    float min_p;
    /**
     * Repeat penalty; 0 or 1 = off. Gated by `TURBO_CAP_OPT_GEN_PENALTIES`.
     */
    float repeat_penalty;
    /**
     * Presence penalty; 0 = off. Gated.
     */
    float presence_penalty;
    /**
     * Frequency penalty; 0 = off. Gated.
     */
    float frequency_penalty;
    /**
     * 1 = use `seed`. Gated by `TURBO_CAP_OPT_GEN_SEED`.
     */
    uint32_t has_seed;
    /**
     * Random seed.
     */
    uint64_t seed;
    /**
     * Number of stop strings. Gated by `TURBO_CAP_OPT_GEN_STOP_STRINGS`.
     */
    uint32_t n_stop;
    /**
     * Number of stop token ids. Gated by `TURBO_CAP_OPT_GEN_STOP_TOKENS`.
     */
    uint32_t n_stop_tokens;
    /**
     * Stop strings.
     */
    const struct turbo_text *stop;
    /**
     * Stop token ids.
     */
    const int32_t *stop_tokens;
    /**
     * Number of logit bias entries. Gated by `TURBO_CAP_OPT_GEN_LOGIT_BIAS`.
     */
    uint32_t n_logit_bias;
    /**
     * Top logprobs per token to return; 0 = none. Gated by `TURBO_CAP_OPT_GEN_LOGPROBS`.
     */
    uint32_t logprobs;
    /**
     * Logit bias entries.
     */
    const struct turbo_logit_bias *logit_bias;
    /**
     * `TURBO_STRUCTURED_*`. Gated by `TURBO_CAP_OPT_GEN_STRUCTURED`.
     */
    uint32_t structured_kind;
    /**
     * 1 = include the prompt in the output text. Gated by `TURBO_CAP_OPT_GEN_ECHO`.
     */
    uint32_t echo;
    /**
     * Schema or grammar text.
     */
    struct turbo_text structured;
    /**
     * Number of tool definitions (JSON). Gated by `TURBO_CAP_OPT_GEN_TOOLS`.
     */
    uint32_t n_tools;
    /**
     * Number of provider options.
     */
    uint32_t n_options;
    /**
     * Tool definitions.
     */
    const struct turbo_text *tools;
    /**
     * Provider options (unknown keys are rejected).
     */
    const struct turbo_kv *options;
} turbo_generate_desc;

/**
 * One step of generation. Pointers are valid until the next `step`, `cancel`, or `release`.
 */
typedef struct turbo_generation_chunk {
    /**
     * `sizeof(turbo_generation_chunk)`.
     */
    uint32_t struct_size;
    /**
     * Sequence index (0 unless `n_sequences > 1`).
     */
    uint32_t sequence;
    /**
     * Number of new token ids in this chunk.
     */
    uint32_t n_tokens;
    /**
     * Number of logprob entries (`n_tokens * logprobs`).
     */
    uint32_t n_logprobs;
    /**
     * New token ids.
     */
    const int32_t *tokens;
    /**
     * Decoded text for the new tokens (may be empty mid-codepoint).
     */
    struct turbo_text text;
    /**
     * Logprobs, or NULL.
     */
    const float *logprobs;
    /**
     * 1 when this sequence is finished.
     */
    uint32_t done;
    /**
     * `TURBO_FINISH_*` when `done`.
     */
    uint32_t finish_reason;
    /**
     * Prompt tokens consumed (reported on the first chunk).
     */
    uint32_t prompt_tokens;
    /**
     * Total generated tokens so far in this sequence.
     */
    uint32_t generated_tokens;
} turbo_generation_chunk;

/**
 * Push-generation callback. Return `TURBO_STREAM_CONTINUE` or `TURBO_STREAM_STOP`.
 */
typedef uint32_t (*turbo_stream_fn)(void *user_data,
                                    const struct turbo_generation_chunk *chunk);

/**
 * Tokenizer encode options.
 */
typedef struct turbo_encode_options {
    /**
     * `sizeof(turbo_encode_options)`.
     */
    uint32_t struct_size;
    /**
     * 1 = add special tokens (default when the whole struct is NULL).
     */
    uint32_t add_special_tokens;
    /**
     * `TURBO_TRUNCATE_*`.
     */
    uint32_t truncate;
    /**
     * Token budget including specials; 0 = model max.
     */
    uint32_t max_tokens;
    /**
     * Pad every row to this many tokens; 0 = no padding.
     */
    uint32_t pad_to;
    /**
     * `TURBO_PROMPT_*`.
     */
    uint32_t prompt_role;
} turbo_encode_options;

/**
 * Static facts about a tokenizer.
 */
typedef struct turbo_tokenizer_info {
    /**
     * `sizeof(turbo_tokenizer_info)`.
     */
    uint32_t struct_size;
    /**
     * Vocabulary size including added tokens.
     */
    uint32_t vocab_size;
    /**
     * Bundle `max_seq`.
     */
    uint32_t max_seq;
    /**
     * Special tokens added to one sequence.
     */
    uint32_t specials_per_sequence;
    /**
     * Pad id, or -1.
     */
    int32_t pad_id;
    /**
     * Beginning-of-sequence / `[CLS]` id, or -1.
     */
    int32_t bos_id;
    /**
     * End-of-sequence / `[SEP]` id, or -1.
     */
    int32_t eos_id;
    /**
     * Unknown-token id, or -1.
     */
    int32_t unk_id;
    /**
     * Tokenizer kind (`wordpiece`, `bpe`, `unigram`, ...).
     */
    char kind[32];
    /**
     * Hex SHA-256 of the tokenizer file, or empty.
     */
    char sha256[72];
} turbo_tokenizer_info;

/**
 * Chunk planner configuration.
 */
typedef struct turbo_chunk_desc {
    /**
     * `sizeof(turbo_chunk_desc)`.
     */
    uint32_t struct_size;
    /**
     * Model sequence capacity.
     */
    uint32_t max_tokens;
    /**
     * Tokens held back for specials and prefixes.
     */
    uint32_t reserved_tokens;
    /**
     * Upper bound on shared tokens between consecutive chunks of one paragraph.
     */
    uint32_t overlap_tokens;
} turbo_chunk_desc;

/**
 * One planned chunk: half-open byte range into the original text.
 */
typedef struct turbo_chunk {
    /**
     * Byte offset of the chunk start.
     */
    uint64_t byte_start;
    /**
     * Byte offset one past the end.
     */
    uint64_t byte_end;
    /**
     * Paragraph index.
     */
    uint32_t paragraph;
    /**
     * Content tokens in the chunk under the supplied tokenizer.
     */
    uint32_t n_tokens;
} turbo_chunk;

#endif  /* TURBO_TYPES_H */
