/* SPDX-License-Identifier: Apache-2.0
 *
 * Turbo provider plugin ABI. A provider library exports
 *
 *     const turbo_provider_vtbl *turbo_provider_get(uint32_t core_abi_version);
 *
 * returning a pointer to a static vtable, or NULL if it cannot serve that
 * ABI version. See the field documentation for ownership rules. Provider
 * functions must never unwind or throw across this boundary.
 */

#ifndef TURBO_PROVIDER_H
#define TURBO_PROVIDER_H

/* Generated by cbindgen from crates/turbo-abi/src/provider.rs. Do not edit; run scripts/gen-header.sh. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include <stddef.h>
#include <stdint.h>
#include <stdbool.h>
#include "turbo_types.h"

/**
 * Success.
 */
#define TURBO_OK 0

/**
 * A caller argument is invalid; `turbo_error.field` may name it.
 */
#define TURBO_E_INVALID_ARGUMENT 256

/**
 * A descriptor's `struct_size` is not one this library understands.
 */
#define TURBO_E_INVALID_STRUCT_SIZE 257

/**
 * A text view is not valid UTF-8.
 */
#define TURBO_E_INVALID_UTF8 258

/**
 * A handle is null or of the wrong kind.
 */
#define TURBO_E_INVALID_HANDLE 259

/**
 * A shape, stride, or byte count is inconsistent or overflows.
 */
#define TURBO_E_INVALID_SHAPE 260

/**
 * The operation is not valid in the handle's current state (for example
 * `run` before any input was written, or use after cancel).
 */
#define TURBO_E_INVALID_STATE 261

/**
 * A constant (dtype, task, option value) is outside the known set.
 */
#define TURBO_E_INVALID_ENUM 262

/**
 * The requested combination is unsupported here; see `message`.
 */
#define TURBO_E_UNSUPPORTED 512

/**
 * An option field is not honored by this provider for this model;
 * `turbo_error.field` is the 1-based field index in the options struct.
 */
#define TURBO_E_UNSUPPORTED_OPTION 513

/**
 * The task is not offered on this device for this model.
 */
#define TURBO_E_UNSUPPORTED_TASK 514

/**
 * The dtype is not supported in the requested placement.
 */
#define TURBO_E_UNSUPPORTED_DTYPE 515

/**
 * The placement is not supported by this device.
 */
#define TURBO_E_UNSUPPORTED_PLACEMENT 516

/**
 * Declared in the header but not implemented in this build. Never a silent fallback.
 */
#define TURBO_E_NOT_IMPLEMENTED 517

/**
 * The modality is not offered on this device for this model.
 */
#define TURBO_E_UNSUPPORTED_MODALITY 518

/**
 * Allocation failed.
 */
#define TURBO_E_OUT_OF_MEMORY 768

/**
 * The session or generation has an operation or result lease in flight.
 */
#define TURBO_E_BUSY 769

/**
 * The provider is refusing new work; retry later.
 */
#define TURBO_E_OVERLOADED 770

/**
 * The request exceeds a declared capacity (batch, sequence, output size).
 */
#define TURBO_E_CAPACITY 771

/**
 * No device matches the selector.
 */
#define TURBO_E_DEVICE_NOT_FOUND 1024

/**
 * The device exists but cannot be used (driver missing, busy, failed probe).
 */
#define TURBO_E_DEVICE_UNAVAILABLE 1025

/**
 * The vendor runtime reported an error; `message` carries its text.
 */
#define TURBO_E_RUNTIME 1026

/**
 * A provider library could not be loaded or did not export the entry point.
 */
#define TURBO_E_PROVIDER_LOAD 1027

/**
 * A provider library targets a different ABI version.
 */
#define TURBO_E_ABI_MISMATCH 1028

/**
 * The operation was cancelled by the caller.
 */
#define TURBO_E_CANCELLED 1029

/**
 * The bundle directory or a required file is missing.
 */
#define TURBO_E_BUNDLE_NOT_FOUND 1280

/**
 * The bundle manifest is malformed or declares an unknown version.
 */
#define TURBO_E_BUNDLE_INVALID 1281

/**
 * A bundle file does not match its recorded hash.
 */
#define TURBO_E_BUNDLE_INTEGRITY 1282

/**
 * The bundle is valid but no artifact in it is loadable by this provider.
 */
#define TURBO_E_BUNDLE_NO_ARTIFACT 1283

/**
 * A bug in the library or provider.
 */
#define TURBO_E_INTERNAL 1536

/**
 * A panic or exception was caught at the language boundary.
 */
#define TURBO_E_PANIC 1537

/**
 * Device kind: CPU.
 */
#define TURBO_DEVICE_CPU 1

/**
 * Device kind: discrete GPU.
 */
#define TURBO_DEVICE_GPU 2

/**
 * Device kind: integrated GPU.
 */
#define TURBO_DEVICE_IGPU 3

/**
 * Device kind: neural processing unit.
 */
#define TURBO_DEVICE_NPU 4

/**
 * Device kind: other accelerator.
 */
#define TURBO_DEVICE_ACCEL 5

/**
 * Task: dense text embedding.
 */
#define TURBO_TASK_EMBED 1

/**
 * Task: cross-encoder reranking.
 */
#define TURBO_TASK_RERANK 2

/**
 * Task: sequence classification with labels.
 */
#define TURBO_TASK_CLASSIFY 3

/**
 * Task: per-token classification with span aggregation.
 */
#define TURBO_TASK_TOKEN_CLASSIFY 4

/**
 * Task: causal generation.
 */
#define TURBO_TASK_GENERATE 5

/**
 * Task: tokenize / detokenize.
 */
#define TURBO_TASK_TOKENIZE 6

/**
 * Task: generic named-tensor execution.
 */
#define TURBO_TASK_RUN 7

/**
 * Task: source chunking (host utility).
 */
#define TURBO_TASK_CHUNK 8

/**
 * Modality: text.
 */
#define TURBO_MODALITY_TEXT 1

/**
 * Modality: audio.
 */
#define TURBO_MODALITY_AUDIO 2

/**
 * Modality: image.
 */
#define TURBO_MODALITY_IMAGE 3

/**
 * Modality: video.
 */
#define TURBO_MODALITY_VIDEO 4

/**
 * Capability status: not offered.
 */
#define TURBO_CAP_UNSUPPORTED 0

/**
 * Capability status: planned, code path may exist but is not qualified.
 */
#define TURBO_CAP_PLANNED 1

/**
 * Capability status: works, not yet qualified with receipts.
 */
#define TURBO_CAP_EXPERIMENTAL 2

/**
 * Capability status: qualified with conformance, precision, and benchmark receipts.
 */
#define TURBO_CAP_SUPPORTED 3

/**
 * Model kind: embedder.
 */
#define TURBO_MODEL_EMBEDDING 1

/**
 * Model kind: cross-encoder reranker.
 */
#define TURBO_MODEL_RERANKER 2

/**
 * Model kind: sequence classifier.
 */
#define TURBO_MODEL_CLASSIFIER 3

/**
 * Model kind: token classifier.
 */
#define TURBO_MODEL_TOKEN_CLASSIFIER 4

/**
 * Model kind: generative language model.
 */
#define TURBO_MODEL_GENERATIVE 5

/**
 * Model kind: generic graph with named inputs and outputs.
 */
#define TURBO_MODEL_GENERIC 6

/**
 * Element type: boolean (one byte).
 */
#define TURBO_DTYPE_BOOL 1

/**
 * Element type: unsigned 8-bit.
 */
#define TURBO_DTYPE_U8 2

/**
 * Element type: unsigned 16-bit.
 */
#define TURBO_DTYPE_U16 3

/**
 * Element type: unsigned 32-bit.
 */
#define TURBO_DTYPE_U32 4

/**
 * Element type: unsigned 64-bit.
 */
#define TURBO_DTYPE_U64 5

/**
 * Element type: signed 8-bit.
 */
#define TURBO_DTYPE_I8 6

/**
 * Element type: signed 16-bit.
 */
#define TURBO_DTYPE_I16 7

/**
 * Element type: signed 32-bit.
 */
#define TURBO_DTYPE_I32 8

/**
 * Element type: signed 64-bit.
 */
#define TURBO_DTYPE_I64 9

/**
 * Element type: IEEE half.
 */
#define TURBO_DTYPE_F16 10

/**
 * Element type: bfloat16.
 */
#define TURBO_DTYPE_BF16 11

/**
 * Element type: IEEE single.
 */
#define TURBO_DTYPE_F32 12

/**
 * Element type: IEEE double.
 */
#define TURBO_DTYPE_F64 13

/**
 * Element type: length-prefixed byte strings (KServe BYTES): each element is
 * a little-endian `uint32_t` length followed by that many bytes.
 */
#define TURBO_DTYPE_BYTES 14

/**
 * Placement: pageable host memory.
 */
#define TURBO_PLACE_HOST 1

/**
 * Placement: page-locked host memory visible to the device.
 */
#define TURBO_PLACE_PINNED 2

/**
 * Placement: device memory.
 */
#define TURBO_PLACE_DEVICE 3

/**
 * Placement: memory shared between host and device (unified / USM shared).
 */
#define TURBO_PLACE_SHARED 4

/**
 * Device selection policy: the host's best accelerator; never CPU.
 */
#define TURBO_SELECT_AUTO 0

/**
 * Device selection policy: exactly the device the selector names.
 */
#define TURBO_SELECT_EXPLICIT 1

/**
 * Pipeline stage index: tokenization.
 */
#define TURBO_STAGE_TOKENIZE 0

/**
 * Pipeline stage index: encoder / model forward.
 */
#define TURBO_STAGE_ENCODE 1

/**
 * Pipeline stage index: pooling.
 */
#define TURBO_STAGE_POOL 2

/**
 * Pipeline stage index: normalization.
 */
#define TURBO_STAGE_NORMALIZE 3

/**
 * Pipeline stage index: post-processing (softmax, aggregation, sampling).
 */
#define TURBO_STAGE_POSTPROCESS 4

/**
 * Number of pipeline stages reported.
 */
#define TURBO_STAGE_COUNT 5

/**
 * Stage placement: the stage does not apply to this model.
 */
#define TURBO_STAGE_UNUSED 0

/**
 * Stage placement: runs on the host.
 */
#define TURBO_STAGE_HOST 1

/**
 * Stage placement: runs on the device as a separate step.
 */
#define TURBO_STAGE_DEVICE 2

/**
 * Stage placement: fused into the device graph with adjacent stages.
 */
#define TURBO_STAGE_FUSED 3

/**
 * Option value meaning "use the model contract".
 */
#define TURBO_OPT_MODEL 0

/**
 * Truncation: as the model contract says (`TURBO_OPT_MODEL`). The bundle
 * contract carries no truncation field today, so every text provider
 * resolves MODEL to RIGHT (the BERT convention: keep the head of the
 * text); a provider that resolved it differently would say so in its
 * README and its capability notes.
 */
#define TURBO_TRUNCATE_MODEL 0

/**
 * Truncation: never; over-length input is an error.
 */
#define TURBO_TRUNCATE_NONE 1

/**
 * Truncation: drop tokens from the end.
 */
#define TURBO_TRUNCATE_RIGHT 2

/**
 * Truncation: drop tokens from the start.
 */
#define TURBO_TRUNCATE_LEFT 3

/**
 * Prompt role: no prefix.
 */
#define TURBO_PROMPT_NONE 0

/**
 * Prompt role: apply the bundle's query prefix.
 */
#define TURBO_PROMPT_QUERY 1

/**
 * Prompt role: apply the bundle's document prefix.
 */
#define TURBO_PROMPT_DOCUMENT 2

/**
 * Normalization: as the model contract says.
 */
#define TURBO_NORMALIZE_MODEL 0

/**
 * Normalization: none.
 */
#define TURBO_NORMALIZE_NONE 1

/**
 * Normalization: L2.
 */
#define TURBO_NORMALIZE_L2 2

/**
 * Pooling: as the model contract says.
 */
#define TURBO_POOLING_MODEL 0

/**
 * Pooling: masked mean.
 */
#define TURBO_POOLING_MEAN 1

/**
 * Pooling: first token.
 */
#define TURBO_POOLING_CLS 2

/**
 * Pooling: last non-padding token.
 */
#define TURBO_POOLING_LAST 3

/**
 * Output dtype: as the model contract says.
 */
#define TURBO_OUTPUT_MODEL 0

/**
 * Output dtype: FP32.
 */
#define TURBO_OUTPUT_F32 1

/**
 * Output dtype: FP16.
 */
#define TURBO_OUTPUT_F16 2

/**
 * Output dtype: int8 quantized.
 */
#define TURBO_OUTPUT_I8 3

/**
 * Token-classification aggregation: as the model contract says.
 */
#define TURBO_AGGREGATE_MODEL 0

/**
 * Token-classification aggregation: none, per-token labels only.
 */
#define TURBO_AGGREGATE_NONE 1

/**
 * Token-classification aggregation: merge consecutive same-label tokens.
 */
#define TURBO_AGGREGATE_SIMPLE 2

/**
 * Token-classification aggregation: label of the first sub-token wins.
 */
#define TURBO_AGGREGATE_FIRST 3

/**
 * Token-classification aggregation: highest-scoring sub-token wins.
 */
#define TURBO_AGGREGATE_MAX 4

/**
 * Generation finish reason: not finished.
 */
#define TURBO_FINISH_NONE 0

/**
 * Generation finish reason: end-of-sequence token.
 */
#define TURBO_FINISH_EOS 1

/**
 * Generation finish reason: a stop string or stop token matched.
 */
#define TURBO_FINISH_STOP 2

/**
 * Generation finish reason: `max_new_tokens` reached.
 */
#define TURBO_FINISH_LENGTH 3

/**
 * Generation finish reason: cancelled by the caller.
 */
#define TURBO_FINISH_CANCELLED 4

/**
 * Structured output: none.
 */
#define TURBO_STRUCTURED_NONE 0

/**
 * Structured output: constrain to a JSON schema (text is the schema).
 */
#define TURBO_STRUCTURED_JSON_SCHEMA 1

/**
 * Structured output: constrain to a grammar (text is GBNF).
 */
#define TURBO_STRUCTURED_GRAMMAR 2

/**
 * Push-generation callback return: keep generating.
 */
#define TURBO_STREAM_CONTINUE 0

/**
 * Push-generation callback return: stop after this chunk.
 */
#define TURBO_STREAM_STOP 1

/**
 * Native handle kind: host pointer.
 */
#define TURBO_HANDLE_HOST_PTR 1

/**
 * Native handle kind: CUDA device pointer (`aux` = device ordinal).
 */
#define TURBO_HANDLE_CUDA_PTR 2

/**
 * Native handle kind: OpenCL `cl_mem` (`aux` = `cl_context`).
 */
#define TURBO_HANDLE_CL_MEM 3

/**
 * Native handle kind: Level Zero USM pointer (`aux` = `ze_context_handle_t`).
 */
#define TURBO_HANDLE_ZE_USM 4

/**
 * Native handle kind: Metal `MTLBuffer` (`aux` = `MTLDevice`).
 */
#define TURBO_HANDLE_MTL_BUFFER 5

/**
 * Native handle kind: Linux DMA-BUF file descriptor.
 */
#define TURBO_HANDLE_DMABUF_FD 6

/**
 * I/O direction: model input.
 */
#define TURBO_IO_INPUT 1

/**
 * I/O direction: model output.
 */
#define TURBO_IO_OUTPUT 2

/**
 * Runtime flag: do not scan the default provider search path.
 */
#define TURBO_RUNTIME_NO_DEFAULT_PROVIDERS (1 << 0)

/**
 * The device can execute asynchronously (`turbo_session_submit` + fences).
 */
#define TURBO_CAP_ASYNC 1

/**
 * Caller host memory can be imported without a copy.
 */
#define TURBO_CAP_HOST_PTR_IMPORT 2

/**
 * Results can stay resident on the device and be exported.
 */
#define TURBO_CAP_DEVICE_RESULT 4

/**
 * A caller-owned queue/stream can be imported.
 */
#define TURBO_CAP_EXTERNAL_QUEUE 8

/**
 * DMA-BUF import.
 */
#define TURBO_CAP_DMABUF 16

/**
 * Host and device share one address space (unified / USM shared).
 */
#define TURBO_CAP_UNIFIED_MEMORY 32

/**
 * Sessions may run any shape up to their maximum without recompiling.
 */
#define TURBO_CAP_DYNAMIC_SHAPE 64

/**
 * Sessions on one model share weights.
 */
#define TURBO_CAP_WEIGHT_SHARING 128

/**
 * Tokenization runs on the device from raw UTF-8.
 */
#define TURBO_CAP_DEVICE_TOKENIZE 256

/**
 * Post-processing (softmax, aggregation) runs on the device.
 */
#define TURBO_CAP_DEVICE_POSTPROCESS 512

/**
 * Deterministic results across runs for the same inputs and seed.
 */
#define TURBO_CAP_DETERMINISTIC 1024

/**
 * Option `truncate` is honored.
 */
#define TURBO_CAP_OPT_TRUNCATE 65536

/**
 * Option `max_tokens` is honored.
 */
#define TURBO_CAP_OPT_MAX_TOKENS 131072

/**
 * Option `prompt_role` is honored.
 */
#define TURBO_CAP_OPT_PROMPT_ROLE 262144

/**
 * Option `normalize` may differ from the model contract.
 */
#define TURBO_CAP_OPT_NORMALIZE 524288

/**
 * Option `pooling` may differ from the model contract.
 */
#define TURBO_CAP_OPT_POOLING_OVERRIDE 1048576

/**
 * Option `output_dim` (Matryoshka truncation) is honored.
 */
#define TURBO_CAP_OPT_OUTPUT_DIM 2097152

/**
 * Option `output_dtype` is honored.
 */
#define TURBO_CAP_OPT_OUTPUT_DTYPE 4194304

/**
 * Rerank `top_n` and sorted output are computed by the provider.
 */
#define TURBO_CAP_OPT_TOP_N 8388608

/**
 * Token-classification `aggregation` may differ from the model contract.
 */
#define TURBO_CAP_OPT_AGGREGATION 16777216

/**
 * Rerank and classify `raw_scores` (logits instead of activated scores) is honored.
 */
#define TURBO_CAP_OPT_RAW_SCORES 33554432

/**
 * Generation: structured output (JSON schema / grammar).
 */
#define TURBO_CAP_OPT_GEN_STRUCTURED 4294967296

/**
 * Generation: tool definitions in the prompt template.
 */
#define TURBO_CAP_OPT_GEN_TOOLS 8589934592

/**
 * Generation: `n_sequences > 1`.
 */
#define TURBO_CAP_OPT_GEN_N 17179869184

/**
 * Generation: `logit_bias`.
 */
#define TURBO_CAP_OPT_GEN_LOGIT_BIAS 34359738368

/**
 * Generation: presence / frequency / repeat penalties.
 */
#define TURBO_CAP_OPT_GEN_PENALTIES 68719476736

/**
 * Generation: per-token logprobs.
 */
#define TURBO_CAP_OPT_GEN_LOGPROBS 137438953472

/**
 * Generation: stop strings (as opposed to stop token ids only).
 */
#define TURBO_CAP_OPT_GEN_STOP_STRINGS 274877906944

/**
 * Generation: `seed` is honored (implies reproducible sampling).
 */
#define TURBO_CAP_OPT_GEN_SEED 549755813888

/**
 * Generation: sampling controls `temperature`, `top_k`, `top_p`, `min_p`.
 */
#define TURBO_CAP_OPT_GEN_SAMPLING 1099511627776

/**
 * Generation: `min_new_tokens`.
 */
#define TURBO_CAP_OPT_GEN_MIN_TOKENS 2199023255552

/**
 * Generation: `echo` (the prompt is included in the output text).
 */
#define TURBO_CAP_OPT_GEN_ECHO 4398046511104

/**
 * Generation: stop token ids.
 */
#define TURBO_CAP_OPT_GEN_STOP_TOKENS 8796093022208

/**
 * Length of `turbo_error.message` including the terminating NUL.
 */
#define TURBO_ERROR_MESSAGE_LEN 496

/**
 * Maximum tensor rank.
 */
#define TURBO_MAX_RANK 8

/**
 * Provider ABI version. Equals the public ABI version; bumped together
 * (a test asserts this).
 */
#define TURBO_PROVIDER_ABI_VERSION 2

/**
 * A buffer the provider allocated or imported.
 */
typedef struct turbo_provider_buffer {
    /**
     * `sizeof(turbo_provider_buffer)`.
     */
    uint32_t struct_size;
    /**
     * Reserved; 0.
     */
    uint32_t reserved;
    /**
     * Provider handle, passed to `buffer_read`, `buffer_export`, `buffer_release`.
     */
    void *handle;
    /**
     * Stable host pointer for host-visible placements, else NULL.
     */
    void *host_ptr;
    /**
     * Description as allocated (placement, dtype, shape, strides, bytes).
     */
    turbo_buffer_desc desc;
} turbo_provider_buffer;

/**
 * One output of a run, borrowed from the session.
 */
typedef struct turbo_provider_output {
    /**
     * `sizeof(turbo_provider_output)`.
     */
    uint32_t struct_size;
    /**
     * Rank of the logical shape.
     */
    uint32_t ndim;
    /**
     * Output name, valid for the session's lifetime.
     */
    turbo_text name;
    /**
     * The backing buffer (capacity may exceed the logical shape).
     */
    struct turbo_provider_buffer buffer;
    /**
     * Logical shape.
     */
    uint64_t shape[TURBO_MAX_RANK];
} turbo_provider_output;

/**
 * Result of `session_run`. Arrays are borrowed until the next run or release.
 */
typedef struct turbo_provider_result {
    /**
     * `sizeof(turbo_provider_result)`.
     */
    uint32_t struct_size;
    /**
     * Number of outputs (at least 1 on success).
     */
    uint32_t n_outputs;
    /**
     * Outputs; output 0 is primary.
     */
    const struct turbo_provider_output *outputs;
    /**
     * Number of spans (token classification).
     */
    uint32_t n_spans;
    /**
     * Reserved; 0.
     */
    uint32_t reserved;
    /**
     * Spans.
     */
    const turbo_span *spans;
} turbo_provider_result;

/**
 * The provider vtable. All function pointers except those documented as
 * optional must be non-NULL; the core rejects a vtable with a NULL required
 * entry at load time with `TURBO_E_PROVIDER_LOAD`.
 */
typedef struct turbo_provider_vtbl {
    /**
     * `sizeof(turbo_provider_vtbl)`.
     */
    uint32_t struct_size;
    /**
     * Must equal `TURBO_PROVIDER_ABI_VERSION`.
     */
    uint32_t abi_version;
    /**
     * Stable provider id, NUL-terminated (`cuda`, `openvino`, `metal`, `hailo`, `ggml`, `static`, `mock`).
     */
    const char *id;
    /**
     * Provider version, NUL-terminated.
     */
    const char *version;
    /**
     * Provider-global state passed to the provider-level functions.
     */
    void *state;
    /**
     * Number of devices this provider offers.
     */
    int32_t (*device_count)(void *state,
                            uint32_t *out,
                            turbo_error *err);
    /**
     * Static device info for an ordinal.
     */
    int32_t (*device_info)(void *state,
                           uint32_t ordinal,
                           turbo_device_info *out,
                           turbo_error *err);
    /**
     * Capability cell.
     */
    int32_t (*capability)(void *state,
                          uint32_t ordinal,
                          uint32_t task,
                          uint32_t modality,
                          turbo_capability *out,
                          turbo_error *err);
    /**
     * Per-request feasibility for a bundle directory.
     */
    int32_t (*can_run)(void *state,
                       uint32_t ordinal,
                       turbo_text bundle_dir,
                       uint32_t task,
                       uint32_t modality,
                       turbo_error *err);
    /**
     * Create a context on a device.
     */
    int32_t (*context_create)(void *state,
                              uint32_t ordinal,
                              const turbo_context_desc *desc,
                              void **out,
                              turbo_error *err);
    /**
     * Release a context (all its models and buffers are already released).
     */
    void (*context_release)(void *ctx);
    /**
     * Allocate a buffer.
     */
    int32_t (*buffer_alloc)(void *ctx,
                            const turbo_buffer_desc *desc,
                            struct turbo_provider_buffer *out,
                            turbo_error *err);
    /**
     * Import caller memory. Optional; NULL means unsupported.
     */
    int32_t (*buffer_import)(void *ctx,
                             const turbo_buffer_desc *desc,
                             const turbo_native_handle *handle,
                             struct turbo_provider_buffer *out,
                             turbo_error *err);
    /**
     * Blocking copy of the whole buffer to host memory of `bytes` bytes (must equal `desc.bytes`).
     */
    int32_t (*buffer_read)(void *buffer,
                           void *dst,
                           uint64_t bytes,
                           turbo_error *err);
    /**
     * Export a native handle. Optional.
     */
    int32_t (*buffer_export)(void *buffer,
                             uint32_t kind,
                             turbo_native_handle *out,
                             turbo_error *err);
    /**
     * Release a buffer obtained from `buffer_alloc` or `buffer_import`.
     */
    void (*buffer_release)(void *buffer);
    /**
     * Load a verified bundle. The core has already verified hashes and
     * checked the capability cell; the provider re-reads what it needs.
     */
    int32_t (*model_load)(void *ctx,
                          turbo_text bundle_dir,
                          const turbo_model_desc *desc,
                          void **out,
                          turbo_error *err);
    /**
     * What loaded.
     */
    int32_t (*model_info)(void *model,
                          turbo_model_info *out,
                          turbo_error *err);
    /**
     * Label by index (classifiers). The view is valid for the model's lifetime.
     */
    int32_t (*model_label)(void *model,
                           uint32_t index,
                           turbo_text *out,
                           turbo_error *err);
    /**
     * Named tensor info (RUN). Optional when the provider loads no generic models.
     */
    int32_t (*model_io_info)(void *model,
                             uint32_t direction,
                             uint32_t index,
                             turbo_tensor_info *out,
                             turbo_error *err);
    /**
     * Release a model.
     */
    void (*model_release)(void *model);
    /**
     * Create a session. `desc` maxima are already resolved and validated.
     */
    int32_t (*session_create)(void *model,
                              const turbo_session_desc *desc,
                              void **out,
                              turbo_error *err);
    /**
     * Write texts for embedding. Options are already validated by the core.
     */
    int32_t (*session_write_text)(void *session,
                                  const turbo_text *texts,
                                  uint32_t count,
                                  const turbo_embed_options *opts,
                                  turbo_error *err);
    /**
     * Write prepared tokens (already validated).
     */
    int32_t (*session_write_tokens)(void *session,
                                    const turbo_token_batch *batch,
                                    turbo_error *err);
    /**
     * Write a query and documents.
     */
    int32_t (*session_write_pairs)(void *session,
                                   const turbo_text *query,
                                   const turbo_text *docs,
                                   uint32_t count,
                                   const turbo_rerank_options *opts,
                                   turbo_error *err);
    /**
     * Write texts for classification.
     */
    int32_t (*session_write_text_classify)(void *session,
                                           const turbo_text *texts,
                                           uint32_t count,
                                           const turbo_classify_options *opts,
                                           turbo_error *err);
    /**
     * Bind a named tensor (RUN). `buffer` is a handle from this provider's `buffer_alloc`/`buffer_import`.
     */
    int32_t (*session_bind)(void *session,
                            turbo_text name,
                            void *buffer,
                            turbo_error *err);
    /**
     * Execute. The result arrays are borrowed until the next run or release.
     */
    int32_t (*session_run)(void *session,
                           const turbo_run_options *opts,
                           struct turbo_provider_result *out,
                           turbo_error *err);
    /**
     * Counters.
     */
    int32_t (*session_stats)(void *session,
                             turbo_session_stats *out,
                             turbo_error *err);
    /**
     * Release a session.
     */
    void (*session_release)(void *session);
    /**
     * Create a generation. Optional; NULL means the provider does not generate.
     */
    int32_t (*generation_create)(void *model,
                                 const turbo_generate_desc *desc,
                                 void **out,
                                 turbo_error *err);
    /**
     * Apply the chat template and tokenize.
     */
    int32_t (*generation_prompt)(void *generation,
                                 const turbo_message *messages,
                                 uint32_t count,
                                 turbo_error *err);
    /**
     * Use caller-supplied prompt tokens.
     */
    int32_t (*generation_prompt_tokens)(void *generation,
                                        const int32_t *ids,
                                        uint32_t count,
                                        turbo_error *err);
    /**
     * Next chunk. Pointers in `out` stay valid until the next call on this generation.
     */
    int32_t (*generation_step)(void *generation,
                               turbo_generation_chunk *out,
                               turbo_error *err);
    /**
     * Cancel.
     */
    void (*generation_cancel)(void *generation);
    /**
     * Release a generation.
     */
    void (*generation_release)(void *generation);
} turbo_provider_vtbl;

/**
 * Signature of the exported `turbo_provider_get` symbol. `core_abi_version`
 * is the core's `TURBO_ABI_VERSION`; return NULL if unsupported.
 */
typedef const struct turbo_provider_vtbl *(*turbo_provider_get_fn)(uint32_t core_abi_version);

#endif  /* TURBO_PROVIDER_H */
