/* SPDX-License-Identifier: Apache-2.0
 *
 * Turbo C ABI, version 2. One header for every provider and every binding.
 *
 * Conventions:
 *   - Every descriptor starts with uint32_t struct_size = sizeof(descriptor).
 *     The library reads only fields below that size. Appended fields have a
 *     zero value meaning "old behavior". Sizes larger than the library knows
 *     are rejected with TURBO_E_INVALID_STRUCT_SIZE.
 *   - Enumerations are uint32_t constants. Unknown values are rejected with
 *     TURBO_E_INVALID_ENUM, never mapped to a default.
 *   - Strings are UTF-8 pointer+length views (turbo_text), valid for the
 *     duration of the call. Invalid UTF-8 is TURBO_E_INVALID_UTF8.
 *   - Errors go to the caller-owned turbo_error (may be NULL). There is no
 *     thread-local or shared error state.
 *   - Handles are opaque and reference counted. A child handle retains its
 *     parent; releasing a parent never invalidates a child. Release functions
 *     accept NULL.
 *   - Runtime, context, model, tokenizer: any thread. Session, generation,
 *     result: single owner; a concurrent call returns TURBO_E_BUSY.
 *   - Every per-call option maps to a TURBO_CAP_* bit. A provider honors the
 *     option exactly or the call fails with TURBO_E_UNSUPPORTED_OPTION and
 *     turbo_error.field names the option. Nothing is silently ignored.
 *   - AUTO device selection never picks a CPU. CPU runs only when selected.
 */

#ifndef TURBO_H
#define TURBO_H

/* Generated by cbindgen from crates/turbo-abi and crates/turbo-capi. Do not edit; run scripts/gen-header.sh. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include <stddef.h>
#include <stdint.h>
#include <stdbool.h>
#include "turbo_types.h"

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * ABI version compiled into this library.
 */
uint32_t turbo_abi_version(void);

/**
 * Library version as a static C string (`major.minor.patch[-pre]`).
 */
const char *turbo_version(void);

/**
 * Symbolic name of a status code. Static, never NULL.
 */
const char *turbo_status_name(int32_t code);

/**
 * Create a runtime. `desc` may be NULL for defaults.
 */
int32_t turbo_runtime_create(const turbo_runtime_desc *desc,
                             turbo_runtime **out,
                             turbo_error *err);

/**
 * Release a runtime. NULL is a no-op. Contexts keep it alive.
 */
void turbo_runtime_release(turbo_runtime *rt);

/**
 * Load a provider library (`turbo_provider.h`) and register its devices.
 * The library stays loaded for the runtime's lifetime. A provider whose id
 * is already registered is rejected with `TURBO_E_PROVIDER_LOAD`.
 */
int32_t turbo_runtime_load_provider(turbo_runtime *rt,
                                    turbo_text path,
                                    turbo_error *err);

/**
 * Number of enumerated devices.
 */
int32_t turbo_runtime_device_count(turbo_runtime *rt,
                                   uint32_t *out,
                                   turbo_error *err);

/**
 * Static info for device `index`.
 */
int32_t turbo_runtime_device_info(turbo_runtime *rt,
                                  uint32_t index,
                                  turbo_device_info *out,
                                  turbo_error *err);

/**
 * Select a device by policy. `sel` may be NULL for AUTO.
 */
int32_t turbo_runtime_select_device(turbo_runtime *rt,
                                    const turbo_device_selector *sel,
                                    uint32_t *out,
                                    turbo_error *err);

/**
 * Capability cell for (device, task, modality).
 */
int32_t turbo_runtime_capability(turbo_runtime *rt,
                                 uint32_t index,
                                 uint32_t task,
                                 uint32_t modality,
                                 turbo_capability *out,
                                 turbo_error *err);

/**
 * Per-request feasibility: can `bundle_path` run `task`/`modality` on device `index`?
 */
int32_t turbo_can_run(turbo_runtime *rt,
                      uint32_t index,
                      turbo_text bundle_path,
                      uint32_t task,
                      uint32_t modality,
                      turbo_error *err);

/**
 * Create a context on device `index`. `desc` may be NULL.
 */
int32_t turbo_context_create(turbo_runtime *rt,
                             uint32_t index,
                             const turbo_context_desc *desc,
                             turbo_context **out,
                             turbo_error *err);

/**
 * Release a context. Models and buffers keep it alive.
 */
void turbo_context_release(turbo_context *ctx);

/**
 * Device index of a context.
 */
int32_t turbo_context_device(turbo_context *ctx,
                             uint32_t *out,
                             turbo_error *err);

/**
 * Allocate a buffer in the context's memory.
 */
int32_t turbo_buffer_alloc(turbo_context *ctx,
                           const turbo_buffer_desc *desc,
                           turbo_buffer **out,
                           turbo_error *err);

/**
 * Wrap caller memory described by a `turbo_native_handle` in `desc.next`.
 */
int32_t turbo_buffer_import(turbo_context *ctx,
                            const turbo_buffer_desc *desc,
                            turbo_buffer **out,
                            turbo_error *err);

/**
 * Release a buffer.
 */
void turbo_buffer_release(turbo_buffer *buf);

/**
 * Description of a buffer.
 */
int32_t turbo_buffer_get_desc(turbo_buffer *buf,
                              turbo_buffer_desc *out,
                              turbo_error *err);

/**
 * Host pointer for host-visible placements, else `TURBO_E_UNSUPPORTED_PLACEMENT`.
 */
int32_t turbo_buffer_host_ptr(turbo_buffer *buf,
                              void **out,
                              turbo_error *err);

/**
 * Export a native handle of `kind`.
 */
int32_t turbo_buffer_export(turbo_buffer *buf,
                            uint32_t kind,
                            turbo_native_handle *out,
                            turbo_error *err);

/**
 * Load a bundle directory on a context. `desc` may be NULL.
 */
int32_t turbo_model_load(turbo_context *ctx,
                         turbo_text bundle_path,
                         const turbo_model_desc *desc,
                         turbo_model **out,
                         turbo_error *err);

/**
 * Release a model. Sessions and generations keep it alive.
 */
void turbo_model_release(turbo_model *m);

/**
 * What loaded.
 */
int32_t turbo_model_get_info(turbo_model *m,
                             turbo_model_info *out,
                             turbo_error *err);

/**
 * Named tensor `index` in `direction` (RUN models).
 */
int32_t turbo_model_io_info(turbo_model *m,
                            uint32_t direction,
                            uint32_t index,
                            turbo_tensor_info *out,
                            turbo_error *err);

/**
 * Label `index` as a view valid for the model's lifetime.
 */
int32_t turbo_model_label(turbo_model *m,
                          uint32_t index,
                          turbo_text *out,
                          turbo_error *err);

/**
 * Create a session. `desc` may be NULL for model defaults.
 */
int32_t turbo_session_create(turbo_model *m,
                             const turbo_session_desc *desc,
                             turbo_session **out,
                             turbo_error *err);

/**
 * Release a session. Results keep it alive.
 */
void turbo_session_release(turbo_session *s);

/**
 * Tokenize `count` texts into the session's inputs. `opts` may be NULL.
 */
int32_t turbo_session_write_text(turbo_session *s,
                                 const turbo_text *texts_ptr,
                                 uint32_t count,
                                 const turbo_embed_options *opts,
                                 turbo_error *err);

/**
 * Copy caller-prepared tokens into the session's inputs.
 */
int32_t turbo_session_write_tokens(turbo_session *s,
                                   const turbo_token_batch *batch,
                                   turbo_error *err);

/**
 * Write a query and `count` documents for reranking. `opts` may be NULL.
 */
int32_t turbo_session_write_pairs(turbo_session *s,
                                  const turbo_text *query,
                                  const turbo_text *docs,
                                  uint32_t count,
                                  const turbo_rerank_options *opts,
                                  turbo_error *err);

/**
 * Write `count` texts for classification. `opts` may be NULL.
 */
int32_t turbo_session_write_text_classify(turbo_session *s,
                                          const turbo_text *texts_ptr,
                                          uint32_t count,
                                          const turbo_classify_options *opts,
                                          turbo_error *err);

/**
 * Bind a named input or output buffer (RUN models).
 */
int32_t turbo_session_bind(turbo_session *s,
                           turbo_text name,
                           turbo_buffer *buf,
                           turbo_error *err);

/**
 * Execute and lease the result. `opts` may be NULL.
 */
int32_t turbo_session_run(turbo_session *s,
                          const turbo_run_options *opts,
                          turbo_result **out,
                          turbo_error *err);

/**
 * Session counters.
 */
int32_t turbo_session_get_stats(turbo_session *s,
                                turbo_session_stats *out,
                                turbo_error *err);

/**
 * Summary of a result.
 */
int32_t turbo_result_get_info(turbo_result *r,
                              turbo_result_info *out,
                              turbo_error *err);

/**
 * Description of output `index`, including its logical shape.
 */
int32_t turbo_result_output_info(turbo_result *r,
                                 uint32_t index,
                                 turbo_tensor_info *out,
                                 turbo_error *err);

/**
 * Buffer view of output `index`. The view keeps the result lease alive.
 */
int32_t turbo_result_buffer(turbo_result *r,
                            uint32_t index,
                            turbo_buffer **out,
                            turbo_error *err);

/**
 * Blocking copy of output `index` into `dst` (`capacity` bytes). Writes the
 * byte count to `written` if non-NULL.
 */
int32_t turbo_result_read(turbo_result *r,
                          uint32_t index,
                          void *dst,
                          uint64_t capacity,
                          uint64_t *written,
                          turbo_error *err);

/**
 * Copy up to `capacity` spans into `dst` and report the total available in `count`.
 */
int32_t turbo_result_spans(turbo_result *r,
                           turbo_span *dst,
                           uint32_t capacity,
                           uint32_t *count,
                           turbo_error *err);

/**
 * Release a result and return its lease (once every view is released too).
 */
void turbo_result_release(turbo_result *r);

/**
 * Create a generation on a generative model. `desc` may be NULL.
 */
int32_t turbo_generation_create(turbo_model *m,
                                const turbo_generate_desc *desc,
                                turbo_generation **out,
                                turbo_error *err);

/**
 * Apply the chat template to `count` messages and tokenize.
 */
int32_t turbo_generation_prompt(turbo_generation *g,
                                const turbo_message *messages,
                                uint32_t count,
                                turbo_error *err);

/**
 * Use `count` caller-supplied prompt token ids.
 */
int32_t turbo_generation_prompt_tokens(turbo_generation *g,
                                       const int32_t *ids,
                                       uint32_t count,
                                       turbo_error *err);

/**
 * Produce the next chunk. Pointers in `out` stay valid until the next call on `g`.
 */
int32_t turbo_generation_step(turbo_generation *g,
                              turbo_generation_chunk *out,
                              turbo_error *err);

/**
 * Cancel; the next step reports `TURBO_FINISH_CANCELLED`.
 */
int32_t turbo_generation_cancel(turbo_generation *g,
                                turbo_error *err);

/**
 * Release a generation.
 */
void turbo_generation_release(turbo_generation *g);

/**
 * Push-style generation over the pull iterator: creates a generation,
 * applies `messages`, and calls `callback` with every chunk until the
 * generation finishes or the callback returns `TURBO_STREAM_STOP`. The
 * chunk and its pointers are valid during the callback only. A stopped
 * generation is cancelled and released before this returns `TURBO_OK`; a
 * callback result other than `TURBO_STREAM_CONTINUE` or
 * `TURBO_STREAM_STOP` is `TURBO_E_INVALID_ARGUMENT`.
 */
int32_t turbo_generate(turbo_model *m,
                       const turbo_generate_desc *desc,
                       const turbo_message *messages,
                       uint32_t count,
                       turbo_stream_fn callback,
                       void *user_data,
                       turbo_error *err);

/**
 * Load the tokenizer a bundle declares (`tokenizer.files["tokenizer.json"]`).
 * Tokenizers are thread-safe and independent of any device.
 */
int32_t turbo_tokenizer_create(turbo_runtime *rt,
                               turbo_text bundle_path,
                               turbo_tokenizer **out,
                               turbo_error *err);

/**
 * Release a tokenizer.
 */
void turbo_tokenizer_release(turbo_tokenizer *t);

/**
 * Static facts about a tokenizer.
 */
int32_t turbo_tokenizer_get_info(turbo_tokenizer *t,
                                 turbo_tokenizer_info *out,
                                 turbo_error *err);

/**
 * Encode `count` texts into caller-owned row-major `[count, row_stride]`
 * arrays. Rows are padded with the pad id and mask 0 to `pad_to` (or to
 * `row_stride` when `pad_to` is 0). `types` and `lengths` may be NULL;
 * `lengths` receives each row's live token count. `opts` may be NULL.
 */
int32_t turbo_tokenizer_encode(turbo_tokenizer *t,
                               const turbo_text *texts_ptr,
                               uint32_t count,
                               const turbo_encode_options *opts,
                               int32_t *ids,
                               int32_t *mask,
                               int32_t *types,
                               uint32_t row_stride,
                               uint32_t *lengths,
                               turbo_error *err);

/**
 * Decode `count` ids into `dst` (`capacity` bytes, not NUL-terminated).
 * Writes the byte length to `written`; if `capacity` is too small, returns
 * `TURBO_E_CAPACITY` with the required length in `written`.
 */
int32_t turbo_tokenizer_decode(turbo_tokenizer *t,
                               const int32_t *ids,
                               uint32_t count,
                               uint32_t skip_special_tokens,
                               char *dst,
                               uint64_t capacity,
                               uint64_t *written,
                               turbo_error *err);

/**
 * Number of tokens `text` produces, without truncation or prefix.
 */
int32_t turbo_tokenizer_count(turbo_tokenizer *t,
                              turbo_text text_in,
                              uint32_t add_special_tokens,
                              uint32_t *out,
                              turbo_error *err);

/**
 * Plan chunks over `text` with `tokenizer` counting content tokens. The
 * plan stores byte offsets only; the caller keeps the text.
 */
int32_t turbo_chunk_plan_create(const turbo_chunk_desc *desc,
                                turbo_text text_in,
                                turbo_tokenizer *tokenizer,
                                turbo_chunk_plan **out,
                                turbo_error *err);

/**
 * Number of chunks in a plan.
 */
int32_t turbo_chunk_plan_count(turbo_chunk_plan *p,
                               uint32_t *out,
                               turbo_error *err);

/**
 * Chunk `index` of a plan.
 */
int32_t turbo_chunk_plan_get(turbo_chunk_plan *p,
                             uint32_t index,
                             turbo_chunk *out,
                             turbo_error *err);

/**
 * Release a chunk plan.
 */
void turbo_chunk_plan_release(turbo_chunk_plan *p);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* TURBO_H */


